// De-Slop Spanish (es) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for Spanish-language content
// ChatGPT in Spanish has distinctive overused phrases - these are the real ones

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.es = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in Spanish - phrases that appear constantly in LLM-generated Spanish text
  tier1: [
    // Signature ChatGPT Spanish phrases - the most blatant tells
    /\ben el (cambiante|dinámico|complejo|vertiginoso) panorama\b/gi,
    /\bpanorama (en constante|siempre) (cambio|evolución|transformación)\b/gi,
    /\bnavegar (el|por el|este) (complejo )?(panorama|mundo|entorno|paisaje)\b/gi,
    /\badentrándonos en\b/gi,
    /\bprofundizando en (las|los|la|el)? ?(complejidades|entresijos|matices)\b/gi,
    /\bun viaje transformador\b/gi,
    /\bembarcarnos en (este|un|nuestro) viaje\b/gi,
    /\btapiz de\b/gi,
    /\bel (poder|la belleza|la importancia) reside en\b/gi,
    /\bin fine de cuentas,? (la )?(decisión|elección) es (tuya|suya|vuestra)\b/gi,
    /\benfoque (holístico|integral)\b/gi,
    /\bintegra(r|ción|ndo)se? (sin fisuras|perfectamente|a la perfección)\b/gi,
    /\bdesbloquear (el potencial|nuevas posibilidades|el poder)\b/gi,
    /\bfomentar (la innovación|el crecimiento|la colaboración)\b/gi,
    /\bmatices? (de comprensión|del enfoque|de la perspectiva)\b/gi,
    /\batención meticulosa\b/gi,
    /\bpaisaje en (constante|rápida) evolución\b/gi,
    /\bentorno (dinámico|cambiante|complejo)\b/gi,
    /\bpapel fundamental\b/gi,
    /\ben el gran esquema de las cosas\b/gi,
    /\bpilar(es)? (fundamental(es)?|clave)\b/gi,
    /\bconclusiones? clave\b/gi,
    /\bexplorar (los|las|las )?(diversas? )?(facetas?|aristas?) de\b/gi,
    /\bpotencial transformador\b/gi,
    /\bcambia(dor|r) de juego\b/gi,
    /\bcambio de paradigma\b/gi,
    /\bsin precedentes\b/gi,
    /\bsolución (robusta|integral|sólida)\b/gi,
    /\bguía (completa|exhaustiva|detallada)\b/gi,
    /\baprovecha(r|ndo) el poder\b/gi,
    /\bes (importante|esencial|fundamental) (tener en cuenta|señalar|destacar|comprender) que\b/gi,
    /\nen este (artículo|post|texto),? (veremos|exploraremos|analizaremos)\b/gi,
    /\ba lo largo de (este|el) (artículo|post|texto|análisis)\b/gi,
    /\bcomo (modelo de lenguaje|asistente de IA)\b/gi,
    /\bno (puede|puedo|podemos) (subestimarse|ignorarse)\b/gi,
    /\bsumergirse en\b/gi,
    /\barrojar luz sobre\b/gi,
    /\bsin parangón\b/gi,
    /\btesoro (de información|de recursos|de conocimiento)\b/gi,
    /\bterreno inexplorado\b/gi,
    /\bde (última|última) generación\b/gi,
    /\bde vanguardia\b/gi,
    /\bla próxima frontera\b/gi,
    /\bprovocador de reflexión\b/gi,
    /\bal fin y al cabo\b/gi,
    /\ben conclusión\b/gi,
    /\ben (resumen|síntesis)\b/gi,
    /\bpara resumir\b/gi,
    /\bde cara al futuro\b/gi,
    /\bavanzando\b/gi,

    // Structural patterns in Spanish
    /^(En conclusión|En resumen|Para resumir|En definitiva),?\s/mi,
    /\bNo solo .{10,50} sino (también|que)?\b/gi,
    /\bA pesar de (sus|su|los|las) .{5,30},? .{5,30} (enfrenta|presenta) desafíos\b/gi,
    /\bPerspectivas de futuro:?\b/gi,

    // AI antithesis patterns in Spanish
    /\bNo (se trata|es) (solo|únicamente|simplemente) de .{5,40}[,;] (se trata|es) de\b/gi,
    /\bNo es .{5,40}[,;] es .{5,40}\b/gi,
    /\bNo .{5,40}[,;] sino .{5,40}\b/gi,
    /\bMenos .{5,30}[,;] más .{5,30}\b/gi,
    /\bOlvida (que|el|la) .{5,30}[,;] (abraza|piensa en|céntrate en) .{5,30}\b/gi,

    // Excessive transition words (Spanish)
    /\b(Además|Por otra parte|Asimismo|Por consiguiente|Sin embargo|No obstante),?\s/gi,
    /\b(Cabe destacar|Cabe señalar|Es importante señalar|Hay que destacar) que\b/gi,
    /\b(Huelga decir|No hace falta decir|Sobra decir) que\b/gi,

    // Generic openers in Spanish
    /^En (el mundo|la era) (de hoy|actual|moderna),?\s/mi,
    /^(En|Con|A través de) .{20,60}(sigue|ha (llegado a ser|se ha convertido en)|se está convirtiendo en)\b/mi,

    // Listicle patterns in Spanish
    /\b\d+\s+(formas|razones|consejos|trucos|secretos|beneficios|ventajas)\s+(para|de)\b/gi,
    /\b(Las?|Los?) (mejores?|principales?)\s+\d+\b/gi,
    /\bGuía (definitiva|completa|exhaustiva) (para|de|sobre)\b/gi,
    /\bTodo lo que (necesitas|debes) saber (sobre|acerca de)\b/gi,
    /\bGuía (para principiantes|del principiante) (sobre|de|para)\b/gi,

    // Unearned profundity in Spanish
    /\bAlgo (cambió|ha cambiado)\b/gi,
    /\bTodo (cambió|ha cambiado)\b/gi,
    /\bPero aquí está la clave\b/gi,
    /\bEsto es lo que (aprendí|aprendimos)\b/gi,

    // AI content mill phrases in Spanish
    /\bavance(s)? (revolucionario|sin precedentes)\b/gi,
    /\bsalto (gigante|cuántico|monumental)\b/gi,
    /\bposibilidades (emocionantes|apasionantes)\b/gi,
    /\bpace (vertiginoso|acelerado|frenético)\b/gi,
    /\btecnología (avanzada|de última generación|punta)\b/gi,
    /\bresultados (sorprendentes|impresionantes|extraordinarios)\b/gi,
    /\bimpacto (real|en el mundo real|tangible)\b/gi,
    /\bestá claro que\b/gi,
    /\bdesde .{5,30} hasta .{5,30}, (esto|esta|este)\b/gi,
    /\bImagina .{10,50} — eso es\b/gi,
    /\bPor (décadas|años), .{10,50} (parecía|parecían)\b/gi,

    // Additional AI tells in Spanish
    /\bel panorama (está|se está) (cambiando|transformando|evolucionando) (constantemente|rápidamente)\b/gi,
    /\bcrucial (entender|señalar|reconocer|comprender)\b/gi,
    /\bvital (entender|señalar|reconocer|comprender)\b/gi,
    /\bimportante (entender|señalar|reconocer|recordar) que\b/gi,
    /\bvale la pena (mencionar|señalar|destacar) que\b/gi,
    /\bse debe (considerar|entender|reconocer)\b/gi,
    /\btrayectoria probada\b/gi,
    /\btradición (arraigada|consolidada|longeva)\b/gi,
    /\bmirar hacia el futuro\b/gi,
    /\bdar forma al futuro (de|del)\b/gi,
    /\bpreparado para (convertirse|transformar|revolucionar)\b/gi,
    /\ben (el umbral|la cúspide|el borde) de\b/gi,
    /\banuncia(r)? una nueva (era|época|etapa)\b/gi,
    /\bmarca(r)? un (punto de inflexión|momento decisivo)\b/gi,
    /\bpunto de inflexión\b/gi,
    /\bmomento decisivo\b/gi,
    /\btormenta perfecta de\b/gi,
    /\bconvergencia de\b/gi,
    /\bintersección de\b/gi,
    /\ben la (encrucijada|vanguardia) de\b/gi,
    /\blider(ar|ando) (el|la)\b/gi,
    /\bpionero(s)? en\b/gi,
    /\bsin igual\b/gi,
    /\bcrecimiento exponencial\b/gi,
    /\boportunidad única\b/gi,
    /\bindudablemente\b/gi,
    /\binnegablemente\b/gi,
    /\bindiscutiblemente\b/gi,
    /\bsin lugar a dudas\b/gi,
    /\bsobra decir\b/gi,
    /\ben pocas palabras\b/gi,
    /\ber resumidas cuentas\b/gi,
    /\bdicho esto,\b/gi,
    /\ben este momento\b/gi,
    /\bganando (tracción|impulso|terreno)\b/gi,
    /\ben ascenso\b/gi,
    /\bcrecimiento (explosivo|meteórico|vertiginoso)\b/gi,
    /\bauge meteórico\b/gi,
    /\bcrecimiento sin precedentes\b/gi,
    /\béxito sin parangón\b/gi,
    /\brecord histórico\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Estoy|Me siento|Estamos) (muy )?(emocionado|emocionada|orgulloso|orgullosa|encantado|encantada|honrado|honrada|feliz|contento|contenta) de (anunciar|compartir|presentar|revelar|contarles)/gim,
    /^(No puedo|No podemos) esperar (para|a) (compartir|contarles|anunciar|presentar|revelar)/gim,
    /^(¡Grandes|¡Emocionantes|¡Fantásticas|¡Increíbles) noticias[!:]/gim,
    /^Acaba(mos)? de lanzar\b/gim,
    /^(Hoy|Esta semana|Este mes) (estoy|estamos) (anunciando|lanzando|presentando|compartiendo|emocionado de)\b/gim,
    /^Emocionado(a)? de (compartir|anunciar|presentar|revelar)\b/gim,
    /^Orgulloso(a)? de (compartir|anunciar|presentar|revelar)\b/gim,
    /^Encantado(a)? de (compartir|anunciar|presentar|revelar)\b/gim,
    /^Feliz de (compartir|anunciar|presentar|revelar)\b/gim,
    /^Honrado(a)? de (compartir|anunciar|presentar|revelar)\b/gim,
    /^¿Adivinen qué[!?]/gim,
    /^No (van|vas) a (creer|poder creer)\b/gim,
    /^(Miren|Mira|Echa un vistazo a) (esto|lo que)\b/gim,
    /^(¡Gran|¡Enorme) anuncio[!:]/gim,
    /^(¡Por fin|¡Al fin)[,!]/gim,
    /^(Noticias de última hora|Noticias calientes)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in Spanish (2 points per match)
  tier2: [
    /\bsinergias?\b/gi,
    /\bapalancar(se)?\b/gi,
    /\bhacer un seguimiento\b/gi,
    /\bfruta(s)? al alcance de la mano\b/gi,
    /\bmover la aguja\b/gi,
    /\bpensar fuera de la caja\b/gi,
    /\bponerse en contacto\b/gi,
    /\bpivotar\b/gi,
    /\bdisruptiv(o|a|os|as)\b/gi,
    /\bescalar\b/gi,
    /\bágil\b/gi,
    /\bcapacidad (disponible|instalada)\b/gi,
    /\bcompetencias? (clave|núcleo|esencial)\b/gi,
    /\bpartes? interesadas?\b/gi,
    /\bpropuesta de valor\b/gi,
    /\blíder de (opinión|pensamiento)\b/gi,
    /\bbuenas prácticas?\b/gi,
    /\btransformación digital\b/gi,
    /\bimpulsado por IA\b/gi,
    /\bbasado en la nube\b/gi,
    /\borientado al (cliente|datos?)\b/gi,
    /\bventaja competitiva\b/gi,
    /\bcuota de mercado\b/gi,
    /\bROI\b/gi,
    /\bKPI\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\bproductos? entregables?\b/gi,
    /\bpuntos? de acción\b/gi,
    /\bempodera(r|miento)\b/gi,
    /\bimpulsar la innovación\b/gi,
    /\bfomentar\b/gi,
    /\boptimizar\b/gi,
    /\boptimización\b/gi,
    /\bmaximizar\b/gi,
    /\balinea(ción|miento|r)\b/gi,
    /\bsinergia\b/gi,
    /\bcolabora(ción|r)\b/gi,
    /\btransversal\b/gi,
    /\bsolución integral\b/gi,
    /\bde extremo a extremo\b/gi,
    /\bnativo en la nube\b/gi,
    /\bcontenerizado\b/gi,
    /\bmicroservicios\b/gi,
    /\bserverless\b/gi,
    /\bimpulsado por (datos|eventos)\b/gi,
    /\btiempo real\b/gi,
    /\balta (disponibilidad|performance|rendimiento)\b/gi,
    /\bescalable\b/gi,
    /\bmodular\b/gi,
    /\bflexible\b/gi,
    /\bfácil de usar\b/gi,
    /\bintuitivo\b/gi,
    /\bexperiencia de usuario\b/gi,
    /\btransformación del negocio\b/gi,
    /\becosistema (digital|tecnológico)\b/gi,
    /\bplataforma (digital|tecnológica|integrada)\b/gi,
    /\bsolución end-to-end\b/gi,
    /\bgestión del cambio\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Clichés in Spanish (1 point per match)
  tier3: [
    /\bgratis\b/gi,
    /\bgarantizado\b/gi,
    /\bincreíble\b/gi,
    /\balucinante\b/gi,
    /\bincreidíble\b/gi,
    /\bimpresionante\b/gi,
    /\brevolucionario\b/gi,
    /\bmilagroso\b/gi,
    /\blo mejor de su clase\b/gi,
    /\bde primer nivel\b/gi,
    /\bde última tecnología\b/gi,
    /\bhaz clic aquí\b/gi,
    /\bcompra ahora\b/gi,
    /\bactúa (ahora|de inmediato)\b/gi,
    /\boferta por tiempo limitado\b/gi,
    /\bno esperes\b/gi,
    /\buna vez en la vida\b/gi,
    /\bsin compromiso\b/gi,
    /\bsin riesgo\b/gi,
    /\bduplica tus ingresos\b/gi,
    /\bgana (dinero|plata)\b/gi,
    /\bdinero rápido\b/gi,
    /\bresultados comprobados\b/gi,
    /\bpromoción especial\b/gi,
    /\bahorra a lo grande\b/gi,
    /\bprecio más bajo\b/gi,
    /\bmejor (oferta|precio|deal)\b/gi,
    /\bsin costo\b/gi,
    /\bconsulta gratuita\b/gi,
    /\bimprescindible\b/gi,
    /\bal siguiente nivel\b/gi,
    /\belevar el listón\b/gi,
    /\bdestacar entre la multitud\b/gi,
    /\bdifundirse como la pólvora\b/gi,
    /\bla punta del iceberg\b/gi,
    /\bcontenido es el rey\b/gi,
    /\bcorrer desde el principio\b/gi,
    /\ben pocas palabras\b/gi,
    /\bbásicamente\b/gi,
    /\besencialmente\b/gi,
    /\bactualmente\b/gi,
    /\bfantástico\b/gi,
    /\bespectacular\b/gi,
    /\bfenomenal\b/gi,
    /\bextraordinario\b/gi,
    /\bsensacional\b/gi,
    /\bsorprendente\b/gi,
    /\bmaravilloso\b/gi,
    /\bepico\b/gi,
    /\blegendario\b/gi,
    /\bexclusivo acceso\b/gi,
    /\bsolo por invitación\b/gi,
    /\bpronto\b/gi,
    /\bno te (pierdas|lo pierdas)\b/gi,
    /\bFOMO\b/gi,
    /\bmiedo a perderte algo\b/gi,
    /\bdate prisa\b/gi,
    /\btruco(s)?\b/gi,
    /\bconsejo(s)? y truco(s)?\b/gi,
    /\bpro-tip(s)?\b/gi,
    /\bhack de vida\b/gi,
    /\bhack de crecimiento\b/gi,
    /\bplan paso a paso\b/gi,
    /\bsistema (probado|comprobado)\b/gi,
    /\bfácil como\b/gi,
    /\brápido y sencillo\b/gi,
    /\ben solo \d+ (minutos?|horas?|días?)\b/gi,
    /\béxito de la noche a la mañana\b/gi,
    /\bresultados inmediatos\b/gi,
    /\bcomienza (hoy|gratis|ahora)\b/gi,
    /\bregistrate (ahora|gratis)\b/gi,
    /\búnete (ahora|gratis|miles|millones)\b/gi,
    /\b(miles|millones|miles de millones) de (usuarios|clientes|personas)\b/gi,
    /\bpremio (ganado|obtenido)\b/gi,
    /\btransforma tu (vida|negocio|carrera)\b/gi,
    /\bcambia tu vida\b/gi,
    /\bdesbloquea tu (potencial|éxito)\b/gi
  ],

  // Political content patterns - Spanish/Latin American political context
  political: [
    /\b(política|político|políticos|políticas|partidista)\b/gi,
    /\b(demócrata|republicano|liberal|conservador|libertario|socialista|comunista|marxista|fascista)\b/gi,
    /\b(izquierda|derecha|centro[- ]izquierda|centro[- ]derecha|extrema (izquierda|derecha))\b/gi,
    /\b(progresista|populista|nacionalista|globalista)\b/gi,
    /\b(congreso|senado|parlamento|tribunal supremo|corte suprema)\b/gi,
    /\b(elecciones?|votar|votación|urna|campaña|candidatura|primarias?)\b/gi,
    /\b(legislación|proyecto de ley|ley|decreto|veto)\b/gi,
    /\b(impeachment|destitución|juicio político)\b/gi,
    /\b(presidente|senador|diputado|político|candidato)\b/gi,
    /\b(gobierno|casa (blanca|rosada)|palacio (nacional|presidencial)|estado)\b/gi,
    /\b(inflación|recesión|depresión|estímulo (económico)?)\b/gi,
    /\b(banco central|reserva federal|tasas? de interés)\b/gi,
    /\b(rescate|deuda pública|techo de deuda)\b/gi,
    /\b(presupuesto|déficit|deuda nacional)\b/gi,
    /\b(aranceles?|sanciones?|guerra comercial)\b/gi,
    /\b(tasa de desempleo|informe de (empleo|trabajo))\b/gi,
    /\b(aborto|pro[- ]vida|pro[- ]elección)\b/gi,
    /\b(control de armas|segunda enmienda|portación de armas)\b/gi,
    /\b(inmigración|crisis (migratoria|fronteriza)|indocumentado|migrante ilegal)\b/gi,
    /\b(cambio climático|calentamiento global|pacto verde)\b/gi,
    /\b(sanidad|salud universal|sistema de salud público)\b/gi,
    /\b(reforma fiscal|recortes? fiscales?|impuestos)\b/gi,
    /\b(cultura de la cancelación|corrección política|identitarismo)\b/gi,
    /\b(teoría crítica de la raza|diversidad e inclusión|DEI|equidad)\b/gi,
    /\b(derechos (trans|LGBTQ|de género))\b/gi,
    /\b(censura|libertad de expresión|primera enmienda)\b/gi,
    /\b(patriota|nacionalismo|estado profundo|globalismo)\b/gi,
    /\b(despertad|masa dormida|sheeple)\b/gi,
    /\b(medios (de comunicación|corporativos)|noticias falsas|propaganda)\b/gi,
    /\b(conspiración|encubrimiento|la verdad que)\b/gi,
    /\b(soberanía nacional|libertad|tiranía|autocracia)\b/gi,
    /\b(agenda (socialista|comunista)|régimen)\b/gi,
    /\b(destruyendo (la democracia|el país|la nación))\b/gi,
    /\b(amenaza (a la democracia|a la libertad))\b/gi,
    /\b(guerra contra (la iglesia|la religión|los valores))\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'adentrándonos en': 'explorar, examinar, analizar',
    'profundizando en las complejidades': 'examinar en detalle, analizar',
    'navegar el panorama': 'entender la situación, explorar el campo',
    'cambio de paradigma': 'cambio importante, transformación fundamental',
    'cambiador de juego': 'avance significativo, desarrollo importante',
    'potencial transformador': 'describe el cambio real que ocurre',
    'desbloquear el potencial': 'permitir, posibilitar, hacer posible',
    'integrarse sin fisuras': 'integrar, combinar, funcionar juntos',
    'enfoque holístico': 'método completo, estrategia integral',
    'solución robusta': 'sistema fiable, enfoque sólido',
    'sumergirse en': 'análisis detallado, examen exhaustivo',
    'tapiz de': 'colección de, mezcla de',
    'sin precedentes': 'explica qué lo hace único',
    'pionero en': 'innovador, nuevo, explica la innovación',
    'tesoro de información': 'colección, recurso, fuente',
    'terreno inexplorado': 'territorio nuevo, área sin explorar',
    'arrojar luz sobre': 'explicar, aclarar, revelar',
    'al fin y al cabo': 'en definitiva, finalmente',
    'de cara al futuro': 'en el futuro, a continuación, desde ahora',
    'conclusiones clave': 'puntos principales, resumen, conclusiones',
    'avance sin precedentes': 'explica qué barrera se superó',
    'está claro que': 'expresa tu punto directamente',
    'estoy emocionado de anunciar': 'anunciar directamente',
    'orgulloso de compartir': 'compartir sin autoelogio',
    'sinergias': 'colaboración, cooperación',
    'apalancar': 'usar, aplicar, aprovechar',
    'hacer un seguimiento': 'hacer seguimiento, volver a, revisar',
    'fruta al alcance de la mano': 'victorias fáciles, tareas simples',
    'mover la aguja': 'progresar, generar impacto',
    'pensar fuera de la caja': 'ser creativo, innovar',
    'pivotar': 'cambiar de dirección, ajustar la estrategia',
    'disruptivo': 'explica lo que cambia',
    'partes interesadas': 'personas involucradas, miembros del equipo',
    'líder de opinión': 'experto, especialista, autoridad',
    'buenas prácticas': 'métodos efectivos',
    'empoderamiento': 'permitir, habilitar',
    'optimizar': 'mejorar, perfeccionar',
    'increíble': 'usa descriptores específicos',
    'básicamente': 'elimínalo o sé más preciso',
    'esencialmente': 'elimínalo o sé más específico'
  },

  checkerSuggestions: {
    'adentrándonos en': 'Intenta: "explorar", "examinar", o sé específico sobre lo que estás haciendo',
    'navegar el panorama': 'Sé específico: ¿A qué situación o campo te refieres exactamente?',
    'cambio de paradigma': 'Usa términos concretos: ¿Qué cambió específicamente?',
    'cambiador de juego': 'Explica por qué importa en lugar de usar jerga',
    'potencial transformador': 'Describe la transformación real',
    'apalancar': 'Intenta: "usar", "aplicar" o "aprovechar"',
    'sinergias': 'Explica la colaboración o el beneficio real',
    'hacer un seguimiento': 'Di: "hacer seguimiento", "volver a" o "revisar"',
    'sumergirse en': 'Di: "análisis detallado" o "examen exhaustivo"',
    'desbloquear': 'Sé específico sobre lo que se hace posible',
    'sin fisuras': 'Muestra cómo se integra en lugar de afirmar que lo hace',
    'robusta': 'Describe las características o fortalezas reales',
    'exhaustiva': 'Enumera lo que cubre',
    'holístico': 'Explica cómo consideras todos los aspectos',
    'disruptivo': 'Explica lo que cambia y cómo',
    'sin precedentes': 'Si es verdad, explica qué lo hace único',
    'increíble': 'Usa descriptores específicos y medibles',
    'estoy emocionado de anunciar': 'Salta el relleno de marketing. Anuncia directamente lo que estás compartiendo.',
    'orgulloso de compartir': 'Omite el autoelogio. Deja que el contenido hable por sí mismo.',
    '—': 'Los guiones largos son una señal reveladora de contenido generado por IA. Usa puntuación simple.'
  },

  slopDatabase: [
    { slop: 'adentrándonos en', better: 'explorar, examinar o analizar', tier: 'tier1' },
    { slop: 'navegar el panorama', better: 'entender la situación, explorar el campo', tier: 'tier1' },
    { slop: 'cambio de paradigma', better: 'cambio importante, transformación fundamental', tier: 'tier1' },
    { slop: 'cambiador de juego', better: 'avance significativo, desarrollo importante', tier: 'tier1' },
    { slop: 'potencial transformador', better: 'describe el cambio real que ocurre', tier: 'tier1' },
    { slop: 'desbloquear el potencial', better: 'permitir, posibilitar, hacer posible', tier: 'tier1' },
    { slop: 'integrarse sin fisuras', better: 'integrar, combinar, funcionar juntos', tier: 'tier1' },
    { slop: 'enfoque holístico', better: 'método completo, estrategia integral', tier: 'tier1' },
    { slop: 'solución robusta', better: 'sistema fiable, enfoque sólido', tier: 'tier1' },
    { slop: 'sumergirse en', better: 'análisis detallado, examen exhaustivo', tier: 'tier1' },
    { slop: 'tapiz de', better: 'colección de, mezcla de', tier: 'tier1' },
    { slop: 'sin precedentes', better: 'raro, inusual, o explica qué lo hace único', tier: 'tier1' },
    { slop: 'pionero en', better: 'innovador, nuevo, o explica la innovación', tier: 'tier1' },
    { slop: 'tesoro de información', better: 'colección, recurso, fuente', tier: 'tier1' },
    { slop: 'terreno inexplorado', better: 'territorio nuevo, área sin explorar', tier: 'tier1' },
    { slop: 'arrojar luz sobre', better: 'explicar, aclarar, revelar', tier: 'tier1' },
    { slop: 'al fin y al cabo', better: 'en definitiva, finalmente, en conclusión', tier: 'tier1' },
    { slop: 'de cara al futuro', better: 'en el futuro, a continuación, desde ahora', tier: 'tier1' },
    { slop: 'conclusiones clave', better: 'puntos principales, resumen, conclusiones', tier: 'tier1' },
    { slop: 'avance sin precedentes', better: 'explica qué barrera se superó', tier: 'tier1' },
    { slop: 'está claro que', better: 'expresa tu punto directamente sin el preámbulo', tier: 'tier1' },
    { slop: 'estoy emocionado de anunciar', better: 'anunciarlo directamente', tier: 'stopwords' },
    { slop: 'orgulloso de compartir', better: 'compartir sin el envoltorio emocional', tier: 'stopwords' },
    { slop: 'encantado de presentar', better: 'elimina el autoelogio', tier: 'stopwords' },
    { slop: 'sinergias', better: 'colaboración, cooperación, esfuerzo conjunto', tier: 'tier2' },
    { slop: 'apalancar', better: 'usar, aplicar, aprovechar', tier: 'tier2' },
    { slop: 'hacer un seguimiento', better: 'hacer seguimiento, volver a, revisar', tier: 'tier2' },
    { slop: 'fruta al alcance de la mano', better: 'victorias fáciles, tareas simples', tier: 'tier2' },
    { slop: 'mover la aguja', better: 'progresar, generar impacto, mejorar resultados', tier: 'tier2' },
    { slop: 'pivotar', better: 'cambiar de dirección, ajustar la estrategia', tier: 'tier2' },
    { slop: 'disruptivo', better: 'explica lo que cambia y cómo', tier: 'tier2' },
    { slop: 'partes interesadas', better: 'personas involucradas, miembros del equipo', tier: 'tier2' },
    { slop: 'líder de opinión', better: 'experto, especialista, autoridad', tier: 'tier2' },
    { slop: 'buenas prácticas', better: 'métodos efectivos, enfoques probados', tier: 'tier2' },
    { slop: 'empoderamiento', better: 'permitir, habilitar, dar autonomía', tier: 'tier2' },
    { slop: 'optimizar', better: 'mejorar, perfeccionar, hacer más eficiente', tier: 'tier2' },
    { slop: 'increíble', better: 'usa descriptores específicos y medibles', tier: 'tier3' },
    { slop: 'alucinante', better: 'proporciona detalles concretos', tier: 'tier3' },
    { slop: 'revolucionario', better: 'describe el cambio real', tier: 'tier3' },
    { slop: 'básicamente', better: 'elimínalo o sé más preciso', tier: 'tier3' },
    { slop: 'esencialmente', better: 'elimínalo o sé más específico', tier: 'tier3' },
    { slop: 'guion largo (—)', better: 'usa puntos, comas, o elimina la pausa dramática', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\ben el (cambiante|dinámico|complejo|vertiginoso) panorama\\b/gi',
      '/\\bpanorama (en constante|siempre) (cambio|evolución|transformación)\\b/gi',
      '/\\bnavegar (el|por el|este) (complejo )?(panorama|mundo|entorno|paisaje)\\b/gi',
      '/\\badentrándonos en\\b/gi',
      '/\\bprofundizando en (las|los|la|el)? ?(complejidades|entresijos|matices)\\b/gi',
      '/\\bun viaje transformador\\b/gi',
      '/\\bembarcarnos en (este|un|nuestro) viaje\\b/gi',
      '/\\btapiz de\\b/gi',
      '/\\benfoque (holístico|integral)\\b/gi',
      '/\\bintegra(r|ción|ndo)se? (sin fisuras|perfectamente|a la perfección)\\b/gi',
      '/\\bdesbloquear (el potencial|nuevas posibilidades|el poder)\\b/gi',
      '/\\bcambio de paradigma\\b/gi',
      '/\\bsin precedentes\\b/gi',
      '/\\bsolución (robusta|integral|sólida)\\b/gi',
      '/\\bguía (completa|exhaustiva|detallada)\\b/gi',
      '/\\bpotencial transformador\\b/gi',
      '/\\bcambia(dor|r) de juego\\b/gi',
      '/\\bsumergirse en\\b/gi',
      '/\\barrojar luz sobre\\b/gi',
      '/\\bsin parangón\\b/gi',
      '/\\bal fin y al cabo\\b/gi',
      '/\\ben conclusión\\b/gi',
      '/\\ben (resumen|síntesis)\\b/gi',
      '/\\bde cara al futuro\\b/gi',
      '/\\bconclusiones? clave\\b/gi',
      '/\\bes (importante|esencial|fundamental) (tener en cuenta|señalar|destacar|comprender) que\\b/gi',
      '/\\b(Además|Por otra parte|Asimismo|Por consiguiente|Sin embargo|No obstante),?\\s/gi',
      '/\\b(Cabe destacar|Cabe señalar|Es importante señalar|Hay que destacar) que\\b/gi',
      '/\\bcrecimiento exponencial\\b/gi',
      '/\\bpunto de inflexión\\b/gi',
      '/\\bconvergencia de\\b/gi',
      '/\\bestá claro que\\b/gi',
      '/^En (el mundo|la era) (de hoy|actual|moderna),?\\s/mi',
      '/\\bindudablemente\\b/gi',
      '/\\binnegablemente\\b/gi'
    ],
    tier2: [
      '/\\bsinergias?\\b/gi',
      '/\\bapalancar(se)?\\b/gi',
      '/\\bhacer un seguimiento\\b/gi',
      '/\\bpivotar\\b/gi',
      '/\\bdisruptiv(o|a|os|as)\\b/gi',
      '/\\bescalar\\b/gi',
      '/\\bágil\\b/gi',
      '/\\bcompetencias? (clave|núcleo|esencial)\\b/gi',
      '/\\bpartes? interesadas?\\b/gi',
      '/\\bpropuesta de valor\\b/gi',
      '/\\blíder de (opinión|pensamiento)\\b/gi',
      '/\\bbuenas prácticas?\\b/gi',
      '/\\btransformación digital\\b/gi',
      '/\\bimpulsado por IA\\b/gi',
      '/\\borientado al (cliente|datos?)\\b/gi',
      '/\\bventaja competitiva\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI\\b/gi',
      '/\\bempodera(r|miento)\\b/gi',
      '/\\boptimizar\\b/gi',
      '/\\boptimización\\b/gi',
      '/\\bmaximizar\\b/gi',
      '/\\balinea(ción|miento|r)\\b/gi',
      '/\\bcolabora(ción|r)\\b/gi',
      '/\\bsolución integral\\b/gi',
      '/\\bescalable\\b/gi',
      '/\\bfácil de usar\\b/gi',
      '/\\bintuitivo\\b/gi',
      '/\\becosistema (digital|tecnológico)\\b/gi',
      '/\\bgestión del cambio\\b/gi'
    ],
    tier3: [
      '/\\bgratis\\b/gi',
      '/\\bgarantizado\\b/gi',
      '/\\bincreíble\\b/gi',
      '/\\balucinante\\b/gi',
      '/\\bimpresionante\\b/gi',
      '/\\brevolucionario\\b/gi',
      '/\\bhaz clic aquí\\b/gi',
      '/\\bcompra ahora\\b/gi',
      '/\\boferta por tiempo limitado\\b/gi',
      '/\\bno esperes\\b/gi',
      '/\\bsin riesgo\\b/gi',
      '/\\bgana (dinero|plata)\\b/gi',
      '/\\bresultados comprobados\\b/gi',
      '/\\bpromoción especial\\b/gi',
      '/\\bmejor (oferta|precio|deal)\\b/gi',
      '/\\bimprescindible\\b/gi',
      '/\\bal siguiente nivel\\b/gi',
      '/\\ben pocas palabras\\b/gi',
      '/\\bbásicamente\\b/gi',
      '/\\besencialmente\\b/gi',
      '/\\bfantástico\\b/gi',
      '/\\bespectacular\\b/gi',
      '/\\bno te (pierdas|lo pierdas)\\b/gi',
      '/\\bdate prisa\\b/gi',
      '/\\bcomienza (hoy|gratis|ahora)\\b/gi',
      '/\\btransforma tu (vida|negocio|carrera)\\b/gi'
    ]
  }
};
