// De-Slop French (fr) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for French-language content
// ChatGPT in French has distinctive overused phrases - these are the real ones

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.fr = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in French - phrases that appear constantly in LLM-generated French text
  tier1: [
    // Signature ChatGPT French phrases - the most blatant tells
    /\bdans le paysage (en constante|toujours plus|perpétuellement) (évolution|mutation|transformation)\b/gi,
    /\bpaysage (en constante|toujours) évolution\b/gi,
    /\bnaviguer (dans|le|ce) (complexe )?(paysage|monde|environnement)\b/gi,
    /\bplongeons (dans|au cœur de)\b/gi,
    /\bplonger dans (les|la) (complexités|profondeurs|subtilités)\b/gi,
    /\bun voyage transformateur\b/gi,
    /\bse lancer dans (ce|un|notre) voyage\b/gi,
    /\btapisserie de\b/gi,
    /\bil convient de (noter|souligner|mentionner|préciser) que\b/gi,
    /\bil est (important|essentiel|crucial|fondamental) de (noter|souligner|mentionner|préciser|comprendre) que\b/gi,
    /\bil est à (noter|souligner|mentionner) que\b/gi,
    /\ben fin de compte,? (le )?(choix|la décision) vous appartient\b/gi,
    /\bapproche (holistique|globale|intégrée)\b/gi,
    /\bintégrer (de manière|de façon) (transparente|fluide|harmonieuse|seamless)\b/gi,
    /\bdébloquer (le potentiel|de nouvelles possibilités|le pouvoir)\b/gi,
    /\bfavoriser (l'innovation|la croissance|la collaboration)\b/gi,
    /\bnuances? (de compréhension|de l'approche|de la perspective)\b/gi,
    /\battention méticuleuse\b/gi,
    /\bpaysage (en constante|rapide|perpétuelle) évolution\b/gi,
    /\benvironnement (dynamique|en mutation|en évolution)\b/gi,
    /\brôle (crucial|fondamental|essentiel|pivot)\b/gi,
    /\bdans le grand schéma des choses\b/gi,
    /\bpilier(s)? (fondamental|clé|essentiel)\b/gi,
    /\bpoints clés (à retenir|à mémoriser)\b/gi,
    /\bexplorer (les|les )?(diverses? )?(facettes?|dimensions?) de\b/gi,
    /\bpotentiel transformateur\b/gi,
    /\bchanger la donne\b/gi,
    /\bchangement de paradigme\b/gi,
    /\bsans précédent\b/gi,
    /\bsolution (robuste|complète|solide)\b/gi,
    /\bguide (complet|exhaustif|détaillé)\b/gi,
    /\bexploiter la puissance\b/gi,
    /\ble long de (cet|l') article,? (nous allons|nous examinerons|nous analyserons)\b/gi,
    /\bdans (cet|le) (article|billet|texte|analyse),? (nous allons|nous verrons|nous examinerons)\b/gi,
    /\ben tant que (modèle de langage|assistant IA)\b/gi,
    /\bne (peut|saurait) (pas |)être (sous[- ]estimé|ignoré|négligé)\b/gi,
    /\bse plonger dans\b/gi,
    /\bjeter (une|de la) lumière sur\b/gi,
    /\bsans pareil\b/gi,
    /\btrésor (d'informations|de ressources|de connaissances)\b/gi,
    /\bterrain inexploré\b/gi,
    /\bde pointe\b/gi,
    /\bla prochaine frontière\b/gi,
    /\bqui pousse à la réflexion\b/gi,
    /\nen fin de compte\b/gi,
    /\ben conclusion\b/gi,
    /\ben (résumé|bref)\b/gi,
    /\bpour résumer\b/gi,
    /\bà l'avenir\b/gi,
    /\baller de l'avant\b/gi,

    // Structural patterns in French
    /^(En conclusion|En résumé|Pour résumer|En définitive),?\s/mi,
    /\bNon seulement .{10,50} mais (aussi|également)?\b/gi,
    /\bMalgré (ses|leur|les) .{5,30},? .{5,30} (fait face|présente|rencontre) des défis\b/gi,
    /\bPerspectives d'avenir:?\b/gi,

    // AI antithesis patterns in French
    /\bIl ne s'agit pas (seulement|uniquement|simplement) de .{5,40}[,;] il s'agit de\b/gi,
    /\bCe n'est pas .{5,40}[,;] c'est .{5,40}\b/gi,
    /\bNon pas .{5,40}[,;] mais .{5,40}\b/gi,
    /\bMoins .{5,30}[,;] plus .{5,30}\b/gi,
    /\bOubliez .{5,30}[,;] (embrassez|pensez à|concentrez-vous sur) .{5,30}\b/gi,

    // Excessive transition words (French)
    /\b(De plus|Par ailleurs|En outre|Par conséquent|Néanmoins|Cependant),?\s/gi,
    /\b(Il est important de (noter|souligner)|Force est de constater|Il convient de (noter|souligner|préciser)) que\b/gi,
    /\b(Il va sans dire|Il est inutile de dire|Nul besoin de préciser) que\b/gi,

    // Generic openers in French
    /^Dans le monde d'aujourd'hui .{10,40},?\s/mi,
    /^(Dans|Avec|À travers|Pendant|Depuis) .{20,60}(continue à|est devenu|sont devenus|devient)\b/mi,

    // Listicle patterns in French
    /\b\d+\s+(façons|raisons|conseils|astuces|secrets|avantages|bénéfices)\s+(de|pour)\b/gi,
    /\bLes?\s+\d+\s+(meilleurs?|principaux?)\b/gi,
    /\bGuide (ultime|complet|exhaustif) (de|pour|sur)\b/gi,
    /\bTout ce que vous (devez|avez besoin de) savoir (sur|à propos de)\b/gi,
    /\bGuide (du débutant|pour les débutants) (sur|de|pour)\b/gi,

    // Unearned profundity in French
    /\bQuelque chose a changé\b/gi,
    /\bTout a changé\b/gi,
    /\bMais voilà (la chose|le truc|le point clé)\b/gi,
    /\bVoici ce que (j'ai|nous avons) appris\b/gi,

    // AI content mill phrases in French
    /\bavancée(s)? (révolutionnaire|sans précédent)\b/gi,
    /\bbond (en avant|gigantesque|quantique)\b/gi,
    /\bpossibilités (passionnantes|prometteuses|incroyables)\b/gi,
    /\brythme (vertigineux|effréné|accéléré)\b/gi,
    /\btechnologie (de pointe|avancée|ultramoderne)\b/gi,
    /\brésultats (surprenants|étonnants|impressionnants)\b/gi,
    /\bimpact (réel|concret|tangible)\b/gi,
    /\bde toute évidence\b/gi,
    /\bdepuis .{5,30} jusqu'à .{5,30}, (cela|cette|cet|ces)\b/gi,
    /\bImaginez .{10,50} — c'est\b/gi,
    /\bPendant (des décennies|des années), .{10,50} semblait\b/gi,

    // Additional AI tells in French
    /\ble paysage (change|évolue|se transforme) (constamment|rapidement|perpétuellement)\b/gi,
    /\bcrucial (de comprendre|de noter|de reconnaître)\b/gi,
    /\bvital (de comprendre|de noter|de reconnaître)\b/gi,
    /\bimportant (de comprendre|de noter|de reconnaître|de se rappeler) que\b/gi,
    /\bvaut la peine (de mentionner|de noter|de souligner) que\b/gi,
    /\bil faut (considérer|comprendre|reconnaître)\b/gi,
    /\bbilan (éprouvé|démontré|solide)\b/gi,
    /\btradition (bien établie|ancrée|séculaire)\b/gi,
    /\bregard vers l'avenir\b/gi,
    /\bfaçonner l'avenir (de|du)\b/gi,
    /\bprêt à (devenir|transformer|révolutionner)\b/gi,
    /\bau (seuil|bord|carrefour) de\b/gi,
    /\bannonce(r)? une nouvelle (ère|époque)\b/gi,
    /\bmarque(r)? (un tournant|un moment décisif)\b/gi,
    /\btournant décisif\b/gi,
    /\bmoment charnière\b/gi,
    /\btempête parfaite de\b/gi,
    /\bconvergence de\b/gi,
    /\bintersection de\b/gi,
    /\bà (l'avant-garde|la pointe|la croisée des chemins) de\b/gi,
    /\bpionnier(s)? (en|dans|de)\b/gi,
    /\bcroissance exponentielle\b/gi,
    /\bopportunité unique\b/gi,
    /\bindéniablement\b/gi,
    /\bincontestablement\b/gi,
    /\birréfutablement\b/gi,
    /\bsans aucun doute\b/gi,
    /\binutile de (dire|préciser)\b/gi,
    /\bautrement dit\b/gi,
    /\ben résumé\b/gi,
    /\bce faisant\b/gi,
    /\bà ce stade\b/gi,
    /\bgangnant (de la traction|du terrain|de l'élan)\b/gi,
    /\ben hausse\b/gi,
    /\bcroissance (explosive|fulgurante|météorique)\b/gi,
    /\bessore? fulgurant(e)?\b/gi,
    /\bcroissance sans précédent\b/gi,
    /\bsuccès sans pareil\b/gi,
    /\brecord historique\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Je suis|Nous sommes) (très )?(ravi|ravie|ravis|ravies|fier|fière|fiers|fières|enchanté|enchantée|honoré|honorée|heureux|heureuse|comblé|comblée) de (annoncer|partager|présenter|révéler|vous dire)\b/gim,
    /^(Je n'arrive|Nous n'arrivons) pas à (attendre de|croire que) (partager|vous dire|annoncer|présenter)\b/gim,
    /^(Grandes|Bonnes|Formidables|Incroyables) nouvelles[!:]/gim,
    /^Nous venons (juste)? de lancer\b/gim,
    /^(Aujourd'hui|Cette semaine|Ce mois-ci) (je suis|nous sommes) (en train d'annoncer|en train de lancer|ravi de partager)\b/gim,
    /^Ravi(e)? de (partager|annoncer|présenter|révéler)\b/gim,
    /^Fier\/Fière de (partager|annoncer|présenter|révéler)\b/gim,
    /^Enchanté(e)? de (partager|annoncer|présenter|révéler)\b/gim,
    /^Heureux\/Heureuse de (partager|annoncer|présenter|révéler)\b/gim,
    /^Honoré(e)? de (partager|annoncer|présenter|révéler)\b/gim,
    /^Devinez quoi[!?]/gim,
    /^Vous n'allez pas (le croire|y croire)\b/gim,
    /^(Regardez|Jetez un œil à|Ne manquez pas) (ceci|ce que)\b/gim,
    /^(Grande|Énorme) annonce[!:]/gim,
    /^(Enfin|Finalement)[,!]/gim,
    /^(Info de dernière minute|Dernières nouvelles)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in French (2 points per match)
  tier2: [
    /\bsynergie(s)?\b/gi,
    /\bexploiter\b/gi,
    /\bfaire le point\b/gi,
    /\bfruits facilement accessibles\b/gi,
    /\bfaire bouger les lignes\b/gi,
    /\bpenser (en dehors des sentiers battus|hors des cadres)\b/gi,
    /\bprendre contact\b/gi,
    /\bpivoter\b/gi,
    /\bdisruptif\b/gi,
    /\bscaler\b/gi,
    /\bagile\b/gi,
    /\bcapacité (disponible|installée)\b/gi,
    /\bcompétences? (clés?|essentielles?|cœur)\b/gi,
    /\bparties? prenantes?\b/gi,
    /\bproposition de valeur\b/gi,
    /\bleader (d'opinion|de pensée)\b/gi,
    /\bbonnes pratiques?\b/gi,
    /\btransformation numérique\b/gi,
    /\bpropulsé par l'IA\b/gi,
    /\bbasé sur le (cloud|nuage)\b/gi,
    /\bcentré sur le client\b/gi,
    /\bavantage concurrentiel\b/gi,
    /\bpart de marché\b/gi,
    /\bROI\b/gi,
    /\bKPI\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\blivrables?\b/gi,
    /\bpoints? d'action\b/gi,
    /\bautonomisation\b/gi,
    /\bstimule(r|r) l'innovation\b/gi,
    /\boptimiser\b/gi,
    /\boptimisation\b/gi,
    /\bmaximiser\b/gi,
    /\balignement\b/gi,
    /\bs'aligner (avec|sur)\b/gi,
    /\bcollaborer\b/gi,
    /\btransversal\b/gi,
    /\bsolution intégrée\b/gi,
    /\bde bout en bout\b/gi,
    /\bnativement dans le cloud\b/gi,
    /\bconteneurisé\b/gi,
    /\bmicroservices\b/gi,
    /\bserverless\b/gi,
    /\bpiloté par les (données|événements)\b/gi,
    /\btemps réel\b/gi,
    /\bhaute (disponibilité|performance|fiabilité)\b/gi,
    /\bévolutif\b/gi,
    /\bmodulaire\b/gi,
    /\bflexible\b/gi,
    /\bconvivial\b/gi,
    /\bintuitif\b/gi,
    /\bexpérience utilisateur\b/gi,
    /\btransformation du business\b/gi,
    /\bécosystème (numérique|technologique)\b/gi,
    /\bplateforme (numérique|intégrée|technologique)\b/gi,
    /\bgestion du changement\b/gi,
    /\bfeuille de route\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Clichés in French (1 point per match)
  tier3: [
    /\bgratuit\b/gi,
    /\bgaranti\b/gi,
    /\bincroyable\b/gi,
    /\bépoustouflant\b/gi,
    /\binimaginable\b/gi,
    /\bimpressionnant\b/gi,
    /\brévolutionnaire\b/gi,
    /\bmiraculeuse?\b/gi,
    /\ble meilleur de sa catégorie\b/gi,
    /\bde tout premier plan\b/gi,
    /\bdernière technologie\b/gi,
    /\bcliquez ici\b/gi,
    /\bachetez maintenant\b/gi,
    /\bagissez (maintenant|immédiatement)\b/gi,
    /\boffre (à durée limitée|limitée dans le temps)\b/gi,
    /\bn'attendez pas\b/gi,
    /\bune fois dans sa vie\b/gi,
    /\bsans engagement\b/gi,
    /\bsans risque\b/gi,
    /\bdoublez vos revenus\b/gi,
    /\bgagnez de l'argent\b/gi,
    /\bargent rapide\b/gi,
    /\brésultats prouvés\b/gi,
    /\bpromotion spéciale\b/gi,
    /\béconomisez gros\b/gi,
    /\bprix le plus bas\b/gi,
    /\bmeilleure (offre|prix|affaire)\b/gi,
    /\bsans frais\b/gi,
    /\bconsultation gratuite\b/gi,
    /\bincontournable\b/gi,
    /\bau niveau supérieur\b/gi,
    /\bhausser la barre\b/gi,
    /\bse démarquer de la masse\b/gi,
    /\bse propager comme une traînée de poudre\b/gi,
    /\bla partie émergée de l'iceberg\b/gi,
    /\ble contenu est roi\b/gi,
    /\bpartir (du bon pied|sur les chapeaux de roue)\b/gi,
    /\ben bref\b/gi,
    /\bbasiquement\b/gi,
    /\bessentiellement\b/gi,
    /\ben fait\b/gi,
    /\bformidable\b/gi,
    /\bspectaculaire\b/gi,
    /\bphénoménal\b/gi,
    /\bextraordinaire\b/gi,
    /\bsensationnel\b/gi,
    /\bépatant\b/gi,
    /\bmerveilleux\b/gi,
    /\bépique\b/gi,
    /\blégendaire\b/gi,
    /\baccès exclusif\b/gi,
    /\bsur invitation seulement\b/gi,
    /\bà venir\b/gi,
    /\bne ratez pas\b/gi,
    /\bFOMO\b/gi,
    /\bpeur de rater quelque chose\b/gi,
    /\bdépêchez-vous\b/gi,
    /\bastuce(s)?\b/gi,
    /\bconseil(s)? et astuce(s)?\b/gi,
    /\bpro-tip(s)?\b/gi,
    /\bhack de vie\b/gi,
    /\bhack de croissance\b/gi,
    /\bplan (étape par étape|pas à pas)\b/gi,
    /\bsystème (prouvé|éprouvé)\b/gi,
    /\bfacile comme\b/gi,
    /\brapide et facile\b/gi,
    /\ben seulement \d+ (minutes?|heures?|jours?)\b/gi,
    /\bsuccès (du jour au lendemain|instantané)\b/gi,
    /\brésultats (immédiats|instantanés)\b/gi,
    /\bcommencez (aujourd'hui|gratuitement|maintenant)\b/gi,
    /\binscrivez-vous (maintenant|gratuitement)\b/gi,
    /\brejoingnez (maintenant|gratuitement|des milliers|des millions)\b/gi,
    /\b(des milliers|des millions|des milliards) d'(utilisateurs|clients|personnes)\b/gi,
    /\bprimé\b/gi,
    /\btransformez votre (vie|entreprise|carrière)\b/gi,
    /\bchangez votre vie\b/gi,
    /\bdébloquez votre (potentiel|réussite)\b/gi
  ],

  // Political content patterns - French political context
  political: [
    /\b(politique|politiques|politicien|partisant|partisan)\b/gi,
    /\b(démocrate|républicain|libéral|conservateur|libertarien|socialiste|communiste|marxiste|fasciste)\b/gi,
    /\b(gauche|droite|centre[- ]gauche|centre[- ]droite|extrême (gauche|droite))\b/gi,
    /\b(progressiste|populiste|nationaliste|mondialiste|europhobe|europhile)\b/gi,
    /\b(assemblée nationale|sénat|parlement|conseil constitutionnel|conseil d'état)\b/gi,
    /\b(élections?|voter|vote|scrutin|campagne|candidature|primaires?)\b/gi,
    /\b(législation|projet de loi|loi|décret|veto)\b/gi,
    /\b(destitution|motion de censure|dissolution)\b/gi,
    /\b(président|sénateur|député|politicien|candidat)\b/gi,
    /\b(gouvernement|élysée|palais bourbon|matignon|état)\b/gi,
    /\b(inflation|récession|dépression|stimulus (économique)?|plan de relance)\b/gi,
    /\b(banque (centrale|de france)|taux d'intérêt|BCE)\b/gi,
    /\b(renflouement|dette publique|plafond de la dette)\b/gi,
    /\b(budget|déficit|dette nationale)\b/gi,
    /\b(droits de douane|sanctions|guerre commerciale)\b/gi,
    /\b(taux de chômage|rapport sur l'emploi)\b/gi,
    /\b(avortement|IVG|pro[- ]vie|pro[- ]choix)\b/gi,
    /\b(contrôle des armes|port d'armes)\b/gi,
    /\b(immigration|crise (migratoire|des réfugiés)|sans-papiers|clandestin)\b/gi,
    /\b(changement climatique|réchauffement climatique|pacte vert|transition écologique)\b/gi,
    /\b(sécurité sociale|assurance maladie|système de santé)\b/gi,
    /\b(réforme fiscale|baisses? d'impôts?|impôts?)\b/gi,
    /\b(culture de l'annulation|wokisme|politiquement correct|identitaire)\b/gi,
    /\b(théorie critique de la race|diversité et inclusion|DEI|équité)\b/gi,
    /\b(droits (trans|LGBTQ|de genre))\b/gi,
    /\b(censure|liberté d'expression|liberté de la presse)\b/gi,
    /\b(patriote|nationalisme|état profond|mondialisme)\b/gi,
    /\b(réveillez-vous|moutons|masse endormie)\b/gi,
    /\b(médias (grand public|corporatifs)|infos fake|fake news|propagande)\b/gi,
    /\b(complot|complotisme|théorie du complot|couverture)\b/gi,
    /\b(droits constitutionnels|liberté|tyrannie|autocratie)\b/gi,
    /\b(agenda (socialiste|mondialiste)|régime)\b/gi,
    /\b(détruire (la démocratie|le pays|la nation))\b/gi,
    /\b(menace (pour la démocratie|pour la liberté))\b/gi,
    /\b(guerre contre (l'église|la religion|les valeurs))\b/gi,
    /\b(RN|NUPES|LFI|LREM|Renaissance|LR|PS|PCF)\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'plongeons dans': 'explorer, examiner, analyser',
    'plonger dans les complexités': 'examiner en détail, analyser',
    'naviguer le paysage': 'comprendre la situation, explorer le domaine',
    'changement de paradigme': 'changement majeur, transformation fondamentale',
    'changer la donne': 'avancée significative, développement important',
    'potentiel transformateur': 'décris le changement réel qui se produit',
    'débloquer le potentiel': 'permettre, rendre possible, faciliter',
    'intégrer de manière transparente': 'intégrer, combiner, faire fonctionner ensemble',
    'approche holistique': 'méthode complète, stratégie globale',
    'solution robuste': 'système fiable, approche solide',
    'se plonger dans': 'analyse détaillée, examen approfondi',
    'tapisserie de': 'collection de, mélange de',
    'sans précédent': 'explique ce qui le rend unique',
    'pionnier en': 'innovant, nouveau, explique l\'innovation',
    'trésor d\'informations': 'collection, ressource, source',
    'terrain inexploré': 'territoire nouveau, domaine inexploré',
    'jeter la lumière sur': 'expliquer, clarifier, révéler',
    'en fin de compte': 'en définitive, finalement',
    'à l\'avenir': 'dans le futur, ensuite, dorénavant',
    'points clés à retenir': 'points principaux, résumé, conclusions',
    'avancée sans précédent': 'explique quelle barrière a été surmontée',
    'de toute évidence': 'exprime ton point directement',
    'je suis ravi d\'annoncer': 'annoncer directement',
    'fier de partager': 'partager sans autocongratulation',
    'synergie': 'collaboration, coopération',
    'exploiter': 'utiliser, appliquer, tirer parti de',
    'faire le point': 'faire un suivi, revenir sur, revoir',
    'fruits facilement accessibles': 'victoires faciles, tâches simples',
    'faire bouger les lignes': 'progresser, créer un impact',
    'penser hors des cadres': 'être créatif, innover',
    'pivoter': 'changer de direction, ajuster la stratégie',
    'disruptif': 'explique ce que cela change',
    'parties prenantes': 'personnes impliquées, membres de l\'équipe',
    'leader d\'opinion': 'expert, spécialiste, autorité',
    'bonnes pratiques': 'méthodes efficaces',
    'autonomisation': 'permettre, autoriser',
    'optimiser': 'améliorer, perfectionner',
    'incroyable': 'utilise des descripteurs spécifiques',
    'basiquement': 'supprime-le ou sois plus précis',
    'essentiellement': 'supprime-le ou sois plus spécifique'
  },

  checkerSuggestions: {
    'plongeons dans': 'Essaie: "explorer", "examiner", ou sois spécifique sur ce que tu fais',
    'naviguer le paysage': 'Sois précis: À quelle situation ou quel domaine te réfères-tu exactement?',
    'changement de paradigme': 'Utilise des termes concrets: Qu\'est-ce qui a changé spécifiquement?',
    'changer la donne': 'Explique pourquoi c\'est important plutôt que d\'utiliser du jargon',
    'potentiel transformateur': 'Décris la transformation réelle',
    'exploiter': 'Essaie: "utiliser", "appliquer" ou "tirer parti de"',
    'synergie': 'Explique la collaboration ou le bénéfice réel',
    'faire le point': 'Dis: "faire un suivi", "revenir sur" ou "revoir"',
    'se plonger dans': 'Dis: "analyse détaillée" ou "examen approfondi"',
    'débloquer': 'Sois spécifique sur ce qui devient possible',
    'de manière transparente': 'Montre comment c\'est intégré plutôt que de l\'affirmer',
    'robuste': 'Décris les caractéristiques ou les forces réelles',
    'exhaustif': 'Énumère ce que cela couvre',
    'holistique': 'Explique comment tu considères tous les aspects',
    'disruptif': 'Explique ce que cela change et comment',
    'sans précédent': 'Si c\'est vrai, explique ce qui le rend unique',
    'incroyable': 'Utilise des descripteurs spécifiques et mesurables',
    'je suis ravi d\'annoncer': 'Évite le marketing. Annonce directement ce que tu partages.',
    'fier de partager': 'Omets l\'autocongratulation. Laisse le contenu parler de lui-même.',
    '—': 'Les tirets em sont un signe révélateur de contenu généré par IA. Utilise une ponctuation simple.'
  },

  slopDatabase: [
    { slop: 'plongeons dans', better: 'explorer, examiner ou analyser', tier: 'tier1' },
    { slop: 'naviguer le paysage', better: 'comprendre la situation, explorer le domaine', tier: 'tier1' },
    { slop: 'changement de paradigme', better: 'changement majeur, transformation fondamentale', tier: 'tier1' },
    { slop: 'changer la donne', better: 'avancée significative, développement important', tier: 'tier1' },
    { slop: 'potentiel transformateur', better: 'décris le changement réel qui se produit', tier: 'tier1' },
    { slop: 'débloquer le potentiel', better: 'permettre, rendre possible, faciliter', tier: 'tier1' },
    { slop: 'intégrer de manière transparente', better: 'intégrer, combiner, faire fonctionner ensemble', tier: 'tier1' },
    { slop: 'approche holistique', better: 'méthode complète, stratégie globale', tier: 'tier1' },
    { slop: 'solution robuste', better: 'système fiable, approche solide', tier: 'tier1' },
    { slop: 'se plonger dans', better: 'analyse détaillée, examen approfondi', tier: 'tier1' },
    { slop: 'tapisserie de', better: 'collection de, mélange de', tier: 'tier1' },
    { slop: 'sans précédent', better: 'rare, inhabituel, ou explique ce qui le rend unique', tier: 'tier1' },
    { slop: 'pionnier en', better: 'innovant, nouveau, ou explique l\'innovation', tier: 'tier1' },
    { slop: 'trésor d\'informations', better: 'collection, ressource, source', tier: 'tier1' },
    { slop: 'terrain inexploré', better: 'territoire nouveau, domaine inexploré', tier: 'tier1' },
    { slop: 'jeter la lumière sur', better: 'expliquer, clarifier, révéler', tier: 'tier1' },
    { slop: 'en fin de compte', better: 'en définitive, finalement, en conclusion', tier: 'tier1' },
    { slop: 'à l\'avenir', better: 'dans le futur, ensuite, dorénavant', tier: 'tier1' },
    { slop: 'points clés à retenir', better: 'points principaux, résumé, conclusions', tier: 'tier1' },
    { slop: 'avancée sans précédent', better: 'explique quelle barrière a été surmontée', tier: 'tier1' },
    { slop: 'de toute évidence', better: 'exprime ton point directement sans préambule', tier: 'tier1' },
    { slop: 'il convient de noter que', better: 'note que... ou affirme-le directement', tier: 'tier1' },
    { slop: 'je suis ravi d\'annoncer', better: 'l\'annoncer directement', tier: 'stopwords' },
    { slop: 'fier de partager', better: 'partager sans l\'emballage émotionnel', tier: 'stopwords' },
    { slop: 'enchanté de présenter', better: 'supprime l\'autocongratulation', tier: 'stopwords' },
    { slop: 'synergie', better: 'collaboration, coopération, effort commun', tier: 'tier2' },
    { slop: 'exploiter', better: 'utiliser, appliquer, tirer parti de', tier: 'tier2' },
    { slop: 'faire le point', better: 'faire un suivi, revenir sur, revoir', tier: 'tier2' },
    { slop: 'pivoter', better: 'changer de direction, ajuster la stratégie', tier: 'tier2' },
    { slop: 'disruptif', better: 'explique ce que cela change et comment', tier: 'tier2' },
    { slop: 'parties prenantes', better: 'personnes impliquées, membres de l\'équipe', tier: 'tier2' },
    { slop: 'leader d\'opinion', better: 'expert, spécialiste, autorité', tier: 'tier2' },
    { slop: 'bonnes pratiques', better: 'méthodes efficaces, approches éprouvées', tier: 'tier2' },
    { slop: 'autonomisation', better: 'permettre, autoriser, donner de l\'autonomie', tier: 'tier2' },
    { slop: 'optimiser', better: 'améliorer, perfectionner, rendre plus efficace', tier: 'tier2' },
    { slop: 'incroyable', better: 'utilise des descripteurs spécifiques et mesurables', tier: 'tier3' },
    { slop: 'époustouflant', better: 'fournis des détails concrets', tier: 'tier3' },
    { slop: 'révolutionnaire', better: 'décris le changement réel', tier: 'tier3' },
    { slop: 'basiquement', better: 'supprime-le ou sois plus précis', tier: 'tier3' },
    { slop: 'essentiellement', better: 'supprime-le ou sois plus spécifique', tier: 'tier3' },
    { slop: 'tiret em (—)', better: 'utilise des points, virgules, ou supprime la pause dramatique', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\bdans le paysage (en constante|toujours plus|perpétuellement) (évolution|mutation|transformation)\\b/gi',
      '/\\bpaysage (en constante|toujours) évolution\\b/gi',
      '/\\bnaviguer (dans|le|ce) (complexe )?(paysage|monde|environnement)\\b/gi',
      '/\\bplongeons (dans|au cœur de)\\b/gi',
      '/\\bplonger dans (les|la) (complexités|profondeurs|subtilités)\\b/gi',
      '/\\bun voyage transformateur\\b/gi',
      '/\\btapisserie de\\b/gi',
      '/\\bil convient de (noter|souligner|mentionner|préciser) que\\b/gi',
      '/\\bil est (important|essentiel|crucial|fondamental) de (noter|souligner|mentionner|préciser|comprendre) que\\b/gi',
      '/\\bapproche (holistique|globale|intégrée)\\b/gi',
      '/\\bdébloquer (le potentiel|de nouvelles possibilités|le pouvoir)\\b/gi',
      '/\\bchangement de paradigme\\b/gi',
      '/\\bsans précédent\\b/gi',
      '/\\bsolution (robuste|complète|solide)\\b/gi',
      '/\\bguide (complet|exhaustif|détaillé)\\b/gi',
      '/\\bpotentiel transformateur\\b/gi',
      '/\\bchanger la donne\\b/gi',
      '/\\bse plonger dans\\b/gi',
      '/\\bjeter (une|de la) lumière sur\\b/gi',
      '/\\bsans pareil\\b/gi',
      '/\\ben fin de compte\\b/gi',
      '/\\ben conclusion\\b/gi',
      '/\\ben (résumé|bref)\\b/gi',
      '/\\bà l\'avenir\\b/gi',
      '/\\bpoints clés (à retenir|à mémoriser)\\b/gi',
      '/\\b(De plus|Par ailleurs|En outre|Par conséquent|Néanmoins|Cependant),?\\s/gi',
      '/\\b(Il est important de (noter|souligner)|Force est de constater) que\\b/gi',
      '/\\bcroissance exponentielle\\b/gi',
      '/\\btournant décisif\\b/gi',
      '/\\bconvergence de\\b/gi',
      '/\\bde toute évidence\\b/gi',
      '/^Dans le monde d\'aujourd\'hui .{10,40},?\\s/mi',
      '/\\bindéniablement\\b/gi',
      '/\\bincontestablement\\b/gi'
    ],
    tier2: [
      '/\\bsynergie(s)?\\b/gi',
      '/\\bexploiter\\b/gi',
      '/\\bfaire le point\\b/gi',
      '/\\bpivoter\\b/gi',
      '/\\bdisruptif\\b/gi',
      '/\\bscaler\\b/gi',
      '/\\bagile\\b/gi',
      '/\\bcompétences? (clés?|essentielles?|cœur)\\b/gi',
      '/\\bparties? prenantes?\\b/gi',
      '/\\bproposition de valeur\\b/gi',
      '/\\bleader (d\'opinion|de pensée)\\b/gi',
      '/\\bbonnes pratiques?\\b/gi',
      '/\\btransformation numérique\\b/gi',
      '/\\bpropulsé par l\'IA\\b/gi',
      '/\\bcentré sur le client\\b/gi',
      '/\\bavantage concurrentiel\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI\\b/gi',
      '/\\bautonomisation\\b/gi',
      '/\\boptimiser\\b/gi',
      '/\\boptimisation\\b/gi',
      '/\\bmaximiser\\b/gi',
      '/\\balignement\\b/gi',
      '/\\bcollaborer\\b/gi',
      '/\\bsolution intégrée\\b/gi',
      '/\\bévolutif\\b/gi',
      '/\\bconvivial\\b/gi',
      '/\\bintuitif\\b/gi',
      '/\\bécosystème (numérique|technologique)\\b/gi',
      '/\\bgestion du changement\\b/gi'
    ],
    tier3: [
      '/\\bgratuit\\b/gi',
      '/\\bgaranti\\b/gi',
      '/\\bincroyable\\b/gi',
      '/\\bépoustouflant\\b/gi',
      '/\\bimpressionnant\\b/gi',
      '/\\brévolutionnaire\\b/gi',
      '/\\bcliquez ici\\b/gi',
      '/\\bachetez maintenant\\b/gi',
      '/\\boffre (à durée limitée|limitée dans le temps)\\b/gi',
      "/\\bn'attendez pas\\b/gi",
      '/\\bsans risque\\b/gi',
      '/\\bgagnez de l\'argent\\b/gi',
      '/\\brésultats prouvés\\b/gi',
      '/\\bpromotion spéciale\\b/gi',
      '/\\bmeilleure (offre|prix|affaire)\\b/gi',
      '/\\bincontournable\\b/gi',
      '/\\bau niveau supérieur\\b/gi',
      '/\\ben bref\\b/gi',
      '/\\bbasiquement\\b/gi',
      '/\\bessentiellement\\b/gi',
      '/\\bformidable\\b/gi',
      '/\\bspectaculaire\\b/gi',
      "/\\bne ratez pas\\b/gi",
      '/\\bdépêchez-vous\\b/gi',
      '/\\bcommencez (aujourd\'hui|gratuitement|maintenant)\\b/gi',
      '/\\btransformez votre (vie|entreprise|carrière)\\b/gi'
    ]
  }
};
