// De-Slop Italian (it) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for Italian-language content
// ChatGPT in Italian has distinctive overused phrases - these are the real ones

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.it = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in Italian - phrases that appear constantly in LLM-generated Italian text
  tier1: [
    // Signature ChatGPT Italian phrases - the most blatant tells
    /\bnel (mutevole|dinamico|complesso|frenetico) panorama\b/gi,
    /\bpanorama in (continua|costante|rapida) (evoluzione|trasformazione|mutazione)\b/gi,
    /\bnavigare (il|nel|questo) (complesso )?(panorama|mondo|contesto|ambiente)\b/gi,
    /\baddentrarsi (in|nel|nella|nelle)\b/gi,
    /\bapprofondire (le|la|i|gli)? ?(complessit[aà]|sfumature|intricatezze|dinamiche)\b/gi,
    /\bun viaggio trasformativo\b/gi,
    /\bintraprendere (questo|un|il nostro) viaggio\b/gi,
    /\btessuto di\b/gi,
    /\bmosaico di\b/gi,
    /\b[eè] (importante|essenziale|fondamentale|cruciale) (notare|sottolineare|evidenziare|comprendere|ricordare) che\b/gi,
    /\bva (notato|sottolineato|evidenziato|ricordato) che\b/gi,
    /\bin ultima analisi,? la (decisione|scelta) spetta a (te|voi|lei|loro)\b/gi,
    /\bapproccio (olistico|integrato|a 360 gradi)\b/gi,
    /\bintegra(re|zione|ndo)si? (senza soluzione di continuit[aà]|perfettamente|in modo (trasparente|armonioso))\b/gi,
    /\bsbloccare (il potenziale|nuove possibilit[aà]|il potere)\b/gi,
    /\bpromuovere (l'innovazione|la crescita|la collaborazione)\b/gi,
    /\bsfumature? (di comprensione|dell'approccio|della prospettiva)\b/gi,
    /\battenzione meticolosa\b/gi,
    /\bpaesaggio in (costante|rapida|continua) evoluzione\b/gi,
    /\bcontesto (dinamico|in evoluzione|in continuo cambiamento)\b/gi,
    /\bruolo (fondamentale|cruciale|chiave|determinante|pivotale)\b/gi,
    /\bnell(o|a|e|') (schema|grande schema) (delle cose|complessivo|generale)\b/gi,
    /\bpilastro (fondamentale|portante|chiave)\b/gi,
    /\bpilastri (fondamentali|portanti|chiave)\b/gi,
    /\bpunti chiave\b/gi,
    /\bconsiderazioni? chiave\b/gi,
    /\besplorare (le|la|i|gli|le )?(diverse|varie)? ?(sfaccettature?|dimensioni?|aspetti?) di\b/gi,
    /\bpotenziale trasformativo\b/gi,
    /\bcambiare le regole del gioco\b/gi,
    /\bcambio di paradigma\b/gi,
    /\bsenza precedenti\b/gi,
    /\bsoluzione (robusta|completa|solida)\b/gi,
    /\bguida (completa|esaustiva|dettagliata|definitiva)\b/gi,
    /\bsfruttare (la potenza|il potere|la forza) di\b/gi,
    /\b(in|nel corso di) questo (articolo|post|testo|approfondimento),? (vedremo|esploreremo|analizzeremo|esamineremo)\b/gi,
    /\bnel corso (di questo|dell') (articolo|post|testo|analisi)\b/gi,
    /\bcome (modello linguistico|assistente IA)\b/gi,
    /\bnon (pu[oò]|possiamo) (essere sottovalutat[oae]|essere ignorat[oae])\b/gi,
    /\bimmergersi in\b/gi,
    /\bgettare luce su\b/gi,
    /\bfar luce su\b/gi,
    /\bsenza eguali\b/gi,
    /\bminiera (di informazioni|di risorse|di conoscenze)\b/gi,
    /\bterreno (inesplorato|vergine)\b/gi,
    /\ball'avanguardia\b/gi,
    /\bdi ultima generazione\b/gi,
    /\bla prossima frontiera\b/gi,
    /\bche (stimola|invita alla) riflessione\b/gi,
    /\bin definitiva\b/gi,
    /\bin conclusione\b/gi,
    /\bper riassumere\b/gi,
    /\bin sintesi\b/gi,
    /\bin prospettiva (futura)?\b/gi,
    /\bandando avanti\b/gi,
    /\bguardando al futuro\b/gi,

    // Structural patterns in Italian
    /^(In conclusione|In sintesi|Per riassumere|In definitiva|Tirando le somme),?\s/mi,
    /\bNon solo .{10,50} ma (anche|pure)?\b/gi,
    /\bNonostante (i suoi|i loro|le sue|le) .{5,30},? .{5,30} (affronta|presenta|incontra) sfide\b/gi,
    /\bProspettive future:?\b/gi,

    // AI antithesis patterns in Italian
    /\bNon si tratta (solo|unicamente|semplicemente) di .{5,40}[,;] (si tratta|ma) di\b/gi,
    /\bNon [eè] .{5,40}[,;] [eè] .{5,40}\b/gi,
    /\bNon .{5,40}[,;] (ma|bens[ií]) .{5,40}\b/gi,
    /\bMeno .{5,30}[,;] pi[uù] .{5,30}\b/gi,
    /\bDimentica (che|il|la|lo) .{5,30}[,;] (abbraccia|pensa a|concentrati su) .{5,30}\b/gi,

    // Excessive transition words (Italian) - the biggest ChatGPT Italian tell
    /\b(Inoltre|Per di pi[uù]|Peraltro|Di conseguenza|Tuttavia|Ciononostante|Nondimeno),?\s/gi,
    /\b([EÈ] importante sottolineare|[EÈ] doveroso notare|Va sottolineato|Occorre evidenziare|Merita di essere menzionato) che\b/gi,
    /\b(Inutile dire|Va da s[eé]|Non c'[eè] bisogno di dire) che\b/gi,

    // Generic openers in Italian
    /^(Nel mondo|Nell'era|Nel contesto) (di oggi|attuale|moderno|contemporaneo),?\s/mi,
    /^(In|Con|Attraverso|Nel corso di) .{20,60}(continua a|[eè] (diventat[oa]|diventando)|si sta trasformando in)\b/mi,

    // Listicle patterns in Italian
    /\b\d+\s+(modi|motivi|consigli|trucchi|segreti|benefici|vantaggi)\s+(per|di)\b/gi,
    /\bI (migliori|principali)\s+\d+\b/gi,
    /\bLe (migliori|principali)\s+\d+\b/gi,
    /\bGuida (definitiva|completa|esaustiva) (per|a|su|alla|al)\b/gi,
    /\bTutto (quello|ci[oò]) che (devi|bisogna) sapere (su|riguardo a)\b/gi,
    /\bGuida (per principianti|del principiante) (su|a|per)\b/gi,

    // Unearned profundity in Italian
    /\bQualcosa [eè] cambiato\b/gi,
    /\bTutto [eè] cambiato\b/gi,
    /\bMa ecco (il punto|la chiave|il nodo)\b/gi,
    /\b(Ecco|Questo [eè]) (quello|ci[oò]) che (ho|abbiamo) imparato\b/gi,

    // AI content mill phrases in Italian
    /\bprogresso (rivoluzionario|senza precedenti)\b/gi,
    /\bsalto (in avanti|quantico|di qualit[aà])\b/gi,
    /\bpossibilit[aà] (entusiasmanti|affascinanti|straordinarie)\b/gi,
    /\britmo (vertiginoso|frenetico|accelerato|incalzante)\b/gi,
    /\btecnologia (avanzata|di ultima generazione|all'avanguardia)\b/gi,
    /\brisultati (sorprendenti|impressionanti|straordinari)\b/gi,
    /\bimpatto (reale|concreto|tangibile|nel mondo reale)\b/gi,
    /\b[eè] (chiaro|evidente) che\b/gi,
    /\bda .{5,30} a .{5,30}, (questo|questa|quest[oi])\b/gi,
    /\bImmagina .{10,50} — (questo|ecco)\b/gi,
    /\bPer (decenni|anni), .{10,50} (sembrava|pareva)\b/gi,

    // Additional AI tells in Italian
    /\bil panorama (sta cambiando|si sta trasformando|sta evolvendo) (costantemente|rapidamente)\b/gi,
    /\bcruciale (comprendere|notare|riconoscere)\b/gi,
    /\bfondamentale (comprendere|notare|riconoscere|ricordare) che\b/gi,
    /\bvale la pena (menzionare|notare|sottolineare|evidenziare) che\b/gi,
    /\bsi deve (considerare|comprendere|riconoscere)\b/gi,
    /\bcomprovata esperienza\b/gi,
    /\btradizione (radicata|consolidata|secolare)\b/gi,
    /\bvolgere lo sguardo al futuro\b/gi,
    /\bplasmare il futuro (di|del|della|delle|dei)\b/gi,
    /\bpronto a (diventare|trasformare|rivoluzionare)\b/gi,
    /\balla (soglia|cuspide|vigilia) di\b/gi,
    /\bannuncia(re)? una nuova (era|epoca|fase|stagione)\b/gi,
    /\bsegna(re)? un (punto di svolta|momento decisivo)\b/gi,
    /\bpunto di svolta\b/gi,
    /\bmomento (decisivo|cruciale)\b/gi,
    /\btempesta perfetta di\b/gi,
    /\bconvergenza di\b/gi,
    /\bintersezione (di|tra)\b/gi,
    /\b(all'avanguardia|al crocevia|alla confluenza) di\b/gi,
    /\bpioniere (in|di|nel)\b/gi,
    /\bcrescita esponenziale\b/gi,
    /\bopportunit[aà] unica\b/gi,
    /\bindubbiamente\b/gi,
    /\binnegabilmente\b/gi,
    /\bincontestabilmente\b/gi,
    /\bsenza ombra di dubbio\b/gi,
    /\binutile dire\b/gi,
    /\bin poche parole\b/gi,
    /\btirando le somme\b/gi,
    /\bdetto (questo|ci[oò]),\b/gi,
    /\bin questo (momento|frangente)\b/gi,
    /\bsta guadagnando (terreno|slancio|impulso)\b/gi,
    /\bin (costante|forte) ascesa\b/gi,
    /\bcrescita (esplosiva|fulminea|vertiginosa)\b/gi,
    /\bascesa (meteoric|fulmine)a\b/gi,
    /\bcrescita senza precedenti\b/gi,
    /\bsuccesso senza eguali\b/gi,
    /\brecord storico\b/gi,

    // Heavy overuse of formal connectives in Italian ChatGPT
    /\bpertanto\b/gi,
    /\bnell'ambito di\b/gi,
    /\ba tal proposito\b/gi,
    /\ba tal fine\b/gi,
    /\bin quest'ottica\b/gi,
    /\bin tale contesto\b/gi,
    /\balla luce di (quanto|ci[oò])\b/gi,
    /\bin virt[uù] di\b/gi,
    /\bai fini di\b/gi,
    /\bin merito a\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Sono|Siamo) (molto )?(entusiast[aoi]|orgoglios[aoi]|lieti?|onorat[aoi]|felic[ie]|content[aoi]) di (annunciare|condividere|presentare|rivelare|comunicare)/gim,
    /^Non (vedo|vediamo) l'ora di (condividere|comunicare|annunciare|presentare|rivelare)/gim,
    /^(Grandi|Entusiasmanti|Fantastiche|Incredibili) (notizie|novit[aà])[!:]/gim,
    /^Abbiamo appena lanciato\b/gim,
    /^(Oggi|Questa settimana|Questo mese) (sono|siamo) (lieti|entusiasti|orgogliosi|felici) di (annunciare|condividere)\b/gim,
    /^Entusiast[aoi] di (condividere|annunciare|presentare|rivelare)\b/gim,
    /^Orgoglios[aoi] di (condividere|annunciare|presentare|rivelare)\b/gim,
    /^Felic[ie] di (condividere|annunciare|presentare|rivelare)\b/gim,
    /^Onorat[aoi] di (condividere|annunciare|presentare|rivelare)\b/gim,
    /^Lieti? di (condividere|annunciare|presentare|rivelare)\b/gim,
    /^Indovinate (un po'|cosa)[!?]/gim,
    /^Non (crederete|ci crederete|potrete credere)\b/gim,
    /^(Guardate|Guarda|Date un'occhiata a) (questo|cosa)\b/gim,
    /^(Grande|Enorme) annuncio[!:]/gim,
    /^(Finalmente|Alla fine)[,!]/gim,
    /^(Ultime notizie|Notizia dell'ultima ora)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in Italian (2 points per match)
  tier2: [
    /\bsinergia\b/gi,
    /\bsinergie\b/gi,
    /\bfare leva su\b/gi,
    /\bleva(re)? strategica\b/gi,
    /\bfare il punto\b/gi,
    /\bfrutti facili da cogliere\b/gi,
    /\bspostare l'ago\b/gi,
    /\bpensare fuori dagli schemi\b/gi,
    /\bmettersi in contatto\b/gi,
    /\bpivotare\b/gi,
    /\bdisruptiv[oaei]\b/gi,
    /\bscalare\b/gi,
    /\bscalabilit[aà]\b/gi,
    /\bagile\b/gi,
    /\bcompetenz[ae] (chiave|core|essenzial[ie])\b/gi,
    /\bstakeholder\b/gi,
    /\bproposta di valore\b/gi,
    /\bthought leader(ship)?\b/gi,
    /\bleader di pensiero\b/gi,
    /\bbest practice\b/gi,
    /\bmigliori pratiche\b/gi,
    /\btrasformazione digitale\b/gi,
    /\bbasato sull'IA\b/gi,
    /\bguidato dall'IA\b/gi,
    /\bcloud[- ]based\b/gi,
    /\bbasato sul cloud\b/gi,
    /\borientato al (cliente|dato|mercato)\b/gi,
    /\bvantaggio competitivo\b/gi,
    /\bquota di mercato\b/gi,
    /\bROI\b/gi,
    /\bKPI\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\bdeliverable\b/gi,
    /\bprodotti consegnabili\b/gi,
    /\bpunti d'azione\b/gi,
    /\bempowerment\b/gi,
    /\bresponsabilizzazione\b/gi,
    /\bstimolare l'innovazione\b/gi,
    /\bpromuovere l'innovazione\b/gi,
    /\bottimizzare\b/gi,
    /\bottimizzazione\b/gi,
    /\bmassimizzare\b/gi,
    /\ballinea(mento|re)\b/gi,
    /\bcollabora(zione|re)\b/gi,
    /\btrasversale\b/gi,
    /\bcross[- ]funzionale\b/gi,
    /\bsoluzione (integrata|end[- ]to[- ]end)\b/gi,
    /\bcloud[- ]native\b/gi,
    /\bcontainerizzato\b/gi,
    /\bmicroservizi\b/gi,
    /\bserverless\b/gi,
    /\bdata[- ]driven\b/gi,
    /\bguidato dai dati\b/gi,
    /\btempo reale\b/gi,
    /\balta (disponibilit[aà]|performance|affidabilit[aà])\b/gi,
    /\bscalabile\b/gi,
    /\bmodulare\b/gi,
    /\bflessibile\b/gi,
    /\buser[- ]friendly\b/gi,
    /\bfacile da usare\b/gi,
    /\bintuitivo\b/gi,
    /\besperienza utente\b/gi,
    /\btrasformazione (del business|aziendale)\b/gi,
    /\becosistema (digitale|tecnologico)\b/gi,
    /\bpiattaforma (digitale|tecnologica|integrata)\b/gi,
    /\bgestione del cambiamento\b/gi,
    /\broadmap\b/gi,
    /\bworkflow\b/gi,
    /\bonboarding\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Cliches in Italian (1 point per match)
  tier3: [
    /\bgratis\b/gi,
    /\bgratuito\b/gi,
    /\bgarantito\b/gi,
    /\bincredibile\b/gi,
    /\bstrabiliante\b/gi,
    /\bsbalorditivo\b/gi,
    /\bimpressionante\b/gi,
    /\brivoluzionario\b/gi,
    /\bmiracoloso\b/gi,
    /\bil meglio della (sua|categoria|classe)\b/gi,
    /\bdi (primo|altissimo) livello\b/gi,
    /\bultima tecnologia\b/gi,
    /\bclicca qui\b/gi,
    /\bcompra (ora|adesso|subito)\b/gi,
    /\bagisci (ora|adesso|subito)\b/gi,
    /\bofferta a tempo limitato\b/gi,
    /\bnon (aspettare|attendere)\b/gi,
    /\buna volta nella vita\b/gi,
    /\bsenza impegno\b/gi,
    /\bsenza rischio\b/gi,
    /\braddoppia (i tuoi|le tue) (entrate|guadagni)\b/gi,
    /\bguadagna (soldi|denaro)\b/gi,
    /\bsoldi facili\b/gi,
    /\brisultati (comprovati|dimostrati|garantiti)\b/gi,
    /\bpromozione speciale\b/gi,
    /\brisparmia (alla grande|tantissimo)\b/gi,
    /\bprezzo pi[uù] basso\b/gi,
    /\b(migliore|miglior) (offerta|prezzo|affare)\b/gi,
    /\bsenza (costi|spese)\b/gi,
    /\bconsulenza gratuita\b/gi,
    /\bindispensabile\b/gi,
    /\bimperdibile\b/gi,
    /\bal (livello|passo) successivo\b/gi,
    /\balzare l'asticella\b/gi,
    /\bdistinguersi dalla (massa|folla)\b/gi,
    /\bdiffondersi a macchia d'olio\b/gi,
    /\bla punta dell'iceberg\b/gi,
    /\bil contenuto [eè] re\b/gi,
    /\bpartire col piede giusto\b/gi,
    /\bfondamentalmente\b/gi,
    /\bessenzialmente\b/gi,
    /\battualmente\b/gi,
    /\bfantastico\b/gi,
    /\bspettacolare\b/gi,
    /\bfenomenale\b/gi,
    /\bstraordinario\b/gi,
    /\bsensazionale\b/gi,
    /\bsorprendente\b/gi,
    /\bmeraviglioso\b/gi,
    /\bepico\b/gi,
    /\bleggendario\b/gi,
    /\baccesso esclusivo\b/gi,
    /\bsolo su invito\b/gi,
    /\bin arrivo\b/gi,
    /\bnon (perderti|perdertelo|perdetevelo)\b/gi,
    /\bFOMO\b/gi,
    /\bpaura di (perdere|perdersi) qualcosa\b/gi,
    /\baffrettati\b/gi,
    /\bsbrigati\b/gi,
    /\btrucco\b/gi,
    /\btrucchi\b/gi,
    /\bconsigli e trucchi\b/gi,
    /\bpro[- ]tip\b/gi,
    /\blife hack\b/gi,
    /\bgrowth hack\b/gi,
    /\bpiano passo (a|dopo) passo\b/gi,
    /\bsistema (collaudato|comprovato)\b/gi,
    /\bfacile come\b/gi,
    /\brapido e semplice\b/gi,
    /\bin soli? \d+ (minuti?|ore?|giorni?)\b/gi,
    /\bsuccesso (immediato|dall'oggi al domani)\b/gi,
    /\brisultati immediati\b/gi,
    /\binizia (oggi|gratis|ora|subito)\b/gi,
    /\bregistrati (ora|gratis|subito)\b/gi,
    /\bunisciti (ora|gratis|a migliaia|a milioni)\b/gi,
    /\b(migliaia|milioni|miliardi) di (utenti|clienti|persone)\b/gi,
    /\bpremiato\b/gi,
    /\btrasforma la tua (vita|attivit[aà]|carriera)\b/gi,
    /\bcambia la tua vita\b/gi,
    /\bsblocca il tuo (potenziale|successo)\b/gi
  ],

  // Political content patterns - Italian political context
  political: [
    /\b(politic[aoie]|politici|partitist[aoie]|partitico)\b/gi,
    /\b(democratico|repubblicano|liberale|conservatore|libertario|socialista|comunista|marxista|fascista)\b/gi,
    /\b(sinistra|destra|centro[- ]sinistra|centro[- ]destra|estrema (sinistra|destra))\b/gi,
    /\b(progressista|populista|nazionalista|globalista|sovranista|europeista|euroscettico)\b/gi,
    /\b(parlamento|senato|camera dei deputati|corte costituzionale|consiglio dei ministri)\b/gi,
    /\b(elezioni?|votare|votazione|urna|campagna (elettorale)?|candidatura|primarie)\b/gi,
    /\b(legislazione|disegno di legge|legge|decreto|decreto[- ]legge|veto)\b/gi,
    /\b(impeachment|mozione di sfiducia|crisi di governo)\b/gi,
    /\b(presidente|senatore|deputato|politico|candidato|premier|ministro)\b/gi,
    /\b(governo|palazzo (chigi|madama|montecitorio)|quirinale|stato)\b/gi,
    /\b(inflazione|recessione|crisi economica|manovra (economica|finanziaria))\b/gi,
    /\b(banca (centrale|d'italia)|BCE|tassi? d'interesse|spread)\b/gi,
    /\b(salvataggio|debito pubblico|tetto del debito|PNRR)\b/gi,
    /\b(bilancio|deficit|debito (nazionale|sovrano))\b/gi,
    /\b(dazi|sanzioni|guerra commerciale)\b/gi,
    /\b(tasso di disoccupazione|rapporto (sull'|di )occupazione)\b/gi,
    /\b(aborto|pro[- ]vita|pro[- ]scelta|IVG)\b/gi,
    /\b(controllo delle armi|porto d'armi)\b/gi,
    /\b(immigrazione|crisi (migratoria|dei migranti)|clandestino|irregolare)\b/gi,
    /\b(cambiamento climatico|riscaldamento globale|green deal|transizione ecologica)\b/gi,
    /\b(sanit[aà]|sistema sanitario (nazionale|pubblico)|SSN)\b/gi,
    /\b(riforma fiscale|taglio delle tasse|tasse|imposte)\b/gi,
    /\b(cultura della cancellazione|politicamente corretto|identitarismo|wokismo)\b/gi,
    /\b(diversit[aà] e inclusione|DEI|equit[aà])\b/gi,
    /\b(diritti (trans|LGBTQ|di genere|civili))\b/gi,
    /\b(censura|libert[aà] di (espressione|stampa|parola))\b/gi,
    /\b(patriota|nazionalismo|stato profondo|sovranismo)\b/gi,
    /\b(svegliatevi|pecore|massa addormentata)\b/gi,
    /\b(media (mainstream|corporativi)|fake news|propaganda|disinformazione)\b/gi,
    /\b(complotto|complottismo|teoria del complotto|insabbiamento)\b/gi,
    /\b(sovranit[aà] nazionale|libert[aà]|tirannia|autocrazia)\b/gi,
    /\b(agenda (socialista|comunista|globalista)|regime)\b/gi,
    /\b(PD|FdI|Lega|M5S|Forza Italia|Azione|Italia Viva|AVS)\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'addentrarsi in': 'esplorare, esaminare, analizzare',
    'approfondire le complessit\u00e0': 'esaminare in dettaglio, analizzare',
    'navigare il panorama': 'capire la situazione, esplorare il campo',
    'cambio di paradigma': 'cambiamento importante, trasformazione fondamentale',
    'cambiare le regole del gioco': 'progresso significativo, sviluppo importante',
    'potenziale trasformativo': 'descrivi il cambiamento reale che avviene',
    'sbloccare il potenziale': 'permettere, rendere possibile, facilitare',
    'integrarsi senza soluzione di continuit\u00e0': 'integrare, combinare, far funzionare insieme',
    'approccio olistico': 'metodo completo, strategia integrale',
    'soluzione robusta': 'sistema affidabile, approccio solido',
    'immergersi in': 'analisi dettagliata, esame approfondito',
    'tessuto di': 'collezione di, insieme di',
    'senza precedenti': 'spiega cosa lo rende unico',
    'pioniere in': 'innovativo, nuovo, spiega l\'innovazione',
    'miniera di informazioni': 'collezione, risorsa, fonte',
    'terreno inesplorato': 'territorio nuovo, area inesplorata',
    'gettare luce su': 'spiegare, chiarire, rivelare',
    'in definitiva': 'alla fine, in conclusione',
    'guardando al futuro': 'in futuro, poi, d\'ora in avanti',
    'punti chiave': 'punti principali, riepilogo, conclusioni',
    'progresso senza precedenti': 'spiega quale barriera e\u0300 stata superata',
    '\u00e8 chiaro che': 'esprimi il tuo punto direttamente',
    'sono entusiasta di annunciare': 'annuncia direttamente',
    'orgoglioso di condividere': 'condividi senza autocelebrazione',
    'sinergia': 'collaborazione, cooperazione',
    'fare leva su': 'usare, applicare, sfruttare',
    'fare il punto': 'fare un riepilogo, rivedere, ricapitolare',
    'frutti facili da cogliere': 'vittorie facili, compiti semplici',
    'spostare l\'ago': 'fare progressi, avere un impatto',
    'pensare fuori dagli schemi': 'essere creativi, innovare',
    'pivotare': 'cambiare direzione, adattare la strategia',
    'disruptivo': 'spiega cosa cambia',
    'stakeholder': 'persone coinvolte, membri del team',
    'thought leader': 'esperto, specialista, autorit\u00e0',
    'best practice': 'metodi efficaci',
    'empowerment': 'permettere, abilitare',
    'ottimizzare': 'migliorare, perfezionare',
    'incredibile': 'usa descrittori specifici',
    'fondamentalmente': 'eliminalo o sii piu\u0300 preciso',
    'essenzialmente': 'eliminalo o sii piu\u0300 specifico',
    'inoltre': 'spesso superfluo - collega le idee direttamente',
    'pertanto': 'usa connettivi piu\u0300 naturali o elimina',
    'nell\'ambito di': 'nel campo di, riguardo a'
  },

  checkerSuggestions: {
    'addentrarsi in': 'Prova: "esplorare", "esaminare", o sii specifico su cosa stai facendo',
    'navigare il panorama': 'Sii specifico: a quale situazione o campo ti riferisci esattamente?',
    'cambio di paradigma': 'Usa termini concreti: cosa e\u0300 cambiato specificamente?',
    'cambiare le regole del gioco': 'Spiega perch\u00e9 e\u0300 importante invece di usare gergo',
    'potenziale trasformativo': 'Descrivi la trasformazione reale',
    'fare leva su': 'Prova: "usare", "applicare" o "sfruttare"',
    'sinergia': 'Spiega la collaborazione o il beneficio reale',
    'fare il punto': 'Di\': "riepilogare", "rivedere" o "ricapitolare"',
    'immergersi in': 'Di\': "analisi dettagliata" o "esame approfondito"',
    'sbloccare': 'Sii specifico su cosa diventa possibile',
    'senza soluzione di continuit\u00e0': 'Mostra come si integra invece di affermarlo',
    'robusta': 'Descrivi le caratteristiche o i punti di forza reali',
    'esaustiva': 'Elenca cosa copre',
    'olistico': 'Spiega come consideri tutti gli aspetti',
    'disruptivo': 'Spiega cosa cambia e come',
    'senza precedenti': 'Se e\u0300 vero, spiega cosa lo rende unico',
    'incredibile': 'Usa descrittori specifici e misurabili',
    'sono entusiasta di annunciare': 'Salta il riempitivo marketing. Annuncia direttamente quello che stai condividendo.',
    'orgoglioso di condividere': 'Ometti l\'autocelebrazione. Lascia che il contenuto parli da solo.',
    '\u2014': 'I trattini lunghi sono un segnale rivelatore di contenuto generato da IA. Usa punteggiatura semplice.'
  },

  slopDatabase: [
    { slop: 'addentrarsi in', better: 'esplorare, esaminare o analizzare', tier: 'tier1' },
    { slop: 'navigare il panorama', better: 'capire la situazione, esplorare il campo', tier: 'tier1' },
    { slop: 'cambio di paradigma', better: 'cambiamento importante, trasformazione fondamentale', tier: 'tier1' },
    { slop: 'cambiare le regole del gioco', better: 'progresso significativo, sviluppo importante', tier: 'tier1' },
    { slop: 'potenziale trasformativo', better: 'descrivi il cambiamento reale che avviene', tier: 'tier1' },
    { slop: 'sbloccare il potenziale', better: 'permettere, rendere possibile, facilitare', tier: 'tier1' },
    { slop: 'integrarsi senza soluzione di continuit\u00e0', better: 'integrare, combinare, far funzionare insieme', tier: 'tier1' },
    { slop: 'approccio olistico', better: 'metodo completo, strategia integrale', tier: 'tier1' },
    { slop: 'soluzione robusta', better: 'sistema affidabile, approccio solido', tier: 'tier1' },
    { slop: 'immergersi in', better: 'analisi dettagliata, esame approfondito', tier: 'tier1' },
    { slop: 'tessuto di', better: 'collezione di, insieme di', tier: 'tier1' },
    { slop: 'senza precedenti', better: 'raro, insolito, o spiega cosa lo rende unico', tier: 'tier1' },
    { slop: 'pioniere in', better: 'innovativo, nuovo, o spiega l\'innovazione', tier: 'tier1' },
    { slop: 'miniera di informazioni', better: 'collezione, risorsa, fonte', tier: 'tier1' },
    { slop: 'terreno inesplorato', better: 'territorio nuovo, area inesplorata', tier: 'tier1' },
    { slop: 'gettare luce su', better: 'spiegare, chiarire, rivelare', tier: 'tier1' },
    { slop: 'in definitiva', better: 'alla fine, in conclusione', tier: 'tier1' },
    { slop: 'guardando al futuro', better: 'in futuro, poi, d\'ora in avanti', tier: 'tier1' },
    { slop: 'punti chiave', better: 'punti principali, riepilogo, conclusioni', tier: 'tier1' },
    { slop: 'progresso senza precedenti', better: 'spiega quale barriera e\u0300 stata superata', tier: 'tier1' },
    { slop: '\u00e8 chiaro che', better: 'esprimi il tuo punto direttamente senza preamboli', tier: 'tier1' },
    { slop: '\u00e8 importante notare che', better: 'nota che... o affermalo direttamente', tier: 'tier1' },
    { slop: 'sono entusiasta di annunciare', better: 'annunciarlo direttamente', tier: 'stopwords' },
    { slop: 'orgoglioso di condividere', better: 'condividere senza il packaging emotivo', tier: 'stopwords' },
    { slop: 'lieto di presentare', better: 'elimina l\'autocelebrazione', tier: 'stopwords' },
    { slop: 'sinergia', better: 'collaborazione, cooperazione, sforzo congiunto', tier: 'tier2' },
    { slop: 'fare leva su', better: 'usare, applicare, sfruttare', tier: 'tier2' },
    { slop: 'fare il punto', better: 'riepilogare, rivedere, ricapitolare', tier: 'tier2' },
    { slop: 'pivotare', better: 'cambiare direzione, adattare la strategia', tier: 'tier2' },
    { slop: 'disruptivo', better: 'spiega cosa cambia e come', tier: 'tier2' },
    { slop: 'stakeholder', better: 'persone coinvolte, membri del team', tier: 'tier2' },
    { slop: 'thought leader', better: 'esperto, specialista, autorit\u00e0', tier: 'tier2' },
    { slop: 'best practice', better: 'metodi efficaci, approcci collaudati', tier: 'tier2' },
    { slop: 'empowerment', better: 'permettere, abilitare, dare autonomia', tier: 'tier2' },
    { slop: 'ottimizzare', better: 'migliorare, perfezionare, rendere piu\u0300 efficiente', tier: 'tier2' },
    { slop: 'incredibile', better: 'usa descrittori specifici e misurabili', tier: 'tier3' },
    { slop: 'strabiliante', better: 'fornisci dettagli concreti', tier: 'tier3' },
    { slop: 'rivoluzionario', better: 'descrivi il cambiamento reale', tier: 'tier3' },
    { slop: 'fondamentalmente', better: 'eliminalo o sii piu\u0300 preciso', tier: 'tier3' },
    { slop: 'essenzialmente', better: 'eliminalo o sii piu\u0300 specifico', tier: 'tier3' },
    { slop: 'trattino lungo (\u2014)', better: 'usa punti, virgole, o elimina la pausa drammatica', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\bnel (mutevole|dinamico|complesso|frenetico) panorama\\b/gi',
      '/\\bpanorama in (continua|costante|rapida) (evoluzione|trasformazione|mutazione)\\b/gi',
      '/\\bnavigare (il|nel|questo) (complesso )?(panorama|mondo|contesto|ambiente)\\b/gi',
      '/\\baddentrarsi (in|nel|nella|nelle)\\b/gi',
      '/\\bapprofondire (le|la|i|gli)? ?(complessit[a\u00e0]|sfumature|intricatezze|dinamiche)\\b/gi',
      '/\\bun viaggio trasformativo\\b/gi',
      '/\\bintraprendere (questo|un|il nostro) viaggio\\b/gi',
      '/\\btessuto di\\b/gi',
      '/\\bmosaico di\\b/gi',
      '/\\b[e\u00e8] (importante|essenziale|fondamentale|cruciale) (notare|sottolineare|evidenziare|comprendere|ricordare) che\\b/gi',
      '/\\bapproccio (olistico|integrato|a 360 gradi)\\b/gi',
      '/\\bsbloccare (il potenziale|nuove possibilit[a\u00e0]|il potere)\\b/gi',
      '/\\bcambio di paradigma\\b/gi',
      '/\\bsenza precedenti\\b/gi',
      '/\\bsoluzione (robusta|completa|solida)\\b/gi',
      '/\\bguida (completa|esaustiva|dettagliata|definitiva)\\b/gi',
      '/\\bpotenziale trasformativo\\b/gi',
      '/\\bcambiare le regole del gioco\\b/gi',
      '/\\bimmergersi in\\b/gi',
      '/\\bgettare luce su\\b/gi',
      '/\\bfar luce su\\b/gi',
      '/\\bsenza eguali\\b/gi',
      '/\\bin definitiva\\b/gi',
      '/\\bin conclusione\\b/gi',
      '/\\bin sintesi\\b/gi',
      '/\\bguardando al futuro\\b/gi',
      '/\\bpunti chiave\\b/gi',
      '/\\b[e\u00e8] (chiaro|evidente) che\\b/gi',
      '/\\b(Inoltre|Per di pi[u\u00f9]|Peraltro|Di conseguenza|Tuttavia|Ciononostante|Nondimeno),?\\s/gi',
      '/\\b([E\u00c8] importante sottolineare|[E\u00c8] doveroso notare|Va sottolineato|Occorre evidenziare) che\\b/gi',
      '/\\bcrescita esponenziale\\b/gi',
      '/\\bpunto di svolta\\b/gi',
      '/\\bconvergenza di\\b/gi',
      '/^(Nel mondo|Nell\'era|Nel contesto) (di oggi|attuale|moderno|contemporaneo),?\\s/mi',
      '/\\bindubbiamente\\b/gi',
      '/\\binnegabilmente\\b/gi'
    ],
    tier2: [
      '/\\bsinergia\\b/gi',
      '/\\bsinergie\\b/gi',
      '/\\bfare leva su\\b/gi',
      '/\\bfare il punto\\b/gi',
      '/\\bpivotare\\b/gi',
      '/\\bdisruptiv[oaei]\\b/gi',
      '/\\bscalare\\b/gi',
      '/\\bagile\\b/gi',
      '/\\bcompetenz[ae] (chiave|core|essenzial[ie])\\b/gi',
      '/\\bstakeholder\\b/gi',
      '/\\bproposta di valore\\b/gi',
      '/\\bthought leader(ship)?\\b/gi',
      '/\\bbest practice\\b/gi',
      '/\\bmigliori pratiche\\b/gi',
      '/\\btrasformazione digitale\\b/gi',
      '/\\bbasato sull\'IA\\b/gi',
      '/\\borientato al (cliente|dato|mercato)\\b/gi',
      '/\\bvantaggio competitivo\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI\\b/gi',
      '/\\bempowerment\\b/gi',
      '/\\bottimizzare\\b/gi',
      '/\\bottimizzazione\\b/gi',
      '/\\bmassimizzare\\b/gi',
      '/\\ballinea(mento|re)\\b/gi',
      '/\\bcollabora(zione|re)\\b/gi',
      '/\\bsoluzione (integrata|end[- ]to[- ]end)\\b/gi',
      '/\\bscalabile\\b/gi',
      '/\\bfacile da usare\\b/gi',
      '/\\bintuitivo\\b/gi',
      '/\\becosistema (digitale|tecnologico)\\b/gi',
      '/\\bgestione del cambiamento\\b/gi'
    ],
    tier3: [
      '/\\bgratis\\b/gi',
      '/\\bgratuito\\b/gi',
      '/\\bgarantito\\b/gi',
      '/\\bincredibile\\b/gi',
      '/\\bstrabiliante\\b/gi',
      '/\\bimpressionante\\b/gi',
      '/\\brivoluzionario\\b/gi',
      '/\\bclicca qui\\b/gi',
      '/\\bcompra (ora|adesso|subito)\\b/gi',
      '/\\bofferta a tempo limitato\\b/gi',
      '/\\bnon (aspettare|attendere)\\b/gi',
      '/\\bsenza rischio\\b/gi',
      '/\\bguadagna (soldi|denaro)\\b/gi',
      '/\\brisultati (comprovati|dimostrati|garantiti)\\b/gi',
      '/\\bpromozione speciale\\b/gi',
      '/\\b(migliore|miglior) (offerta|prezzo|affare)\\b/gi',
      '/\\bindispensabile\\b/gi',
      '/\\bimperdibile\\b/gi',
      '/\\bal (livello|passo) successivo\\b/gi',
      '/\\bin poche parole\\b/gi',
      '/\\bfondamentalmente\\b/gi',
      '/\\bessenzialmente\\b/gi',
      '/\\bfantastico\\b/gi',
      '/\\bspettacolare\\b/gi',
      '/\\bnon (perderti|perdertelo|perdetevelo)\\b/gi',
      '/\\baffrettati\\b/gi',
      '/\\binizia (oggi|gratis|ora|subito)\\b/gi',
      '/\\btrasforma la tua (vita|attivit[a\u00e0]|carriera)\\b/gi'
    ]
  }
};
