// De-Slop Polish (pl) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for Polish-language content
// ChatGPT in Polish has distinctive overused phrases - these are the real ones

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.pl = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in Polish - phrases that appear constantly in LLM-generated Polish text
  tier1: [
    // Signature ChatGPT Polish phrases - the most blatant tells
    /\bw (dzisiejszym|obecnym|współczesnym) (dynamicznym|złożonym|szybko zmieniającym się) (świecie|krajobrazie|środowisku)\b/gi,
    /\bw dynamicznie zmieniaj(ącym|ącego) się (krajobrazie|otoczeniu|świecie)\b/gi,
    /\bw (stale|nieustannie|ciągle) (zmieniającym|ewoluującym) się (krajobrazie|świecie|otoczeniu)\b/gi,
    /\bkrajobraz (stale|ciągle|nieustannie) (się zmienia|ewoluuje|przekształca)\b/gi,
    /\bnawigowa(ć|nie) (po|w|przez) (złożonym |skomplikowanym )?(krajobrazie|świecie|otoczeniu)\b/gi,
    /\bzanurzmy się w\b/gi,
    /\bzagłębi(ć|ając|my) się w\b/gi,
    /\bzanurzy(ć|my) się w\b/gi,
    /\bgłębsze (zrozumienie|wgląd|spojrzenie) (na|w)\b/gi,
    /\bpodróż transformacyjna\b/gi,
    /\btransformacyjna (podróż|zmiana|doświadczenie)\b/gi,
    /\bwyrusz(yć|ając|my) w (tę|naszą) podróż\b/gi,
    /\bgobelin\b/gi,
    /\btkanka (czegoś|tego|naszego)\b/gi,
    /\bwarto (zauważyć|podkreślić|zaznaczyć|odnotować|wspomnieć)(,)? (że|iż)\b/gi,
    /\bnależy (zauważyć|podkreślić|zaznaczyć|odnotować|wspomnieć)(,)? (że|iż)\b/gi,
    /\b(ostatecznie|w ostatecznym rozrachunku) (decyzja|wybór) (należy|zależy) (do ciebie|od ciebie)\b/gi,
    /\bholistyczne (podejście|spojrzenie|ujęcie)\b/gi,
    /\bpodejście holistyczne\b/gi,
    /\b(bezproblemow(a|e|y)|bezszwow(a|e|y)) integracja\b/gi,
    /\bintegr(ować|acja|ując) się? (bezproblemowo|płynnie|perfekcyjnie)\b/gi,
    /\bpłynnie (zintegrować|połączyć|scalić)\b/gi,
    /\b(odblokowa(ć|nie)|uwolnić) (potencjał(u)?|nowe możliwości|siłę)\b/gi,
    /\bwspiera(ć|nie) (innowacji|innowacje|wzrostu|wzrost|współpracy|współpracę)\b/gi,
    /\bzniuansowane (zrozumienie|spojrzenie|podejście)\b/gi,
    /\bniuans(y|ów) (zrozumienia|podejścia|perspektywy)\b/gi,
    /\bskrupulatna (uwaga|analiza|dbałość)\b/gi,
    /\bstale (zmieniający|ewoluujący|przekształcający) się (świat|środowisko|krajobraz)\b/gi,
    /\bdynamiczne (środowisko|krajobraz|ekosystem|otoczenie)\b/gi,
    /\b(kluczow(ą|e|y)|zasadnicz(ą|e|y)|istotn(ą|e|y)|ważn(ą|e|y)) rol(ę|a)\b/gi,
    /\bw (wielkim schemacie|szerszej perspektywie) (rzeczy|tego wszystkiego)?\b/gi,
    /\bfilar(y)? (fundamentaln(e|y)|kluczow(e|y))\b/gi,
    /\bkamień(ie)? węgieln(y|e) (czegoś|tego)\b/gi,
    /\bkluczowe (wnioski|spostrzeżenia|ustalenia|obserwacje)\b/gi,
    /\bbada(ć|jmy) (różnorodne |różne |liczne |rozmaite )?(aspekty|facety|wymiary) (czegoś|tego)\b/gi,
    /\b(potencjał|siła|zdolność) transformacyjn(a|y|e)\b/gi,
    /\bprzełomow(y|a|e) (rozwiązanie|podejście|odkrycie|metoda)\b/gi,
    /\bzmiana paradygmatu\b/gi,
    /\bbez precedensu\b/gi,
    /\bsolidn(e|a|y) rozwiązanie\b/gi,
    /\bkompleksow(y|a|e) (przewodnik|poradnik|przegląd)\b/gi,
    /\bwykorzysta(ć|jąc) (siłę|potęgę|moc) (czegoś|tego)\b/gi,
    /\bw (tym|niniejszym) artykule (zbadamy|omówimy|przeanalizujemy|przyjrzymy się)\b/gi,
    /\bna przestrzeni (całego |tego )?(artykułu|tekstu|wpisu)\b/gi,
    /\bjako (model językowy|asystent AI)\b/gi,
    /\bnie (można|sposób|da się) (przecenić|niedocenić|zignorować|pominąć|lekceważyć|bagatelizować)\b/gi,
    /\brzuci(ć|ając) (światło|nowe światło) na\b/gi,
    /\bbez (równego|sobie równych)\b/gi,
    /\bskarbnica (informacji|wiedzy|zasobów)\b/gi,
    /\bniezbadane (terytorium|obszar(y)?|tereny)\b/gi,
    /\bnajnowsz(ej|a|e|y) generacji\b/gi,
    /\bnajnowsz(a|e|y) (technologi(a|e)|rozwiązani(a|e))\b/gi,
    /\bna czele (innowacji|zmian|postępu|rozwoju)\b/gi,
    /\bna (przedniej|czołowej) linii\b/gi,
    /\bnastępna granica\b/gi,
    /\bskłaniający do (refleksji|myślenia|zastanowienia|przemyśleń)\b/gi,
    /\bw ostatecznym rozrachunku\b/gi,
    /\bpodsumowując\b/gi,
    /\bna zakończenie\b/gi,
    /\bw (podsumowaniu|skrócie)\b/gi,
    /\bkoncertując\b/gi,
    /\bpatrząc w przyszłość\b/gi,
    /\bz myślą o przyszłości\b/gi,
    /\bidąc dalej\b/gi,

    // Structural patterns in Polish
    /^(Podsumowując|Reasumując|Na zakończenie|Konkludując|Ostatecznie),?\s/mi,
    /\bNie tylko .{10,50} (ale|lecz) (również|także|i|dodatkowo)\b/gi,
    /\bPomimo .{5,30},? .{5,30} (stawia|stoi|staje|napotyka) (przed )?(wyzwania(mi)?|trudności(ami)?|przeszkod(y|ami))\b/gi,
    /\bPerspektywy (na przyszłość|przyszłe):?\b/gi,

    // AI antithesis patterns in Polish
    /\bNie chodzi (tylko|jedynie|wyłącznie) o .{5,40}[,;] (chodzi|ale) (także )?o\b/gi,
    /\bTo nie (jest|są) .{5,40}[,;] to (jest|są) .{5,40}\b/gi,
    /\bNie .{5,40}[,;] (lecz|ale) .{5,40}\b/gi,
    /\bMniej .{5,30}[,;] więcej .{5,30}\b/gi,
    /\bZapomnij o .{5,30}[,;] (skup się na|pomyśl o|postaw na) .{5,30}\b/gi,

    // Excessive transition words (Polish) - ChatGPT overuses these heavily
    /\b(Ponadto|Co więcej|Dodatkowo|W konsekwencji|Jednakże|Niemniej jednak|Tym niemniej|W związku z tym),?\s/gi,
    /\b(Warto (podkreślić|zaznaczyć|zauważyć|wspomnieć)|Należy (podkreślić|zaznaczyć|zauważyć)|Trzeba (podkreślić|zaznaczyć))(,?\s)?(że|iż)\b/gi,
    /\b(Nie trzeba (dodawać|wspominać)|Oczywiste jest|Nie ulega wątpliwości)(,)?\s?(że|iż)\b/gi,

    // Generic openers in Polish
    /^W (dzisiejszym|współczesnym|nowoczesnym|obecnym|naszym) (świecie|krajobrazie|środowisku|czasie|społeczeństwie|erze),?\s/mi,
    /^(W|Dzięki|Poprzez|Z|W trakcie) .{20,60}(nadal|staje się|jest coraz|rośnie|nabiera znaczenia|zyskuje na znaczeniu)\b/mi,

    // Listicle patterns in Polish
    /\b\d+\s+(sposobów|powodów|wskazówek|trików|sekretów|korzyści|zalet)\s+(na|aby|żeby|do|jak)\b/gi,
    /\b(Najlepsze|Najważniejsze|Kluczowe)\s+\d+\b/gi,
    /\b(Kompletny|Kompleksowy|Wyczerpujący) przewodnik (po|do|na temat)\b/gi,
    /\bWszystko,? co (musisz|powinieneś|trzeba|warto) wiedzieć (o|na temat)\b/gi,
    /\bPrzewodnik (dla|krok po kroku) (początkujących )?(po|na temat|do)\b/gi,

    // Unearned profundity in Polish
    /\bCoś się (zmieniło|zaczęło zmieniać)\b/gi,
    /\bWszystko się (zmieniło|zaczęło zmieniać)\b/gi,
    /\bAle (oto|tutaj jest|tu jest) (klucz|sedno|najważniejsze)\b/gi,
    /\b(Oto|To jest to),? czego (się)? nauczyłem\b/gi,

    // AI content mill phrases in Polish
    /\b(przełom|postęp) (rewolucyjny|bez precedensu)\b/gi,
    /\b(gigantyczny|kwantowy|monumentalny) (skok|krok) (naprzód|do przodu)\b/gi,
    /\b(ekscytujące|fascynujące|niezwykłe|niesamowite) (możliwości|perspektywy|szanse)\b/gi,
    /\b(zawrotne|oszałamiające|zatrważające) (tempo|prędkość|szybkość)\b/gi,
    /\b(zaawansowana|nowoczesna|najnowsza) (technologia|metoda)\b/gi,
    /\b(zaskakujące|imponujące|nadzwyczajne) (rezultaty|wyniki|osiągnięcia)\b/gi,
    /\b(rzeczywisty|namacalny|realny) wpływ\b/gi,
    /\bjasne jest(,)?\s?(że|iż)\b/gi,
    /\bjest (jasne|oczywiste|pewne)(,)?\s?(że|iż)\b/gi,
    /\bod .{5,30} (po|do) .{5,30}, (to|ta|ten|te)\b/gi,
    /\bWyobraź sobie .{10,50} — to (jest|właśnie)\b/gi,
    /\bPrzez (dziesięciolecia|lata|dekady),? .{10,50} (wydawał|wydawało|wydawały) się\b/gi,

    // Additional AI tells in Polish
    /\bkrajobraz (nieustannie|ciągle|stale) (się zmienia|ewoluuje|przekształca)\b/gi,
    /\bkluczowe (jest|aby|jest to|pozostaje)(,)? (aby )?(zrozumieć|zauważyć|podkreślić|uznać)\b/gi,
    /\bistotne (jest|aby)(,)? (zrozumieć|zauważyć|podkreślić|uznać)\b/gi,
    /\bważne (jest|aby)(,)? (zrozumieć|zauważyć|podkreślić|pamiętać)(,)? (że|iż)\b/gi,
    /\bwarto (również )?(wspomnieć|zaznaczyć|podkreślić)(,)? (że|iż)\b/gi,
    /\bnależy (rozważyć|zrozumieć|uznać|wziąć pod uwagę|zdać sobie sprawę)\b/gi,
    /\budowodnion(a|e|y) (skuteczność|historia|ścieżka|dorobek|doświadczenie|osiągnięcia)\b/gi,
    /\b(zakorzeniona|ugruntowana|wieloletnia|długoletnia) (tradycj(a|e)|praktyk(a|i)|histori(a|e))\b/gi,
    /\bspoglądając (w|ku) przyszłość\b/gi,
    /\bkształtowa(ć|nie) (przyszłości|jutra)\b/gi,
    /\bgotow(y|a|e) (aby|żeby|do|by) (stać się|przekształcić|zrewolucjonizować)\b/gi,
    /\bna progu (nowej )?(ery|epoki|przełomu|rewolucji|przyszłości)\b/gi,
    /\bwyznaczy(ć|ając|liśmy) (nową|nadchodzącą) erę\b/gi,
    /\brozpoczyna(ć|jący) nową (erę|epokę|rozdział)\b/gi,
    /\bstanowi(ć|ąc)? (punkt zwrotny|przełom|kamień milowy)\b/gi,
    /\bpunkt zwrotny\b/gi,
    /\bprzełomowy moment\b/gi,
    /\bidealna burza\b/gi,
    /\bkonwergencja (czynników|sił|trendów)?\b/gi,
    /\bprzecięcie (się)?\b/gi,
    /\bna (styku|skrzyżowaniu|czele) (czegoś|wielu|różnych)?\b/gi,
    /\blider(ować|ując) (w|na|przez)\b/gi,
    /\bpioniersk(i|ie|a) (podejście|rozwiązanie|metoda)\b/gi,
    /\bpionier(zy)? (w|w zakresie|w dziedzinie)\b/gi,
    /\bniezrównan(y|a|e)\b/gi,
    /\bwykładniczy (wzrost|rozwój|postęp)\b/gi,
    /\bwyjątkow(a|e|y) (możliwość|szansa|okazja)\b/gi,
    /\bniewątpliwie\b/gi,
    /\bniezaprzeczalnie\b/gi,
    /\bbezsprzecznie\b/gi,
    /\bbez (cienia|najmniejszej) wątpliwości\b/gi,
    /\bbez wątpienia\b/gi,
    /\bto mówi samo za siebie\b/gi,
    /\bzbędne jest (mówić|dodawać|wspominać)\b/gi,
    /\bkrótko mówiąc\b/gi,
    /\binnymi słowy\b/gi,
    /\bw gruncie rzeczy\b/gi,
    /\breasumując\b/gi,
    /\bmając to na uwadze,\b/gi,
    /\bw (tym|obecnym) momencie\b/gi,
    /\bzyskuj(ąc|e) na (popularności|znaczeniu|sile)\b/gi,
    /\bna (fali wznostowej|wznoszącej fali|fali wzrostowej)\b/gi,
    /\b(eksplozywny|meteoryczny|zawrotny) wzrost\b/gi,
    /\bmeteoryczny (wzlot|rozwój|awans)\b/gi,
    /\bwzrost bez precedensu\b/gi,
    /\bsukces bez (porównania|precedensu)\b/gi,
    /\brekordowy (wzrost|rozwój|postęp)\b/gi,

    // Polish-specific ChatGPT tells - overuse of formal/stiff constructions
    /\bnależy (podkreślić|stwierdzić|wskazać|zaznaczyć)(,)? że\b/gi,
    /\bma (kluczowe|zasadnicze|fundamentalne|ogromne) znaczenie\b/gi,
    /\bjest (niezwykle|niezmiernie|niesłychanie) (ważn(e|y|a)|istotn(e|y|a))\b/gi,
    /\b(wieloaspektow(y|a|e)|wielowymiarow(y|a|e)) (kwestia|wyzwanie|problem|zagadnienie)\b/gi,
    /\bw świetle (tego|tych|powyższego)\b/gi,
    /\bz uwzględnieniem\b/gi,
    /\bnie (ma|ulega) (żadnych )?(wątpliwości)(,)? (że|iż)\b/gi,
    /\bodgrywa (nieocenioną|niezbędną|niezastąpioną) rolę\b/gi,
    /\bniuanse (czegoś|tego|tematu)\b/gi,
    /\bsolidn(a|e|y) (baz(a|ę)|fundament|podstaw(a|y)) (do|dla|pod)\b/gi,
    /\bw coraz (bardziej zglobalizowanym|bardziej cyfrowym|bardziej połączonym) (świecie|erze)\b/gi,
    /\baby (w pełni|całkowicie) (zrozumieć|docenić|pojąć)\b/gi,
    /\b(podstawow(y|a|e)|leżąc(y|a|e) u podstaw) (przyczyn(a|y)|mechanizm|dynamik(a|i))\b/gi,
    /\bw (zgodzie|harmonii) z\b/gi,
    /\bw dzisiejszym dynamicznym świecie\b/gi,
    /\bsolidna podstawa\b/gi,
    /\bzrównoważony rozwój\b/gi,
    /\bto dopiero (początek|wierzchołek góry lodowej)\b/gi,
    /\bjak (więc|zatem|wobec tego|w takim razie)\b/gi,
    /\bprzyjrzyjmy się (bliżej|dokładniej)\b/gi,
    /\bspójrzmy na to z (innej|szerszej) perspektywy\b/gi,
    /\bnie sposób (przecenić|pominąć|zignorować)\b/gi,
    /\bz (całą|pełną) pewnością\b/gi,
    /\b(istotne|ważne) jest(,| to)(,)? (aby|żeby|by)\b/gi,
    /\bkluczem (jest|do sukcesu|do zrozumienia)\b/gi,
    /\bco (ciekawe|interesujące|istotne|ważne),\b/gi,
    /\bw obliczu (tych|rosnących|współczesnych) wyzwań\b/gi,
    /\bna (szczególną|wyjątkową) uwagę zasługuje\b/gi,
    /\bw erze (cyfryzacji|sztucznej inteligencji|technologii)\b/gi,
    /\bpotężne narzędzie\b/gi,
    /\bzaangażowanie (interesariuszy|wszystkich stron)\b/gi,
    /\bw kontekście\b/gi,
    /\bw tym (kontekście|zakresie)\b/gi,
    /\bna uwagę zasługuje\b/gi,
    /\bz tego (wynika|płynie)\b/gi,
    /\bnie bez (powodu|przyczyny|znaczenia)\b/gi,
    /\bjest to o tyle istotne\b/gi,
    /\bhistoryczny rekord\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Jestem|Jesteśmy) (bardzo )?(podekscytowan(y|a)|dumn(y|a)|zaszczyczon(y|a)|szczęśliw(y|a)|radn(y|a)|zadowolon(y|a)|wdzięczn(y|a)) (mogąc|że mogę|że możemy) (ogłosić|podzielić się|zaprezentować|ujawnić|opowiedzieć)/gim,
    /^(Nie mogę|Nie możemy) się doczekać (aby|żeby|aż) (podzielić się|ogłosić|zaprezentować|ujawnić|opowiedzieć)/gim,
    /^(Wspaniałe|Ekscytujące|Fantastyczne|Niesamowite|Wielkie) (wiadomości|wieści|nowiny|informacje)[!:]/gim,
    /^Właśnie (uruchomiliśmy|wystartowaliśmy|zaprezentowaliśmy|opublikowaliśmy|wprowadziliśmy)\b/gim,
    /^(Dziś|Dzisiaj|W tym tygodniu|W tym miesiącu) (jestem|jesteśmy) (dumn(y|a|i)|zadowolon(y|a|i)|szczęśliw(y|a|i)) (mogąc|że mogę|że możemy)\b/gim,
    /^(Dziś|Dzisiaj|W tym tygodniu|W tym miesiącu) (ogłaszam|ogłaszamy|prezentujemy|uruchamiamy)\b/gim,
    /^Podekscytowan(y|a|i) (mogąc|że mogę|że możemy) (podzielić się|ogłosić|zaprezentować)\b/gim,
    /^Dumn(y|a|i) (mogąc|że mogę|że możemy|aby|żeby) (podzielić się|ogłosić|zaprezentować|ujawnić)\b/gim,
    /^Z (radością|dumą|przyjemnością) (ogłaszam|informuję|dzielę się|prezentuję|informujemy|dzielimy się|ogłaszamy)\b/gim,
    /^Szczęśliw(y|a|i) (mogąc|że mogę|że możemy) (podzielić się|ogłosić|zaprezentować)\b/gim,
    /^Zaszczyczon(y|a|i) (mogąc|że mogę|że możemy) (podzielić się|ogłosić|zaprezentować)\b/gim,
    /^Zgadnijcie (co|kto)[!?]/gim,
    /^Nie (uwierzycie|zgadniecie)\b/gim,
    /^(Spójrzcie na|Zobaczcie|Popatrzcie) (to|co)\b/gim,
    /^(Wielkie|Ogromne) (ogłoszenie|wiadomość|nowina)[!:]/gim,
    /^(Nareszcie|W końcu|Wreszcie)[,!]/gim,
    /^(Gorąca|Pilna|Najnowsza) (wiadomość|informacja|nowość)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in Polish (2 points per match)
  tier2: [
    /\bsynergi(a|e|i|ę|ą)\b/gi,
    /\blewarow(ać|anie)\b/gi,
    /\bdźwigni(a|ę) (finansow(a|ą)|operacyjn(a|ą))\b/gi,
    /\bfollow[- ]?up\b/gi,
    /\bnisko wiszące owoce\b/gi,
    /\bprzesun(ąć|ięcie) (igł(ę|y)|wskaźnika?)\b/gi,
    /\bmyśle(ć|nie) (poza schematem|nieszablonowo|poza ramami)\b/gi,
    /\bskontak(tować|tuj) się\b/gi,
    /\bpiwot(ować|owanie)\b/gi,
    /\bpivot(ować)?\b/gi,
    /\bdysruptywn(y|a|e|ość)\b/gi,
    /\bdysrupcyjn(y|a|e)\b/gi,
    /\bskalow(ać|anie|alność)\b/gi,
    /\bzwinny\b/gi,
    /\bzwinne (zarządzanie|podejście|metodyki)\b/gi,
    /\bagile\b/gi,
    /\bprzepustowość\b/gi,
    /\bkompetencj(a|e|i) (kluczow(a|e)|podstawow(a|e)|rdzenn(a|e))\b/gi,
    /\binteresariusz(e|y|om|ami)\b/gi,
    /\bpropozycja wartości\b/gi,
    /\blider (myśli|opinii)\b/gi,
    /\bnajlepsz(e|a) praktyk(i|a)\b/gi,
    /\btransformacja (cyfrowa|cyfrowej|biznesowa|technologiczna)\b/gi,
    /\bnapędzany? (przez |prze )?(AI|sztuczn(ą|ej) inteligencj(ę|i))\b/gi,
    /\bopart(y|a|e) na chmurze\b/gi,
    /\bw chmurze|chmurowy\b/gi,
    /\b(zorientowan(y|a|e)|nakierowan(y|a|e)) na (klienta|dane)\b/gi,
    /\bklientocentryczn(y|a|e)\b/gi,
    /\bprzewag(a|i|ę) konkurencyjn(a|e|ą)\b/gi,
    /\budział(y)? (w )?(rynk(u|owy|owe|owych))\b/gi,
    /\bROI\b/gi,
    /\bKPI\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\bdeliverable(s)?\b/gi,
    /\bpunkt(y)? akcji\b/gi,
    /\bupodmiotow(ić|ienie|anie)\b/gi,
    /\bempowerment\b/gi,
    /\bnapędzać innowacj(e|ę)\b/gi,
    /\boptymalizow(ać|anie|acja)\b/gi,
    /\bmaksymalizow(ać|anie|acja)\b/gi,
    /\bdostosow(ać|anie|ywanie) (do|się do|pod)\b/gi,
    /\bwspółprac(a|ować|owanie)\b/gi,
    /\bmiędzydziałow(y|a|e|ość)\b/gi,
    /\bmiędzyfunkcyjn(y|a|e)\b/gi,
    /\brozwiązanie (kompleksowe|integralne|całościowe)\b/gi,
    /\bod początku do końca\b/gi,
    /\brozwiązanie end-to-end\b/gi,
    /\bnatywn(y|a|e) (w |dla )?chmur(y|ze|owo)\b/gi,
    /\bcloud[- ]?native\b/gi,
    /\bskonteneryzowany\b/gi,
    /\bkonteneryz(acja|ować|owane)\b/gi,
    /\bmikroserwisy\b/gi,
    /\bmikrousług(i|a|ę)\b/gi,
    /\bserverless\b/gi,
    /\bnapędzan(y|a|e) (danymi|zdarzeniami)\b/gi,
    /\b(opart(y|a|e)|bazując(y|a|e)) na danych\b/gi,
    /\bczas rzeczywisty|real-?time\b/gi,
    /\bwysoka (dostępność|wydajność)\b/gi,
    /\bskalowaln(y|a|e|ość)\b/gi,
    /\bmodulow(y|a|e|ość)\b/gi,
    /\belastyczn(y|a|e|ość)\b/gi,
    /\bprzyjazn(y|a|e) (dla )?(użytkownika|użytkownikowi|użytkowników)\b/gi,
    /\bintuicyjn(y|a|e)\b/gi,
    /\bdoświadczenie użytkownika\b/gi,
    /\btransformacja (biznesowa|biznesu)\b/gi,
    /\bekosystem (cyfrowy|technologiczny)\b/gi,
    /\bplatforma (cyfrowa|technologiczna|zintegrowana)\b/gi,
    /\bzarządzanie zmianą\b/gi,
    /\bdigitalizacja\b/gi,
    /\bautomatyzacja procesów\b/gi,
    /\bstakeholder(ów|om|zy|ami)?\b/gi,
    /\bbenchmark(i|ów|owanie)?\b/gi,
    /\bonboarding\b/gi,
    /\bpipeline\b/gi,
    /\broadmap(a|ę|y)?\b/gi,
    /\bvalue stream\b/gi,
    /\bworkflow\b/gi,
    /\bbacklog\b/gi,
    /\bwartość (biznesowa|dodana)\b/gi,
    /\bstrategi(a|czn(y|a|e)) (pozycjonowani(e|a)|kierunek)\b/gi,
    /\bścieżka wzrostu\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Cliches in Polish (1 point per match)
  tier3: [
    /\bza darmo\b/gi,
    /\bgwarantowan(y|a|e)\b/gi,
    /\bniewiarygodny\b/gi,
    /\bniewiarygodnie\b/gi,
    /\boszałamiając(y|a|e)\b/gi,
    /\bzapierający dech (w piersiach)?\b/gi,
    /\bimponując(y|a|e|o)\b/gi,
    /\brewolucyjn(y|a|e)\b/gi,
    /\bcudotwórcz(y|a|e)\b/gi,
    /\bcudown(y|a|e|ie)\b/gi,
    /\bnajlepsz(y|a|e) w (swojej|tej) klasie\b/gi,
    /\bna najwyższym poziomie\b/gi,
    /\bpierwsz(a|y|e) klas(a|y)\b/gi,
    /\bnajnowsza technologia\b/gi,
    /\bkliknij tutaj\b/gi,
    /\bkup teraz\b/gi,
    /\bdziałaj (teraz|natychmiast|od razu)\b/gi,
    /\boferta (ograniczona|limitowana) (czasowo|ilościowo)?\b/gi,
    /\bnie czekaj\b/gi,
    /\braz w życiu\b/gi,
    /\bbez (zobowiązań|obowiązku)\b/gi,
    /\bbez ryzyka\b/gi,
    /\bpodwój (swoje |)(przychody|dochody|zyski|zarobki)\b/gi,
    /\bzarób (pieniądze|gotówkę)\b/gi,
    /\bzarabiaj (pieniądze|online|z domu)\b/gi,
    /\bszybki (zarobek|pieniądz)\b/gi,
    /\bszybkie pieniądze\b/gi,
    /\budowodnione (rezultaty|wyniki|efekty)\b/gi,
    /\bpromocja specjalna\b/gi,
    /\boferta specjalna\b/gi,
    /\boszczędzaj (więcej|dużo|wielkie pieniądze)\b/gi,
    /\bduże oszczędności\b/gi,
    /\bnajniższ(a|e|y) cen(a|y)\b/gi,
    /\bnajlepsz(a|e|y) (oferta|cena|okazja)\b/gi,
    /\bbez kosztów\b/gi,
    /\bbezpłatna (konsultacja|porada|wycena)\b/gi,
    /\bniezbędny\b/gi,
    /\bobowiązkow(y|a|e)\b/gi,
    /\bna (wyższy|następny|kolejny) poziom\b/gi,
    /\bpodnieść (poprzeczkę|standardy)\b/gi,
    /\bwyróżnić się (z|na tle|spośród) (tłumu|konkurencji|innych)\b/gi,
    /\brozejść się jak ciepłe bułeczki\b/gi,
    /\brozchodzić się lotem błyskawicy\b/gi,
    /\bwierzchołek góry lodowej\b/gi,
    /\btreść jest królem\b/gi,
    /\bw (pigułce|telegraficznym skrócie)\b/gi,
    /\bw skrócie\b/gi,
    /\bzasadniczo\b/gi,
    /\bw istocie\b/gi,
    /\bobecnie\b/gi,
    /\bwłaściwie\b/gi,
    /\bfantastyczn(y|a|e|ie)\b/gi,
    /\bspektakularn(y|a|e|ie)\b/gi,
    /\bfenomenaln(y|a|e|ie)\b/gi,
    /\bnadzwyczajn(y|a|e|ie)\b/gi,
    /\bsensacyjn(y|a|e|ie)\b/gi,
    /\bzaskakując(y|a|e|o)\b/gi,
    /\bwspaniał(y|a|e|le)\b/gi,
    /\bepick(i|a|ie)\b/gi,
    /\blegendarn(y|a|e)\b/gi,
    /\bekskluzywny dostęp\b/gi,
    /\btylko (na|za) zaproszenie(m)?\b/gi,
    /\bjuż wkrótce\b/gi,
    /\bwkrótce\b/gi,
    /\bnie przegap\b/gi,
    /\bFOMO\b/gi,
    /\bstrach przed (przegapieniem|utratą)\b/gi,
    /\bpośpiesz się\b/gi,
    /\btrik(i|ów)?\b/gi,
    /\bwskazówk(i|a) i trik(i|ów)\b/gi,
    /\bpro[- ]?tip(y|ów)?\b/gi,
    /\blife ?hack(i|ów)?\b/gi,
    /\bgrowth ?hack(ing|i|ów)?\b/gi,
    /\b(plan|przewodnik|instrukcja) krok po kroku\b/gi,
    /\b(sprawdzony|udowodniony) system\b/gi,
    /\błatwo jak\b/gi,
    /\bproste jak\b/gi,
    /\bszybko i (prosto|łatwo)\b/gi,
    /\bw (zaledwie|tylko) \d+ (minut|godzin|dni)\b/gi,
    /\bsukces z dnia na dzień\b/gi,
    /\bnatychmiastowe (rezultaty|wyniki|efekty)\b/gi,
    /\bzacznij (dziś|teraz|za darmo)\b/gi,
    /\bzarejestruj się (teraz|za darmo)\b/gi,
    /\bdołącz (teraz|za darmo|do tysięcy|do milionów)\b/gi,
    /\b(tysiące|miliony|miliardy) (użytkowników|klientów|osób|ludzi)\b/gi,
    /\bnagradzany|nagrodziany\b/gi,
    /\bprzekształć (swoje |)(życie|biznes|karierę)\b/gi,
    /\bzmień swoje życie\b/gi,
    /\b(odblokuj|uwolnij) (swój |swoje |swoją )?(potencjał|sukces)\b/gi
  ],

  // Political content patterns - Polish political context
  political: [
    /\b(polityk(a|i)|polityczn(y|a|e|ych)|partyjn(y|a|e))\b/gi,
    /\b(socjaldemokra(ta|ci)|konserwatysta|liberał|ludowiec|lewicowiec|prawicowiec)\b/gi,
    /\b(lewic(a|ow(y|a|e))|prawic(a|ow(y|a|e))|centrolewic(a|ow(y|a|e))|centroprawic(a|ow(y|a|e))|skrajna lewica|skrajna prawica)\b/gi,
    /\b(postępow(y|a|e|iec)|populist(a|yczn(y|a|e))|nacjonalist(a|yczn(y|a|e))|globalist(a|yczn(y|a|e)))\b/gi,
    /\b(Sejm|Senat|Trybunał (Konstytucyjny|Stanu)|Sąd Najwyższy)\b/gi,
    /\b(rząd|Pałac Prezydencki|Kancelaria (Prezesa|Premiera)|Wiejska)\b/gi,
    /\b(wybory|głosow(ać|anie)|urna|kampania (wyborcza)?|kandydatur(a|y)|prawybory)\b/gi,
    /\b(ustawodawstw(o|a)|projekt ustawy|ustaw(a|y)|nowelizacja|weto|dekret)\b/gi,
    /\b(wotum nieufności|impeachment|odwołanie|kryzys (rządowy|polityczny))\b/gi,
    /\b(prezydent|premier|senator|poseł|marszałek|polityk|kandydat(ka)?|minister)\b/gi,
    /\b(inflacj(a|i|ę)|recesj(a|i|ę)|kryzys gospodarczy|stymulacj(a|i) (ekonomiczn(a|ej)|gospodarczej))\b/gi,
    /\b(NBP|Narodowy Bank Polski|EBC|stopy procentowe|stopa referencyjna)\b/gi,
    /\b(dług (publiczny|państwa|narodowy)|deficyt budżetowy|pakiet ratunkowy)\b/gi,
    /\b(budżet (państwa)?|ustawa budżetowa|deficyt|plan finansowy)\b/gi,
    /\b(cł(a|o)|sankcj(a|e|i)|wojna handlowa)\b/gi,
    /\b(bezrobocie|rynek pracy|zatrudnienie|raport o (zatrudnieniu|pracy))\b/gi,
    /\b(aborcj(a|i|ę)|pro[- ]life|pro[- ]choice|prawo (do )?(wyboru|aborcji))\b/gi,
    /\b(broń|prawo do (posiadania )?broni|pozwolenie na broń|kontrola broni)\b/gi,
    /\b(imigracja|kryzys (migracyjny|graniczny|uchodźczy)|uchodźc(y|ów)|polityka azylowa|integracja imigrantów)\b/gi,
    /\b(zmian(a|y) klimat(u|yczne)|globalne ocieplenie|zielony ład|polityka klimatyczna|zielona transformacja)\b/gi,
    /\b(służba zdrowia|NFZ|system opieki zdrowotnej|ochrona zdrowia|sektor publiczny)\b/gi,
    /\b(reforma podatkowa|obniżk(a|i) podatków|obciążenia podatkowe|podatkowy)\b/gi,
    /\b(kultura (wymazywania|unieważniania|wykluczenia)|cancel culture|poprawność polityczna|polityka tożsamości|woke)\b/gi,
    /\b(różnorodność i (inkluzja|włączenie)|DEI|równouprawnienie)\b/gi,
    /\b(praw(a|o) (osób )?(trans|LGBT|LGBTQ|reprodukcyjne))\b/gi,
    /\b(cenzur(a|y)|wolność (słowa|prasy|mediów))\b/gi,
    /\b(patriot(a|yzm)|nacjonalizm|suwerenność|głębokie państwo|globalizm)\b/gi,
    /\b(media (głównego nurtu|korporacyjne|mainstreamowe)|mainstream[- ]?owe media|elity medialne|fake news|propaganda)\b/gi,
    /\b(spisek|spiskow(y|a|e)|teoria spiskowa|tuszowanie|prawda,? (której|którą))\b/gi,
    /\b(demokracja|wolność|tyrania|dyktatura|autorytarn(y|a|e|izm))\b/gi,
    /\b(socjalistyczn(a|y|e)|komunistyczn(a|y|e)) agenda\b/gi,
    /\b(zagrożenie dla demokracji|obrona demokracji)\b/gi,
    /\b(państwo prawa|praworządność|trójpodział władzy)\b/gi,
    /\b(PiS|Prawo i Sprawiedliwość)\b/gi,
    /\b(PO|Platforma Obywatelska)\b/gi,
    /\b(Lewica|Nowa Lewica|SLD|Razem)\b/gi,
    /\b(PSL|Polskie Stronnictwo Ludowe)\b/gi,
    /\b(Konfederacja|Konfederacja Wolność i Niepodległość)\b/gi,
    /\b(Polska 2050|Trzecia Droga)\b/gi,
    /\b(Kukiz'15|Kukiz)\b/gi,
    /\b(Kaczyński|Tusk|Morawiecki|Duda|Hołownia|Kosiniak-Kamysz|Biedroń|Bosak|Korwin|Mentzen)\b/gi,
    /\b(NATO|UE|Unia Europejska|Grupa Wyszehradzka|V4|Trójmorze|Bruksel(a|i))\b/gi,
    /\b(polexit|polexitu)\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'zagłębić się w': 'zbadać, przeanalizować, przyjrzeć się',
    'zanurzmy się w': 'zbadajmy, przeanalizujmy, przyjrzyjmy się',
    'w dynamicznie zmieniającym się krajobrazie': 'w obecnej sytuacji, w tym sektorze',
    'nawigować po krajobrazie': 'zrozumieć sytuację, zbadać pole',
    'zmiana paradygmatu': 'istotna zmiana, fundamentalna przemiana',
    'przełomowe rozwiązanie': 'znaczący postęp, ważne osiągnięcie',
    'potencjał transformacyjny': 'opisz konkretną zmianę, która zachodzi',
    'odblokować potencjał': 'umożliwić, ułatwić, otworzyć drogę',
    'uwolnić potencjał': 'umożliwić, pozwolić, stworzyć warunki',
    'bezproblemowa integracja': 'integrować, łączyć, współdziałać',
    'płynnie zintegrować': 'zintegrować, połączyć, scalić',
    'holistyczne podejście': 'pełna metoda, wszechstronna strategia, całościowe spojrzenie',
    'solidne rozwiązanie': 'niezawodny system, sprawdzone podejście',
    'zanurzyć się w': 'szczegółowa analiza, dokładne zbadanie',
    'gobelin': 'zbiór, mieszanina, mozaika',
    'bez precedensu': 'wyjaśnij, co czyni to wyjątkowym',
    'pionierskie podejście': 'innowacyjne, nowe, wyjaśnij na czym polega nowość',
    'skarbnica informacji': 'zbiór, źródło, zasób',
    'niezbadane terytorium': 'nowy obszar, nieznany teren',
    'rzucić światło na': 'wyjaśnić, ujawnić, naświetlić',
    'w ostatecznym rozrachunku': 'ostatecznie, w efekcie',
    'patrząc w przyszłość': 'w przyszłości, w następnym kroku',
    'kluczowe wnioski': 'główne punkty, podsumowanie, wnioski',
    'przełom bez precedensu': 'wyjaśnij, jaką barierę pokonano',
    'jasne jest, że': 'wyraź swoją myśl bezpośrednio',
    'nie da się przecenić': 'wyjaśnij dokładnie, dlaczego jest to ważne',
    'jestem podekscytowany ogłaszając': 'ogłoś bezpośrednio',
    'dumny mogąc podzielić się': 'podziel się bez samochwalstwa',
    'z radością informuję': 'poinformuj bezpośrednio, bez ozdobników',
    'synergia': 'współpraca, kooperacja',
    'lewarować': 'użyć, zastosować, wykorzystać',
    'nisko wiszące owoce': 'łatwe wygrane, proste zadania',
    'przesunąć igłę': 'poczynić postępy, osiągnąć wynik',
    'myślenie poza schematem': 'kreatywne podejście, innowacyjne myślenie',
    'piwotować': 'zmienić kierunek, dostosować strategię',
    'dysruptywny': 'wyjaśnij, co się zmienia i jak',
    'interesariusze': 'zaangażowane osoby, członkowie zespołu',
    'lider myśli': 'ekspert, specjalista, autorytet',
    'najlepsze praktyki': 'skuteczne metody, sprawdzone podejścia',
    'upodmiotowienie': 'umożliwienie, usamodzielnienie',
    'optymalizować': 'ulepszyć, udoskonalić, usprawnić',
    'niewiarygodny': 'użyj konkretnych opisów',
    'zasadniczo': 'usuń lub bądź precyzyjniejszy',
    'w istocie': 'usuń lub bądź bardziej konkretny',
    'warto zauważyć, że': 'po prostu napisz to, co chcesz powiedzieć',
    'ponadto': 'rozważ usunięcie lub użyj prostszego łącznika',
    'co więcej': 'często zbędne - nadużywane przez AI',
    'w dzisiejszym dynamicznym świecie': 'bądź konkretny - o jakim kontekście mówisz?',
    'solidna podstawa': 'określ dokładnie, na czym się opierasz',
    'potężne narzędzie': 'opisz konkretne możliwości',
    'zrównoważony rozwój': 'wyjaśnij, co konkretnie jest zrównoważone'
  },

  checkerSuggestions: {
    'zagłębić się w': 'Spróbuj: "zbadać", "przeanalizować" lub napisz konkretnie, co robisz',
    'zanurzmy się w': 'Spróbuj: "zbadajmy", "przeanalizujmy" lub bądź bardziej konkretny',
    'nawigować po krajobrazie': 'Bądź konkretny: o jakiej dokładnie sytuacji lub branży mówisz?',
    'zmiana paradygmatu': 'Użyj konkretnych terminów: co dokładnie się zmieniło?',
    'przełomowe rozwiązanie': 'Wyjaśnij, dlaczego to ma znaczenie, zamiast używać żargonu',
    'potencjał transformacyjny': 'Opisz rzeczywistą zmianę',
    'lewarować': 'Spróbuj: "użyć", "zastosować" lub "wykorzystać"',
    'synergia': 'Wyjaśnij rzeczywistą współpracę lub korzyść',
    'zanurzyć się w': 'Napisz: "szczegółowa analiza" lub "dokładne zbadanie"',
    'odblokować': 'Napisz konkretnie, co zostaje umożliwione',
    'uwolnić potencjał': 'Bądź konkretny, co jest umożliwiane',
    'bezproblemowy': 'Pokaż, jak działa integracja, zamiast to deklarować',
    'solidny': 'Opisz konkretne cechy lub mocne strony',
    'kompleksowy': 'Wymień, co obejmuje',
    'holistyczny': 'Wyjaśnij, jak uwzględniasz wszystkie aspekty',
    'dysruptywny': 'Wyjaśnij, co się zmienia i w jaki sposób',
    'bez precedensu': 'Jeśli to prawda, wyjaśnij, co czyni to wyjątkowym',
    'niewiarygodny': 'Użyj konkretnych i mierzalnych opisów',
    'jestem podekscytowany ogłaszając': 'Pomiń marketingowe wstępy. Ogłoś bezpośrednio to, czym się dzielisz.',
    'dumny mogąc podzielić się': 'Pomiń samochwalstwo. Niech treść mówi sama za siebie.',
    'z radością informuję': 'Pomiń emocjonalne opakowanie. Poinformuj bezpośrednio.',
    'warto zauważyć': 'Po prostu powiedz to bezpośrednio, bez zbędnego wstępu.',
    'nie da się przecenić': 'Wyjaśnij dokładnie, dlaczego jest to ważne.',
    'w dzisiejszym dynamicznym świecie': 'Napisz wprost, o jakim kontekście mówisz. To typowy frazes AI.',
    'solidna podstawa': 'Określ dokładnie, na czym się opierasz.',
    'potężne narzędzie': 'Opisz konkretne możliwości zamiast używać ogólników.',
    '—': 'Myślniki em-dash to wyraźna cecha treści generowanych przez AI. Używaj prostej interpunkcji.'
  },

  slopDatabase: [
    { slop: 'zagłębić się w', better: 'zbadać, przeanalizować lub przyjrzeć się', tier: 'tier1' },
    { slop: 'zanurzmy się w', better: 'zbadajmy, przeanalizujmy lub przyjrzyjmy się', tier: 'tier1' },
    { slop: 'nawigować po krajobrazie', better: 'zrozumieć sytuację, zbadać pole', tier: 'tier1' },
    { slop: 'zmiana paradygmatu', better: 'istotna zmiana, fundamentalna przemiana', tier: 'tier1' },
    { slop: 'przełomowe rozwiązanie', better: 'znaczący postęp, ważne osiągnięcie', tier: 'tier1' },
    { slop: 'potencjał transformacyjny', better: 'opisz konkretną zmianę, która zachodzi', tier: 'tier1' },
    { slop: 'odblokować potencjał', better: 'umożliwić, ułatwić, otworzyć drogę', tier: 'tier1' },
    { slop: 'uwolnić potencjał', better: 'umożliwić, pozwolić, stworzyć warunki', tier: 'tier1' },
    { slop: 'bezproblemowa integracja', better: 'integrować, łączyć, współdziałać', tier: 'tier1' },
    { slop: 'holistyczne podejście', better: 'pełna metoda, wszechstronna strategia', tier: 'tier1' },
    { slop: 'solidne rozwiązanie', better: 'niezawodny system, sprawdzone podejście', tier: 'tier1' },
    { slop: 'zanurzyć się w', better: 'szczegółowa analiza, dokładne zbadanie', tier: 'tier1' },
    { slop: 'gobelin', better: 'zbiór, mieszanina, mozaika', tier: 'tier1' },
    { slop: 'bez precedensu', better: 'rzadkie, niezwykłe, lub wyjaśnij co czyni to wyjątkowym', tier: 'tier1' },
    { slop: 'pionierskie podejście', better: 'innowacyjne, nowe, lub wyjaśnij innowację', tier: 'tier1' },
    { slop: 'skarbnica informacji', better: 'zbiór, źródło, zasób', tier: 'tier1' },
    { slop: 'niezbadane terytorium', better: 'nowy obszar, nieznany teren', tier: 'tier1' },
    { slop: 'rzucić światło na', better: 'wyjaśnić, ujawnić, naświetlić', tier: 'tier1' },
    { slop: 'w ostatecznym rozrachunku', better: 'ostatecznie, w efekcie, podsumowując', tier: 'tier1' },
    { slop: 'patrząc w przyszłość', better: 'w przyszłości, w następnym kroku', tier: 'tier1' },
    { slop: 'kluczowe wnioski', better: 'główne punkty, podsumowanie, wnioski', tier: 'tier1' },
    { slop: 'przełom bez precedensu', better: 'wyjaśnij, jaką barierę pokonano', tier: 'tier1' },
    { slop: 'jasne jest, że', better: 'wyraź swoją myśl bezpośrednio, bez wstępów', tier: 'tier1' },
    { slop: 'warto zauważyć, że', better: 'podaj informację wprost, bez preambuły', tier: 'tier1' },
    { slop: 'nie da się przecenić', better: 'wyjaśnij dokładnie, dlaczego jest to istotne', tier: 'tier1' },
    { slop: 'w dzisiejszym dynamicznym świecie', better: 'opisz konkretny kontekst, o którym mówisz', tier: 'tier1' },
    { slop: 'solidna podstawa', better: 'opisz, na czym konkretnie się opierasz', tier: 'tier1' },
    { slop: 'potężne narzędzie', better: 'opisz konkretne możliwości narzędzia', tier: 'tier1' },
    { slop: 'jestem podekscytowany ogłaszając', better: 'ogłoś to bezpośrednio', tier: 'stopwords' },
    { slop: 'dumny mogąc podzielić się', better: 'podziel się bez emocjonalnego opakowania', tier: 'stopwords' },
    { slop: 'z radością informuję', better: 'pomiń samochwalstwo, poinformuj wprost', tier: 'stopwords' },
    { slop: 'z dumą ogłaszam', better: 'ogłoś bez emocjonalnego wstępu', tier: 'stopwords' },
    { slop: 'synergia', better: 'współpraca, kooperacja, wspólny wysiłek', tier: 'tier2' },
    { slop: 'lewarować', better: 'użyć, zastosować, wykorzystać', tier: 'tier2' },
    { slop: 'follow-up', better: 'dalsze działanie, kontynuacja, przypomnienie', tier: 'tier2' },
    { slop: 'nisko wiszące owoce', better: 'łatwe wygrane, proste zadania', tier: 'tier2' },
    { slop: 'przesunąć igłę', better: 'poczynić postępy, osiągnąć wynik', tier: 'tier2' },
    { slop: 'piwotować', better: 'zmienić kierunek, dostosować strategię', tier: 'tier2' },
    { slop: 'dysruptywny', better: 'wyjaśnij, co się zmienia i w jaki sposób', tier: 'tier2' },
    { slop: 'interesariusze', better: 'zaangażowane osoby, członkowie zespołu', tier: 'tier2' },
    { slop: 'lider myśli', better: 'ekspert, specjalista, autorytet', tier: 'tier2' },
    { slop: 'najlepsze praktyki', better: 'skuteczne metody, sprawdzone podejścia', tier: 'tier2' },
    { slop: 'upodmiotowienie', better: 'umożliwienie, usamodzielnienie, danie autonomii', tier: 'tier2' },
    { slop: 'optymalizować', better: 'ulepszyć, udoskonalić, usprawnić', tier: 'tier2' },
    { slop: 'niewiarygodny', better: 'użyj konkretnych i mierzalnych opisów', tier: 'tier3' },
    { slop: 'oszałamiający', better: 'podaj konkretne szczegóły', tier: 'tier3' },
    { slop: 'rewolucyjny', better: 'opisz rzeczywistą zmianę', tier: 'tier3' },
    { slop: 'zasadniczo', better: 'usuń lub bądź precyzyjniejszy', tier: 'tier3' },
    { slop: 'w istocie', better: 'usuń lub bądź bardziej konkretny', tier: 'tier3' },
    { slop: 'myślnik em-dash (---)', better: 'używaj kropek, przecinków, lub usuń dramatyczną pauzę', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\bw (dzisiejszym|obecnym|współczesnym) (dynamicznym|złożonym|szybko zmieniającym się) (świecie|krajobrazie|środowisku)\\b/gi',
      '/\\bw dynamicznie zmieniaj(ącym|ącego) się (krajobrazie|otoczeniu|świecie)\\b/gi',
      '/\\bw (stale|nieustannie|ciągle) (zmieniającym|ewoluującym) się (krajobrazie|świecie|otoczeniu)\\b/gi',
      '/\\bkrajobraz (stale|ciągle|nieustannie) (się zmienia|ewoluuje|przekształca)\\b/gi',
      '/\\bnawigowa(ć|nie) (po|w|przez) (złożonym |skomplikowanym )?(krajobrazie|świecie|otoczeniu)\\b/gi',
      '/\\bzanurzmy się w\\b/gi',
      '/\\bzagłębi(ć|ając|my) się w\\b/gi',
      '/\\bgłębsze (zrozumienie|wgląd|spojrzenie) (na|w)\\b/gi',
      '/\\btransformacyjna (podróż|zmiana|doświadczenie)\\b/gi',
      '/\\bwyrusz(yć|ając|my) w (tę|naszą) podróż\\b/gi',
      '/\\bwarto (zauważyć|podkreślić|zaznaczyć|odnotować|wspomnieć)(,)? (że|iż)\\b/gi',
      '/\\bholistyczne (podejście|spojrzenie|ujęcie)\\b/gi',
      '/\\bpłynnie (zintegrować|połączyć|scalić)\\b/gi',
      '/\\b(odblokowa(ć|nie)|uwolnić) (potencjał(u)?|nowe możliwości|siłę)\\b/gi',
      '/\\bzmiana paradygmatu\\b/gi',
      '/\\bbez precedensu\\b/gi',
      '/\\bsolidn(e|a|y) rozwiązanie\\b/gi',
      '/\\bkompleksow(y|a|e) (przewodnik|poradnik|przegląd)\\b/gi',
      '/\\b(potencjał|siła|zdolność) transformacyjn(a|y|e)\\b/gi',
      '/\\bprzełomow(y|a|e) (rozwiązanie|podejście|odkrycie|metoda)\\b/gi',
      '/\\bzanurzy(ć|my) się w\\b/gi',
      '/\\brzuci(ć|ając) (światło|nowe światło) na\\b/gi',
      '/\\bbez (równego|sobie równych)\\b/gi',
      '/\\bw ostatecznym rozrachunku\\b/gi',
      '/\\bpodsumowując\\b/gi',
      '/\\bna zakończenie\\b/gi',
      '/\\bpatrząc w przyszłość\\b/gi',
      '/\\bkluczowe (wnioski|spostrzeżenia|ustalenia|obserwacje)\\b/gi',
      '/\\b(Ponadto|Co więcej|Dodatkowo|W konsekwencji|Jednakże|Niemniej jednak|Tym niemniej),?\\s/gi',
      '/\\b(Warto (podkreślić|zaznaczyć|zauważyć|wspomnieć)|Należy (podkreślić|zaznaczyć|zauważyć)) (,?\\s)?(że|iż)\\b/gi',
      '/\\bwykładniczy (wzrost|rozwój|postęp)\\b/gi',
      '/\\bpunkt zwrotny\\b/gi',
      '/\\bkonwergencja (czynników|sił|trendów)?\\b/gi',
      '/\\bjest (jasne|oczywiste|pewne)(,)?\\s?(że|iż)\\b/gi',
      '/^W (dzisiejszym|współczesnym|nowoczesnym|obecnym|naszym) (świecie|krajobrazie|środowisku|czasie|społeczeństwie|erze),?\\s/mi',
      '/\\bniewątpliwie\\b/gi',
      '/\\bniezaprzeczalnie\\b/gi',
      '/\\bbez wątpienia\\b/gi',
      '/\\bnie (można|sposób|da się) (przecenić|niedocenić|zignorować|pominąć)\\b/gi',
      '/\\bw dzisiejszym dynamicznym świecie\\b/gi',
      '/\\bsolidna podstawa\\b/gi',
      '/\\bpotężne narzędzie\\b/gi',
      '/\\bna (szczególną|wyjątkową) uwagę zasługuje\\b/gi'
    ],
    tier2: [
      '/\\bsynergi(a|e|i|ę|ą)\\b/gi',
      '/\\blewarow(ać|anie)\\b/gi',
      '/\\bfollow[- ]?up\\b/gi',
      '/\\bpiwot(ować|owanie)\\b/gi',
      '/\\bpivot(ować)?\\b/gi',
      '/\\bdysruptywn(y|a|e|ość)\\b/gi',
      '/\\bskalow(ać|anie|alność)\\b/gi',
      '/\\bzwinny\\b/gi',
      '/\\bkompetencj(a|e|i) (kluczow(a|e)|podstawow(a|e)|rdzenn(a|e))\\b/gi',
      '/\\binteresariusz(e|y|om|ami)\\b/gi',
      '/\\bpropozycja wartości\\b/gi',
      '/\\blider (myśli|opinii)\\b/gi',
      '/\\bnajlepsz(e|a) praktyk(i|a)\\b/gi',
      '/\\btransformacja (cyfrowa|cyfrowej|biznesowa|technologiczna)\\b/gi',
      '/\\bnapędzany? (przez |prze )?(AI|sztuczn(ą|ej) inteligencj(ę|i))\\b/gi',
      '/\\b(zorientowan(y|a|e)|nakierowan(y|a|e)) na (klienta|dane)\\b/gi',
      '/\\bprzewag(a|i|ę) konkurencyjn(a|e|ą)\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI\\b/gi',
      '/\\bupodmiotow(ić|ienie|anie)\\b/gi',
      '/\\boptymalizow(ać|anie|acja)\\b/gi',
      '/\\bmaksymalizow(ać|anie|acja)\\b/gi',
      '/\\bwspółprac(a|ować|owanie)\\b/gi',
      '/\\brozwiązanie (kompleksowe|integralne|całościowe)\\b/gi',
      '/\\bskalowaln(y|a|e|ość)\\b/gi',
      '/\\bintuicyjn(y|a|e)\\b/gi',
      '/\\bekosystem (cyfrowy|technologiczny)\\b/gi',
      '/\\bzarządzanie zmianą\\b/gi',
      '/\\bwartość (biznesowa|dodana)\\b/gi'
    ],
    tier3: [
      '/\\bza darmo\\b/gi',
      '/\\bgwarantowan(y|a|e)\\b/gi',
      '/\\bniewiarygodny\\b/gi',
      '/\\boszałamiając(y|a|e)\\b/gi',
      '/\\bimponując(y|a|e|o)\\b/gi',
      '/\\brewolucyjn(y|a|e)\\b/gi',
      '/\\bkliknij tutaj\\b/gi',
      '/\\bkup teraz\\b/gi',
      '/\\boferta (ograniczona|limitowana) (czasowo|ilościowo)?\\b/gi',
      '/\\bnie czekaj\\b/gi',
      '/\\bbez ryzyka\\b/gi',
      '/\\bzarób (pieniądze|gotówkę)\\b/gi',
      '/\\budowodnione (rezultaty|wyniki|efekty)\\b/gi',
      '/\\bpromocja specjalna\\b/gi',
      '/\\bnajlepsz(a|e|y) (oferta|cena|okazja)\\b/gi',
      '/\\bniezbędny\\b/gi',
      '/\\bna (wyższy|następny|kolejny) poziom\\b/gi',
      '/\\bw (pigułce|telegraficznym skrócie)\\b/gi',
      '/\\bzasadniczo\\b/gi',
      '/\\bfantastyczn(y|a|e|ie)\\b/gi',
      '/\\bspektakularn(y|a|e|ie)\\b/gi',
      '/\\bnie przegap\\b/gi',
      '/\\bpośpiesz się\\b/gi',
      '/\\bzacznij (dziś|teraz|za darmo)\\b/gi',
      '/\\bprzekształć (swoje |)(życie|biznes|karierę)\\b/gi',
      '/\\bzmień swoje życie\\b/gi'
    ]
  }
};
