// De-Slop Portuguese (pt) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for Portuguese-language content
// ChatGPT in Portuguese has distinctive overused phrases - these are the real ones
// Covers both European Portuguese (pt-PT) and Brazilian Portuguese (pt-BR)

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.pt = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in Portuguese - phrases that appear constantly in LLM-generated Portuguese text
  tier1: [
    // Signature ChatGPT Portuguese phrases - the most blatant tells
    /\bno (cenário|panorama) em constante (mudança|evolução|transformação)\b/gi,
    /\bcenário (em constante|sempre em|perpetuamente em) (mudança|evolução|transformação)\b/gi,
    /\bnavegar (pelo|por este|neste) (complexo )?(cenário|mundo|ambiente|panorama)\b/gi,
    /\bmergulhando nas (complexidades|profundezas|nuances) (de|da|do)\b/gi,
    /\bmergulhar (em|nas|nos) (complexidades|profundezas|detalhes)\b/gi,
    /\buma jornada transformadora\b/gi,
    /\bembarcar (nesta|em uma|numa) jornada\b/gi,
    /\btapeçaria de\b/gi,
    /\bé (importante|essencial|fundamental|crucial) (notar|observar|destacar|ressaltar|compreender) que\b/gi,
    /\bcabe (notar|observar|destacar|ressaltar|mencionar) que\b/gi,
    /\bno final das contas,? a (escolha|decisão) é (sua|tua|de vocês)\b/gi,
    /\babordagem (holística|integral|abrangente)\b/gi,
    /\bintegra(r|r-se|ção) (de forma|de maneira) (transparente|perfeita|harmoniosa|fluida)\b/gi,
    /\bdesbloquear (o potencial|novas possibilidades|o poder)\b/gi,
    /\bfomentar (a inovação|o crescimento|a colaboração)\b/gi,
    /\bnuances? (de compreensão|da abordagem|da perspectiva)\b/gi,
    /\batenção meticulosa\b/gi,
    /\bpaisagem em (constante|rápida|contínua) evolução\b/gi,
    /\bambiente (dinâmico|em mudança|em evolução)\b/gi,
    /\bpapel (fundamental|crucial|essencial|central)\b/gi,
    /\bno grande esquema das coisas\b/gi,
    /\bpilares? (fundamentais?|chave|essenciais?)\b/gi,
    /\bprincipais? (aprendizados?|lições?|conclusões?)\b/gi,
    /\bexplorar (as|as )?(diversas? )?(facetas?|dimensões?) (de|da|do)\b/gi,
    /\bpotencial transformador\b/gi,
    /\bmudar o jogo\b/gi,
    /\bvirada de jogo\b/gi,
    /\bmudança de paradigma\b/gi,
    /\bsem precedentes\b/gi,
    /\bsolução (robusta|completa|sólida|abrangente)\b/gi,
    /\bguia (completo|abrangente|definitivo|detalhado)\b/gi,
    /\baproveit(ar|ando) o poder\b/gi,
    /\bneste (artigo|post|texto),? (vamos|iremos|exploraremos|analisaremos)\b/gi,
    /\bao longo (deste|do) (artigo|post|texto)\b/gi,
    /\bcomo (modelo de linguagem|assistente de IA)\b/gi,
    /\bnão (pode|deve) ser (subestimada?|ignorada?)\b/gi,
    /\baprofundar[- ]se em\b/gi,
    /\biluminar (a questão|o tema|o assunto)\b/gi,
    /\bsem igual\b/gi,
    /\btesouro (de informações|de recursos|de conhecimento)\b/gi,
    /\bterritório inexplorado\b/gi,
    /\bde ponta\b/gi,
    /\ba próxima fronteira\b/gi,
    /\binstigante\b/gi,
    /\bno final das contas\b/gi,
    /\bpor fim\b/gi,
    /\bem conclusão\b/gi,
    /\bem (resumo|síntese)\b/gi,
    /\bpara resumir\b/gi,
    /\bpensando no futuro\b/gi,
    /\bavançando\b/gi,

    // Structural patterns in Portuguese
    /^(Em conclusão|Em resumo|Para resumir|Em definitivo|Resumindo),?\s/mi,
    /\bNão apenas .{10,50} mas (também|como também)?\b/gi,
    /\bApesar de (seus|sua|os|as) .{5,30},? .{5,30} (enfrenta|apresenta) desafios\b/gi,
    /\bPerspectivas (futuras?|para o futuro):?\b/gi,

    // AI antithesis patterns in Portuguese
    /\bNão se trata (apenas|somente|simplesmente) de .{5,40}[,;] trata[- ]se de\b/gi,
    /\bNão é .{5,40}[,;] é .{5,40}\b/gi,
    /\bNão .{5,40}[,;] mas sim .{5,40}\b/gi,
    /\bMenos .{5,30}[,;] mais .{5,30}\b/gi,
    /\bEsqueça .{5,30}[,;] (abrace|pense em|concentre[- ]se em) .{5,30}\b/gi,

    // Excessive transition words (Portuguese)
    /\b(Além disso|Por outro lado|Ademais|Consequentemente|No entanto|Contudo|Entretanto),?\s/gi,
    /\b(É importante|É essencial|É fundamental|Vale (notar|destacar|ressaltar)) que\b/gi,
    /\b(Nem é preciso dizer|Desnecessário dizer|Claro que) que\b/gi,

    // Generic openers in Portuguese
    /^No mundo (de hoje|atual|moderno),?\s/mi,
    /^(Em|Com|Através de|Durante|Desde) .{20,60}(continua a|tornou[- ]se|está se tornando)\b/mi,

    // Listicle patterns in Portuguese
    /\b\d+\s+(formas|razões|dicas|truques|segredos|benefícios|vantagens)\s+(de|para)\b/gi,
    /\bAs?\s+(melhores?|principais?)\s+\d+\b/gi,
    /\bGuia (definitivo|completo|abrangente) (de|para|sobre)\b/gi,
    /\bTudo o que você (precisa|deve) saber (sobre|acerca de)\b/gi,
    /\bGuia (para iniciantes|do iniciante) (sobre|de|para)\b/gi,

    // Unearned profundity in Portuguese
    /\bAlgo (mudou|havia mudado)\b/gi,
    /\bTudo (mudou|havia mudado)\b/gi,
    /\bMas eis (o ponto|a questão|o fato)\b/gi,
    /\bIsso é o que (aprendi|aprendemos)\b/gi,

    // AI content mill phrases in Portuguese
    /\bavanços? (revolucionário|sem precedentes)\b/gi,
    /\bsalto (gigante|quântico|monumental)\b/gi,
    /\bpossibilidades (emocionantes|empolgantes|incríveis)\b/gi,
    /\bpasso (vertiginoso|acelerado|alucinante)\b/gi,
    /\btecnologia (avançada|de ponta|ultramoderna)\b/gi,
    /\bresultados (surpreendentes|impressionantes|extraordinários)\b/gi,
    /\bimpacto (real|no mundo real|tangível|concreto)\b/gi,
    /\bé evidente que\b/gi,
    /\bde .{5,30} a .{5,30}, (isso|esta|este)\b/gi,
    /\bImagine .{10,50} — é isso\b/gi,
    /\bHá (décadas|anos), .{10,50} (parecia|pareciam)\b/gi,

    // Additional AI tells in Portuguese
    /\bo cenário (muda|evolui|se transforma) (constantemente|rapidamente|continuamente)\b/gi,
    /\bcrucial (entender|notar|reconhecer|compreender)\b/gi,
    /\bvital (entender|notar|reconhecer|compreender)\b/gi,
    /\bimportante (entender|notar|reconhecer|lembrar) que\b/gi,
    /\bvale (a pena )?(mencionar|notar|ressaltar) que\b/gi,
    /\bdeve[- ]se (considerar|entender|reconhecer)\b/gi,
    /\bhistórico comprovado\b/gi,
    /\btradição (arraigada|consolidada|de longa data)\b/gi,
    /\bolhar para o futuro\b/gi,
    /\bmoldar o futuro (de|da|do)\b/gi,
    /\bpronto para (se tornar|transformar|revolucionar)\b/gi,
    /\bà (beira|limiar|beirada) de\b/gi,
    /\banunciar uma nova (era|época|fase)\b/gi,
    /\bmarca(r)? (um ponto de virada|um momento decisivo)\b/gi,
    /\bponto de virada\b/gi,
    /\bponto de inflexão\b/gi,
    /\btempestade perfeita de\b/gi,
    /\bconvergência de\b/gi,
    /\bintersecção de\b/gi,
    /\bna (vanguarda|encruzilhada) de\b/gi,
    /\bpioneiro(s)? em\b/gi,
    /\bcrescimento exponencial\b/gi,
    /\boportunidade única\b/gi,
    /\bindiscutivelmente\b/gi,
    /\binegavelmente\b/gi,
    /\birrefutavelmente\b/gi,
    /\bsem sombra de dúvida\b/gi,
    /\bdesnecessário dizer\b/gi,
    /\bem poucas palavras\b/gi,
    /\bem suma\b/gi,
    /\bdito isso,\b/gi,
    /\bneste momento\b/gi,
    /\bganhando (tração|impulso|terreno)\b/gi,
    /\bem alta\b/gi,
    /\bcrescimento (explosivo|meteórico|vertiginoso)\b/gi,
    /\bascensão meteórica\b/gi,
    /\bcrescimento sem precedentes\b/gi,
    /\bsucesso sem igual\b/gi,
    /\brecorde histórico\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Estou|Estamos) (muito )?(animado|animada|animados|animadas|orgulhoso|orgulhosa|honrado|honrada|feliz|grato|grata|abençoado|abençoada) (em|de|por) (anunciar|compartilhar|apresentar|revelar|contar)\b/gim,
    /^(Não consigo|Não conseguimos) esperar (para|em) (compartilhar|anunciar|apresentar|contar)\b/gim,
    /^(Grandes|Emocionantes|Fantásticas|Incríveis) notícias[!:]/gim,
    /^Acabamos de (lançar|publicar|criar)\b/gim,
    /^(Hoje|Esta semana|Este mês) (estou|estamos) (anunciando|lançando|apresentando|compartilhando)\b/gim,
    /^Animado(a)? (em|de|para) (compartilhar|anunciar|apresentar|revelar)\b/gim,
    /^Orgulhoso(a)? (em|de|para) (compartilhar|anunciar|apresentar|revelar)\b/gim,
    /^Feliz (em|de|para) (compartilhar|anunciar|apresentar|revelar)\b/gim,
    /^Honrado(a)? (em|de|para) (compartilhar|anunciar|apresentar|revelar)\b/gim,
    /^Adivinhem[!?]/gim,
    /^Vocês não vão (acreditar|querer perder)\b/gim,
    /^(Confiram|Confira|Dêem uma olhada em|Dê uma olhada em) (isso|o que)\b/gim,
    /^(Grande|Enorme) anúncio[!:]/gim,
    /^(Finalmente|Por fim)[,!]/gim,
    /^(Últimas notícias|Notícias quentes)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in Portuguese (2 points per match)
  tier2: [
    /\bsinergias?\b/gi,
    /\balavancar\b/gi,
    /\bdar um retorno\b/gi,
    /\bfrutos ao alcance da mão\b/gi,
    /\bmover a agulha\b/gi,
    /\bpensar fora da caixa\b/gi,
    /\bfazer contato\b/gi,
    /\bpivotar\b/gi,
    /\bdisruptiv(o|a|os|as)\b/gi,
    /\bescalar\b/gi,
    /\bágil\b/gi,
    /\bcompetências?[- ]?chave\b/gi,
    /\bpartes? (interessadas?|envolvidas?)\b/gi,
    /\bproposta de valor\b/gi,
    /\blíder de (opinião|pensamento)\b/gi,
    /\bboas práticas?\b/gi,
    /\btransformação digital\b/gi,
    /\bimpulsionado por IA\b/gi,
    /\bbaseado na nuvem\b/gi,
    /\bcentrado (no cliente|nos dados)\b/gi,
    /\bvantagem competitiva\b/gi,
    /\bparticipação de mercado\b/gi,
    /\bROI\b/gi,
    /\bKPI\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\bentregáveis?\b/gi,
    /\bitens? de ação\b/gi,
    /\bempoderamento\b/gi,
    /\bimpulsionar a inovação\b/gi,
    /\botimizar\b/gi,
    /\botimização\b/gi,
    /\bmaximizar\b/gi,
    /\balinhamento\b/gi,
    /\balinha(r|do|mento) (com|a|em)\b/gi,
    /\bcolabora(r|ção)\b/gi,
    /\btransversal\b/gi,
    /\bsolução integrada\b/gi,
    /\bde ponta a ponta\b/gi,
    /\bnativo na nuvem\b/gi,
    /\bconteinerizado\b/gi,
    /\bmicrosserviços\b/gi,
    /\bserverless\b/gi,
    /\borientado a (dados|eventos)\b/gi,
    /\btempo real\b/gi,
    /\balta (disponibilidade|performance|desempenho)\b/gi,
    /\bescalável\b/gi,
    /\bmodular\b/gi,
    /\bflexível\b/gi,
    /\bfácil de usar\b/gi,
    /\bintuitivo\b/gi,
    /\bexperiência do usuário\b/gi,
    /\becossistema (digital|tecnológico)\b/gi,
    /\bplataforma (digital|tecnológica|integrada)\b/gi,
    /\bgestão da mudança\b/gi,
    /\broadmap\b/gi,
    /\bagilidade\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Clichés in Portuguese (1 point per match)
  tier3: [
    /\bgrátis\b/gi,
    /\bgarantido\b/gi,
    /\bincrível\b/gi,
    /\bimpressionante\b/gi,
    /\binacreditável\b/gi,
    /\bespantoso\b/gi,
    /\brevolucionário\b/gi,
    /\bmilagroso\b/gi,
    /\bo melhor da categoria\b/gi,
    /\bde primeira linha\b/gi,
    /\btecnologia de última geração\b/gi,
    /\bclique aqui\b/gi,
    /\bcompre agora\b/gi,
    /\baja (agora|imediatamente)\b/gi,
    /\boferta (por tempo limitado|limitada)\b/gi,
    /\bnão espere\b/gi,
    /\buma vez na vida\b/gi,
    /\bsem compromisso\b/gi,
    /\bsem risco\b/gi,
    /\bdobre sua renda\b/gi,
    /\bganhe dinheiro\b/gi,
    /\bdinheiro rápido\b/gi,
    /\bresultados comprovados\b/gi,
    /\bpromoção especial\b/gi,
    /\beconomize muito\b/gi,
    /\bmelhor (oferta|preço|deal)\b/gi,
    /\bsem custo\b/gi,
    /\bconsulta gratuita\b/gi,
    /\bindispensável\b/gi,
    /\bpróximo nível\b/gi,
    /\belevando o padrão\b/gi,
    /\bse destacar da multidão\b/gi,
    /\bse espalhar como fogo\b/gi,
    /\ba ponta do iceberg\b/gi,
    /\bconteúdo é rei\b/gi,
    /\bcomeçar com força total\b/gi,
    /\bem poucas palavras\b/gi,
    /\bbasicamente\b/gi,
    /\bessencialmente\b/gi,
    /\bna verdade\b/gi,
    /\bfantástico\b/gi,
    /\bespetacular\b/gi,
    /\bfenomenal\b/gi,
    /\bextraordinário\b/gi,
    /\bsensacional\b/gi,
    /\bmaravilhoso\b/gi,
    /\bépico\b/gi,
    /\blendário\b/gi,
    /\bacesso exclusivo\b/gi,
    /\bsomente por convite\b/gi,
    /\bem breve\b/gi,
    /\bnão perca\b/gi,
    /\bFOMO\b/gi,
    /\bmedo de perder algo\b/gi,
    /\bcorra\b/gi,
    /\btruque(s)?\b/gi,
    /\bdicas e truques\b/gi,
    /\bpro[- ]tip(s)?\b/gi,
    /\bhack de vida\b/gi,
    /\bhack de crescimento\b/gi,
    /\bpasso a passo\b/gi,
    /\bsistema (comprovado|testado)\b/gi,
    /\bfácil como\b/gi,
    /\brápido e fácil\b/gi,
    /\bem apenas \d+ (minutos?|horas?|dias?)\b/gi,
    /\bsucesso (da noite para o dia|instantâneo)\b/gi,
    /\bresultados (imediatos|instantâneos)\b/gi,
    /\bcomece (hoje|de graça|agora)\b/gi,
    /\bcadastre[- ]se (agora|de graça)\b/gi,
    /\bjunte[- ]se (agora|de graça|a milhares|a milhões)\b/gi,
    /\b(milhares|milhões|bilhões) de (usuários|clientes|pessoas)\b/gi,
    /\bpremiado\b/gi,
    /\btransforme (sua|a sua) (vida|empresa|carreira)\b/gi,
    /\bmude sua vida\b/gi,
    /\bdesbloqueie (seu|o seu) (potencial|sucesso)\b/gi
  ],

  // Political content patterns - Portuguese/Brazilian political context
  political: [
    /\b(política|político|políticos|políticas|partidário|partidária)\b/gi,
    /\b(democrata|republicano|liberal|conservador|libertário|socialista|comunista|marxista|fascista)\b/gi,
    /\b(esquerda|direita|centro[- ]esquerda|centro[- ]direita|extrema (esquerda|direita))\b/gi,
    /\b(progressista|populista|nacionalista|globalista|bolsonarista|lulista)\b/gi,
    /\b(congresso|senado|câmara dos deputados|supremo tribunal federal|STF|assembleia da república)\b/gi,
    /\b(eleições?|votar|votação|urna|campanha|candidatura|primárias?)\b/gi,
    /\b(legislação|projeto de lei|lei|decreto|veto)\b/gi,
    /\b(impeachment|destituição|julgamento político)\b/gi,
    /\b(presidente|senador|deputado|político|candidato)\b/gi,
    /\b(governo|palácio (do planalto|de belém|da república)|estado)\b/gi,
    /\b(inflação|recessão|depressão|estímulo (econômico)?|plano de recuperação)\b/gi,
    /\b(banco central|taxa (de juros|selic|prime))\b/gi,
    /\b(resgate|dívida pública|teto da dívida)\b/gi,
    /\b(orçamento|déficit|dívida nacional|orçamento público)\b/gi,
    /\b(tarifas?|sanções?|guerra comercial)\b/gi,
    /\b(taxa de desemprego|relatório de emprego)\b/gi,
    /\b(aborto|pró[- ]vida|pró[- ]escolha|direito ao aborto)\b/gi,
    /\b(controle de armas|porte de armas|direito às armas)\b/gi,
    /\b(imigração|crise (migratória|de refugiados)|indocumentado|imigrante ilegal)\b/gi,
    /\b(mudança climática|aquecimento global|pacto verde|transição energética)\b/gi,
    /\b(saúde pública|sistema de saúde|SUS|plano de saúde)\b/gi,
    /\b(reforma fiscal|cortes de impostos?|impostos?|reforma tributária)\b/gi,
    /\b(cultura do cancelamento|wokismo|politicamente correto|identitarismo)\b/gi,
    /\b(diversidade e inclusão|DEI|equidade|cotas raciais)\b/gi,
    /\b(direitos (trans|LGBTQ|de gênero))\b/gi,
    /\b(censura|liberdade de expressão|liberdade de imprensa)\b/gi,
    /\b(patriota|nacionalismo|estado profundo|globalismo)\b/gi,
    /\b(acordem|rebanho|massa adormecida|gado)\b/gi,
    /\b(mídia (corporativa|mainstream)|fake news|notícia falsa|propaganda)\b/gi,
    /\b(conspiração|teoria da conspiração|encobrimento)\b/gi,
    /\b(direitos constitucionais|liberdade|tirania|ditadura)\b/gi,
    /\b(agenda (socialista|globalista)|regime)\b/gi,
    /\b(destruindo (a democracia|o país|a nação))\b/gi,
    /\b(ameaça (à democracia|à liberdade))\b/gi,
    /\b(guerra contra (a igreja|a religião|os valores))\b/gi,
    /\b(PT|PL|MDB|PSDB|PSOL|PP|PDT|Lula|Bolsonaro)\b/gi,
    /\bPS|PSD|BE|CDS|Chega|IL\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'mergulhando nas complexidades': 'explorar, examinar, analisar',
    'navegar pelo cenário': 'entender a situação, explorar o campo',
    'mudança de paradigma': 'mudança importante, transformação fundamental',
    'virada de jogo': 'avanço significativo, desenvolvimento importante',
    'potencial transformador': 'descreve a mudança real que ocorre',
    'desbloquear o potencial': 'permitir, possibilitar, tornar possível',
    'integrar de forma transparente': 'integrar, combinar, trabalhar juntos',
    'abordagem holística': 'método completo, estratégia abrangente',
    'solução robusta': 'sistema confiável, abordagem sólida',
    'aprofundar-se em': 'análise detalhada, exame minucioso',
    'tapeçaria de': 'coleção de, mistura de',
    'sem precedentes': 'explica o que o torna único',
    'pioneiro em': 'inovador, novo, explica a inovação',
    'tesouro de informações': 'coleção, recurso, fonte',
    'território inexplorado': 'território novo, área inexplorada',
    'iluminar a questão': 'explicar, esclarecer, revelar',
    'no final das contas': 'em definitivo, por fim',
    'pensando no futuro': 'no futuro, em seguida, daqui para frente',
    'principais aprendizados': 'pontos principais, resumo, conclusões',
    'avanço sem precedentes': 'explica qual barreira foi superada',
    'é evidente que': 'expresse seu ponto diretamente',
    'estou animado em anunciar': 'anunciar diretamente',
    'orgulhoso de compartilhar': 'compartilhar sem autoelogio',
    'sinergias': 'colaboração, cooperação',
    'alavancar': 'usar, aplicar, aproveitar',
    'dar um retorno': 'fazer acompanhamento, retornar a, revisitar',
    'frutos ao alcance da mão': 'vitórias fáceis, tarefas simples',
    'mover a agulha': 'progredir, gerar impacto',
    'pensar fora da caixa': 'ser criativo, inovar',
    'pivotar': 'mudar de direção, ajustar a estratégia',
    'disruptivo': 'explica o que isso muda',
    'partes interessadas': 'pessoas envolvidas, membros da equipe',
    'líder de opinião': 'especialista, autoridade',
    'boas práticas': 'métodos eficazes',
    'empoderamento': 'permitir, habilitar',
    'otimizar': 'melhorar, aperfeiçoar',
    'incrível': 'use descritores específicos',
    'basicamente': 'remova ou seja mais preciso',
    'essencialmente': 'remova ou seja mais específico'
  },

  checkerSuggestions: {
    'mergulhando nas complexidades': 'Tente: "explorar", "examinar", ou seja específico sobre o que está fazendo',
    'navegar pelo cenário': 'Seja preciso: A que situação ou campo você está se referindo exatamente?',
    'mudança de paradigma': 'Use termos concretos: O que mudou especificamente?',
    'virada de jogo': 'Explique por que é importante em vez de usar jargão',
    'potencial transformador': 'Descreva a transformação real',
    'alavancar': 'Tente: "usar", "aplicar" ou "aproveitar"',
    'sinergias': 'Explique a colaboração ou o benefício real',
    'dar um retorno': 'Diga: "fazer acompanhamento", "retornar a" ou "revisitar"',
    'aprofundar-se em': 'Diga: "análise detalhada" ou "exame minucioso"',
    'desbloquear': 'Seja específico sobre o que se torna possível',
    'de forma transparente': 'Mostre como se integra em vez de afirmar que se integra',
    'robusta': 'Descreva as funcionalidades ou pontos fortes reais',
    'abrangente': 'Liste o que abrange',
    'holística': 'Explique como você considera todos os aspectos',
    'disruptivo': 'Explique o que muda e como',
    'sem precedentes': 'Se for verdade, explique o que o torna único',
    'incrível': 'Use descritores específicos e mensuráveis',
    'estou animado em anunciar': 'Pule o marketing. Anuncie diretamente o que está compartilhando.',
    'orgulhoso de compartilhar': 'Omita o autoelogio. Deixe o conteúdo falar por si mesmo.',
    '—': 'Travessões duplos são um sinal revelador de conteúdo gerado por IA. Use pontuação simples.'
  },

  slopDatabase: [
    { slop: 'mergulhando nas complexidades', better: 'explorar, examinar ou analisar', tier: 'tier1' },
    { slop: 'navegar pelo cenário', better: 'entender a situação, explorar o campo', tier: 'tier1' },
    { slop: 'mudança de paradigma', better: 'mudança importante, transformação fundamental', tier: 'tier1' },
    { slop: 'virada de jogo', better: 'avanço significativo, desenvolvimento importante', tier: 'tier1' },
    { slop: 'potencial transformador', better: 'descreve a mudança real que ocorre', tier: 'tier1' },
    { slop: 'desbloquear o potencial', better: 'permitir, possibilitar, tornar possível', tier: 'tier1' },
    { slop: 'integrar de forma transparente', better: 'integrar, combinar, trabalhar juntos', tier: 'tier1' },
    { slop: 'abordagem holística', better: 'método completo, estratégia abrangente', tier: 'tier1' },
    { slop: 'solução robusta', better: 'sistema confiável, abordagem sólida', tier: 'tier1' },
    { slop: 'aprofundar-se em', better: 'análise detalhada, exame minucioso', tier: 'tier1' },
    { slop: 'tapeçaria de', better: 'coleção de, mistura de', tier: 'tier1' },
    { slop: 'sem precedentes', better: 'raro, incomum, ou explica o que o torna único', tier: 'tier1' },
    { slop: 'pioneiro em', better: 'inovador, novo, ou explica a inovação', tier: 'tier1' },
    { slop: 'tesouro de informações', better: 'coleção, recurso, fonte', tier: 'tier1' },
    { slop: 'território inexplorado', better: 'território novo, área inexplorada', tier: 'tier1' },
    { slop: 'iluminar a questão', better: 'explicar, esclarecer, revelar', tier: 'tier1' },
    { slop: 'no final das contas', better: 'em definitivo, por fim, em conclusão', tier: 'tier1' },
    { slop: 'pensando no futuro', better: 'no futuro, em seguida, daqui para frente', tier: 'tier1' },
    { slop: 'principais aprendizados', better: 'pontos principais, resumo, conclusões', tier: 'tier1' },
    { slop: 'avanço sem precedentes', better: 'explica qual barreira foi superada', tier: 'tier1' },
    { slop: 'é evidente que', better: 'expresse seu ponto diretamente sem o preâmbulo', tier: 'tier1' },
    { slop: 'é importante notar que', better: 'nota que... ou afirme diretamente', tier: 'tier1' },
    { slop: 'estou animado em anunciar', better: 'anunciar diretamente', tier: 'stopwords' },
    { slop: 'orgulhoso de compartilhar', better: 'compartilhar sem o envoltório emocional', tier: 'stopwords' },
    { slop: 'feliz em apresentar', better: 'remova o autoelogio', tier: 'stopwords' },
    { slop: 'sinergias', better: 'colaboração, cooperação, esforço conjunto', tier: 'tier2' },
    { slop: 'alavancar', better: 'usar, aplicar, aproveitar', tier: 'tier2' },
    { slop: 'dar um retorno', better: 'fazer acompanhamento, retornar a, revisitar', tier: 'tier2' },
    { slop: 'frutos ao alcance da mão', better: 'vitórias fáceis, tarefas simples', tier: 'tier2' },
    { slop: 'pivotar', better: 'mudar de direção, ajustar a estratégia', tier: 'tier2' },
    { slop: 'disruptivo', better: 'explica o que muda e como', tier: 'tier2' },
    { slop: 'partes interessadas', better: 'pessoas envolvidas, membros da equipe', tier: 'tier2' },
    { slop: 'líder de opinião', better: 'especialista, autoridade', tier: 'tier2' },
    { slop: 'boas práticas', better: 'métodos eficazes, abordagens comprovadas', tier: 'tier2' },
    { slop: 'empoderamento', better: 'permitir, habilitar, dar autonomia', tier: 'tier2' },
    { slop: 'otimizar', better: 'melhorar, aperfeiçoar, tornar mais eficiente', tier: 'tier2' },
    { slop: 'incrível', better: 'use descritores específicos e mensuráveis', tier: 'tier3' },
    { slop: 'espantoso', better: 'forneça detalhes concretos', tier: 'tier3' },
    { slop: 'revolucionário', better: 'descreva a mudança real', tier: 'tier3' },
    { slop: 'basicamente', better: 'remova ou seja mais preciso', tier: 'tier3' },
    { slop: 'essencialmente', better: 'remova ou seja mais específico', tier: 'tier3' },
    { slop: 'travessão (—)', better: 'use pontos, vírgulas ou remova a pausa dramática', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\bno (cenário|panorama) em constante (mudança|evolução|transformação)\\b/gi',
      '/\\bcenário (em constante|sempre em|perpetuamente em) (mudança|evolução|transformação)\\b/gi',
      '/\\bnavegar (pelo|por este|neste) (complexo )?(cenário|mundo|ambiente|panorama)\\b/gi',
      '/\\bmergulhando nas (complexidades|profundezas|nuances) (de|da|do)\\b/gi',
      '/\\buma jornada transformadora\\b/gi',
      '/\\btapeçaria de\\b/gi',
      '/\\bé (importante|essencial|fundamental|crucial) (notar|observar|destacar|ressaltar|compreender) que\\b/gi',
      '/\\bcabe (notar|observar|destacar|ressaltar|mencionar) que\\b/gi',
      '/\\babordagem (holística|integral|abrangente)\\b/gi',
      '/\\bdesbloquear (o potencial|novas possibilidades|o poder)\\b/gi',
      '/\\bmudança de paradigma\\b/gi',
      '/\\bsem precedentes\\b/gi',
      '/\\bsolução (robusta|completa|sólida|abrangente)\\b/gi',
      '/\\bguia (completo|abrangente|definitivo|detalhado)\\b/gi',
      '/\\bpotencial transformador\\b/gi',
      '/\\bmudar o jogo\\b/gi',
      '/\\baprofundar[- ]se em\\b/gi',
      '/\\biluminar (a questão|o tema|o assunto)\\b/gi',
      '/\\bsem igual\\b/gi',
      '/\\bno final das contas\\b/gi',
      '/\\bem conclusão\\b/gi',
      '/\\bem (resumo|síntese)\\b/gi',
      '/\\bpensando no futuro\\b/gi',
      '/\\bprincipais? (aprendizados?|lições?|conclusões?)\\b/gi',
      '/\\b(Além disso|Por outro lado|Ademais|Consequentemente|No entanto|Contudo|Entretanto),?\\s/gi',
      '/\\b(É importante|É essencial|É fundamental|Vale (notar|destacar|ressaltar)) que\\b/gi',
      '/\\bcrescimento exponencial\\b/gi',
      '/\\bponto de virada\\b/gi',
      '/\\bconvergência de\\b/gi',
      '/\\bé evidente que\\b/gi',
      '/^No mundo (de hoje|atual|moderno),?\\s/mi',
      '/\\bindiscutivelmente\\b/gi',
      '/\\bsem sombra de dúvida\\b/gi'
    ],
    tier2: [
      '/\\bsinergias?\\b/gi',
      '/\\balavancar\\b/gi',
      '/\\bdar um retorno\\b/gi',
      '/\\bpivotar\\b/gi',
      '/\\bdisruptiv(o|a|os|as)\\b/gi',
      '/\\bescalar\\b/gi',
      '/\\bágil\\b/gi',
      '/\\bcompetências?[- ]?chave\\b/gi',
      '/\\bpartes? (interessadas?|envolvidas?)\\b/gi',
      '/\\bproposta de valor\\b/gi',
      '/\\blíder de (opinião|pensamento)\\b/gi',
      '/\\bboas práticas?\\b/gi',
      '/\\btransformação digital\\b/gi',
      '/\\bimpulsionado por IA\\b/gi',
      '/\\bcentrado (no cliente|nos dados)\\b/gi',
      '/\\bvantagem competitiva\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI\\b/gi',
      '/\\bempoderamento\\b/gi',
      '/\\botimizar\\b/gi',
      '/\\botimização\\b/gi',
      '/\\bmaximizar\\b/gi',
      '/\\balinhamento\\b/gi',
      '/\\bcolabora(r|ção)\\b/gi',
      '/\\bsolução integrada\\b/gi',
      '/\\bescalável\\b/gi',
      '/\\bfácil de usar\\b/gi',
      '/\\bintuitivo\\b/gi',
      '/\\becossistema (digital|tecnológico)\\b/gi',
      '/\\bgestão da mudança\\b/gi'
    ],
    tier3: [
      '/\\bgrátis\\b/gi',
      '/\\bgarantido\\b/gi',
      '/\\bincrível\\b/gi',
      '/\\bimpressionante\\b/gi',
      '/\\binacreditável\\b/gi',
      '/\\brevolucionário\\b/gi',
      '/\\bclique aqui\\b/gi',
      '/\\bcompre agora\\b/gi',
      '/\\boferta (por tempo limitado|limitada)\\b/gi',
      '/\\bnão espere\\b/gi',
      '/\\bsem risco\\b/gi',
      '/\\bganhe dinheiro\\b/gi',
      '/\\bresultados comprovados\\b/gi',
      '/\\bpromoção especial\\b/gi',
      '/\\bmelhor (oferta|preço|deal)\\b/gi',
      '/\\bindispensável\\b/gi',
      '/\\bpróximo nível\\b/gi',
      '/\\bem poucas palavras\\b/gi',
      '/\\bbasicamente\\b/gi',
      '/\\bessencialmente\\b/gi',
      '/\\bfantástico\\b/gi',
      '/\\bespetacular\\b/gi',
      '/\\bnão perca\\b/gi',
      '/\\bcorra\\b/gi',
      '/\\bcomece (hoje|de graça|agora)\\b/gi',
      '/\\btransforme (sua|a sua) (vida|empresa|carreira)\\b/gi'
    ]
  }
};
