// De-Slop Swedish (sv) Pattern Definitions
// AI slop, corporate buzzwords, and marketing spam patterns for Swedish-language content
// ChatGPT in Swedish has distinctive overused phrases - these are the real ones

window.DESLOP_PATTERNS = window.DESLOP_PATTERNS || {};
window.DESLOP_PATTERNS.sv = {

  // === DETECTION PATTERNS (used by content.js) ===

  // LOW AGGRO TIER (Tier 1) - AI-Specific Indicators (3 points per match)
  // ChatGPT-isms in Swedish - phrases that appear constantly in LLM-generated Swedish text
  tier1: [
    // Signature ChatGPT Swedish phrases - the most blatant tells
    /\bi det (ständigt föränderliga|dynamiska|komplexa|snabbt föränderliga) landskapet\b/gi,
    /\blandskapet (som ständigt|alltid) (förändras|utvecklas|omvandlas)\b/gi,
    /\bnavigera (det|i det|detta) (komplexa )?(landskapet|världen|miljön)\b/gi,
    /\bfördjupa oss i\b/gi,
    /\ben djupare (förståelse|inblick|genomgång) (av|i)\b/gi,
    /\ben transformativ (resa|utveckling|upplevelse)\b/gi,
    /\bge oss ut på (denna|en|vår) resa\b/gi,
    /\bväv(nad)? av\b/gi,
    /\bdet är (viktigt|avgörande|väsentligt|nödvändigt) att (notera|påpeka|framhålla|beakta|förstå) att\b/gi,
    /\bdet bör (noteras|påpekas|framhållas|nämnas) att\b/gi,
    /\bi slutändan (ligger|är) (valet|beslutet) (hos dig|ditt|ert)\b/gi,
    /\bholistiskt (angreppssätt|perspektiv|synsätt)\b/gi,
    /\bsömlöst (integrera|sammanfoga|sammanlänka|förena)\b/gi,
    /\bfrigöra (potentialen|nya möjligheter|kraften)\b/gi,
    /\bfrämja (innovation|tillväxt|samarbete)\b/gi,
    /\bnyanserad (förståelse|bild|perspektiv)\b/gi,
    /\bnoggrann (uppmärksamhet|omsorg|analys)\b/gi,
    /\bständigt (föränderlig|utvecklande|skiftande) (värld|miljö|omgivning)\b/gi,
    /\bdynamisk(t|a)? (miljö|landskap|ekosystem|omgivning)\b/gi,
    /\ben (central|avgörande|väsentlig|viktig|nyckel-?) roll\b/gi,
    /\bi det stora hela\b/gi,
    /\bhörnsten(ar)? (i|av|för)\b/gi,
    /\bviktiga (insikter|lärdomar|slutsatser)\b/gi,
    /\butforska de (olika|mångfaldiga) (aspekterna|facetterna|sidorna) av\b/gi,
    /\btransformativ (potential|kraft|kapacitet)\b/gi,
    /\bbanbrytande\b/gi,
    /\bparadigmskifte\b/gi,
    /\butan motstycke\b/gi,
    /\brobust lösning\b/gi,
    /\bövergripande (guide|vägledning|genomgång)\b/gi,
    /\butnyttja kraften (i|av|hos)\b/gi,
    /\bi (denna|den här) (artikeln|texten|genomgången) (ska vi|kommer vi att|tittar vi på)\b/gi,
    /\bgenom (hela|denna|den här) (artikeln|texten|genomgången)\b/gi,
    /\bsom (språkmodell|AI-assistent)\b/gi,
    /\bkan inte (underskattas|ignoreras|nog betonas)\b/gi,
    /\bdyka (djupare |ner )?(i|in i)\b/gi,
    /\bkasta ljus över\b/gi,
    /\bsaknar motstycke\b/gi,
    /\bskattgömma av (information|resurser|kunskap)\b/gi,
    /\boutforskad mark\b/gi,
    /\bsenaste (tekniken|teknologin)\b/gi,
    /\bi framkant\b/gi,
    /\bnästa gräns\b/gi,
    /\btankeväckande\b/gi,
    /\bi slutändan\b/gi,
    /\bavslutningsvis\b/gi,
    /\bsammanfattningsvis\b/gi,
    /\bfrämåtblickande\b/gi,
    /\bblicka framåt\b/gi,
    /\bmed blicken riktad framåt\b/gi,

    // Structural patterns in Swedish
    /^(Avslutningsvis|Sammanfattningsvis|Slutligen|Sammantaget),?\s/mi,
    /\bInte bara .{10,50} utan (även|också|dessutom)\b/gi,
    /\bTrots (sina|dess|de) .{5,30},? .{5,30} (står|möter) (inför )?(utmaningar|hinder)\b/gi,
    /\bFramtidsutsikter:?\b/gi,

    // AI antithesis patterns in Swedish
    /\bDet handlar inte (bara|enbart|blott) om .{5,40}[,;] (det handlar|utan) (också )?om\b/gi,
    /\bDet (är|handlar) inte .{5,40}[,;] (det är|utan) .{5,40}\b/gi,
    /\bInte .{5,40}[,;] utan .{5,40}\b/gi,
    /\bMindre .{5,30}[,;] mer .{5,30}\b/gi,
    /\bGlöm .{5,30}[,;] (omfamna|tänk på|fokusera på) .{5,30}\b/gi,

    // Excessive transition words (Swedish) - ChatGPT overuses these heavily
    /\b(Dessutom|Vidare|Därtill|Följaktligen|Icke desto mindre|Likväl),?\s/gi,
    /\b(Det (bör|ska) (noteras|påpekas|framhållas)|Det är värt att (notera|nämna|påpeka|beakta)) att\b/gi,
    /\b(Det (säger sig självt|behöver inte sägas|torde vara uppenbart)) att\b/gi,

    // Generic openers in Swedish
    /^I (dagens|vår|den moderna|vår samtida) (värld|tid|samhälle|era),?\s/mi,
    /^(I|Med|Genom|Under) .{20,60}(ökar|har (blivit|utvecklats)|blir allt viktigare)\b/mi,

    // Listicle patterns in Swedish
    /\b\d+\s+(sätt|anledningar|tips|tricks|hemligheter|fördelar|vinster)\s+(att|för att|som)\b/gi,
    /\bDe (bästa|främsta|viktigaste)\s+\d+\b/gi,
    /\bDen ultimata (guiden|vägledningen) (till|för|om)\b/gi,
    /\bAllt du (behöver|bör) veta (om|kring|angående)\b/gi,
    /\bNybörjarguide(n)? (till|för|om)\b/gi,

    // Unearned profundity in Swedish
    /\bNågot (förändrades|har förändrats)\b/gi,
    /\bAllt (förändrades|har förändrats)\b/gi,
    /\bMen här (är|kommer) (det|poängen|nyckeln)\b/gi,
    /\bDet (här|detta) är vad (jag|vi) lärde (oss|mig)\b/gi,

    // AI content mill phrases in Swedish
    /\bgenombrott utan motstycke\b/gi,
    /\bjättekliv (framåt)?\b/gi,
    /\bspännande (möjligheter|utsikter|chanser)\b/gi,
    /\bsvindlande (tempo|hastighet|takt)\b/gi,
    /\bavancerad (teknik|teknologi|metod|lösning)\b/gi,
    /\bimponerande (resultat|framsteg|prestationer)\b/gi,
    /\bpåverkan (i|på) den (verkliga|reella) världen\b/gi,
    /\bdet (är|står) klart att\b/gi,
    /\bfrån .{5,30} till .{5,30}, (detta|detta|den här|det här)\b/gi,
    /\bFöreställ dig .{10,50} — det är\b/gi,
    /\bI (årtionden|decennier|år), .{10,50} (verkade|tycktes)\b/gi,

    // Additional AI tells in Swedish
    /\blandskapet (förändras|utvecklas|omvandlas) (ständigt|snabbt|kontinuerligt)\b/gi,
    /\bavgörande (att förstå|att notera|att inse|att beakta)\b/gi,
    /\bviktigt (att förstå|att notera|att inse|att komma ihåg) att\b/gi,
    /\bdet är värt att (nämna|påpeka|betona) att\b/gi,
    /\bman (måste|bör) (beakta|överväga|inse)\b/gi,
    /\bbevisad meritlista\b/gi,
    /\blångvarig (tradition|praxis|historia)\b/gi,
    /\bblicka (mot|in i) framtiden\b/gi,
    /\bforma (framtiden|morgondagen) (för|av)\b/gi,
    /\bredo att (bli|omvandla|revolutionera)\b/gi,
    /\bpå (tröskeln|randen|gränsen) till\b/gi,
    /\binleda en ny (era|epok|tid)\b/gi,
    /\bmarkera(r)? en vändpunkt\b/gi,
    /\bvändpunkt\b/gi,
    /\bperfekt storm av\b/gi,
    /\bkonvergens av\b/gi,
    /\bskärningspunkt(en)? (mellan|av|för)\b/gi,
    /\bi (framkant|spetsen|korsningen) (av|för)\b/gi,
    /\bpionjär(er)? (inom|för|av)\b/gi,
    /\bexponentiell (tillväxt|ökning|utveckling)\b/gi,
    /\bunik (möjlighet|chans|tillfälle)\b/gi,
    /\botvivelaktigt\b/gi,
    /\bonekligen\b/gi,
    /\bobestridligen\b/gi,
    /\butan tvekan\b/gi,
    /\bdet (säger sig|torde vara) självt\b/gi,
    /\bkort sagt\b/gi,
    /\bmed andra ord\b/gi,
    /\bi grund och botten\b/gi,
    /\bvid denna tidpunkt\b/gi,
    /\bfå (genomslag|fart|fotfäste)\b/gi,
    /\bpå uppgång\b/gi,
    /\bexplosiv tillväxt\b/gi,
    /\bmeteorisk (uppgång|utveckling)\b/gi,
    /\btillväxt utan motstycke\b/gi,
    /\bframgång utan motstycke\b/gi,
    /\brekordartad (tillväxt|ökning)\b/gi,

    // Swedish-specific ChatGPT tells - overuse of formal/stiff constructions
    /\bdet (kan|bör) (framhållas|konstateras|understrykas|betonas) att\b/gi,
    /\bav (avgörande|central|stor|yttersta) (betydelse|vikt)\b/gi,
    /\bär av (yttersta|största|högsta) vikt\b/gi,
    /\ben (mångfacetterad|mångdimensionell) (fråga|utmaning|problematik)\b/gi,
    /\bi (ljuset|skenet) av\b/gi,
    /\bmed (hänsyn|avseende) (till|på)\b/gi,
    /\bdet (råder|finns) (ingen|knappast någon) tvekan om att\b/gi,
    /\bspelar en (oumbärlig|oundgänglig) roll\b/gi,
    /\bnyanserna (i|av|kring)\b/gi,
    /\ben gedigen (grund|bas|plattform) (för|till)\b/gi,
    /\bi en (alltmer|allt mer) (globaliserad|digitaliserad|uppkopplad) (värld|tid)\b/gi,
    /\bför att (fullt ut|till fullo) (förstå|uppskatta|ta till sig)\b/gi,
    /\bden (underliggande|bakomliggande) (orsaken|mekanismen|dynamiken)\b/gi,
    /\bi (takt|samklang) med\b/gi
  ],

  // Marketing engagement stop words (separate toggle)
  stopWords: [
    /^(Jag är|Vi är) (mycket )?(glad|glada|stolt|stolta|hedrad|hedrade|exalterad|exalterade|tacksam|tacksamma) (att|över att) (meddela|dela|presentera|avslöja|berätta)/gim,
    /^(Jag kan|Vi kan) inte (vänta|bärga oss) (med att|att) (dela|berätta|meddela|presentera|avslöja)/gim,
    /^(Stora|Spännande|Fantastiska|Otroliga) nyheter[!:]/gim,
    /^Precis (lanserat|släppt|startat)\b/gim,
    /^(Idag|Denna vecka|Denna månad) (är jag|är vi) (glad|glada|stolt|stolta) (att|över att) (meddela|dela|presentera)\b/gim,
    /^Exalterad(e)? (att|över att) (dela|meddela|presentera|avslöja)\b/gim,
    /^Stolt(a)? (att|över att) (dela|meddela|presentera|avslöja)\b/gim,
    /^Glad(a)? (att|över att) (dela|meddela|presentera|avslöja)\b/gim,
    /^Hedrad(e)? (att|över att) (dela|meddela|presentera|avslöja)\b/gim,
    /^Gissa vad[!?]/gim,
    /^Ni (kommer|ska) inte (tro|kunna tro)\b/gim,
    /^(Titta|Kolla|Se) (på )?(detta|det här|vad)\b/gim,
    /^(Stor|Enorm) nyhet[!:]/gim,
    /^(Äntligen|Till slut)[,!]/gim,
    /^(Senaste nytt|Nyhetsflash)[!:]/gim
  ],

  // Em dash patterns (language-agnostic - copied from English)
  emDash: [
    /—.{10,100}—/g,
    /—/g
  ],

  // EMOJI PATTERNS (language-agnostic - copied from English)
  emoji: [
    /[\u{1F300}-\u{1F9FF}][\s]*Revolutioniz(e|ing)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Transform(ing|ative|ation)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Innovati(ng|on|ve)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Disrupt(ing|ive|ion)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game[- ]changer/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unlock(ing)? (the|your)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Navigating the/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Building (the future|tomorrow)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leading the (way|charge)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (barriers|boundaries)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Exciting (news|announcement|times)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Proud to (announce|share|present)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Thrilled to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Honored to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Grateful (for|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blessed to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Humbled (by|to)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Big|Huge|Major) (news|announcement)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Level(ing)? up/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Next level/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Taking (it|things) to/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Raising the bar/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pushing boundaries/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Breaking (new )?ground/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Making (waves|history|impact)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Changing the game/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shaping the future/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Driving (change|innovation|growth)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Empowering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Inspiring/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Amplifying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Elevating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Scaling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Optimizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Maximizing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Leveraging/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Harnessing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pioneering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Spearheading/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Championing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Crushing (it|goals)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Killing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Nailing it/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Winning/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Slaying/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dominating/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Conquering/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Launching/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Unveiling/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Introducing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Announcing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Revealing/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Dropping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Shipping/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*(New|Fresh) (chapter|journey|adventure)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Milestone (alert|achieved)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Achievement unlocked/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Success story/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Plot twist/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Hot take/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Pro tip/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Life hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Growth hack/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Quick win/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Game plan/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Strategy/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Framework/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Blueprint/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Roadmap/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Masterclass/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Deep dive/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Behind the scenes/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Sneak peek/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Coming soon/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Stay tuned/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*Watch this space/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*More to come/giu,
    /\n[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /^[\u{1F300}-\u{1F9FF}][\s]*[A-Z]/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /([\u{1F300}-\u{1F9FF}])\1{2,}/giu,
    /[\u{1F300}-\u{1F9FF}]{4,}/giu,
    /[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}].{0,30}[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}].{0,50}[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /\.[\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /![\s]*[\u{1F300}-\u{1F9FF}][\s]*/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*\n/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{3,30}[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /👇.{0,30}(link|comment|thread|below)/giu,
    /👆.{0,30}(above|check out)/giu,
    /👉.{0,30}(click|read|check|see)/giu,
    /🔥.{0,30}(hot|fire|lit|amazing)/giu,
    /💡.{0,30}(idea|tip|insight)/giu,
    /🚀.{0,30}(launch|grow|scale|rocket)/giu,
    /💪.{0,30}(strong|power|team)/giu,
    /🎯.{0,30}(target|goal|focus)/giu,
    /⚡.{0,30}(fast|quick|instant)/giu,
    /✨.{0,30}(magic|special|shine)/giu,
    /🌟.{0,30}(star|great|amazing)/giu,
    /💰.{0,30}(money|revenue|profit)/giu,
    /📈.{0,30}(growth|increase|up)/giu,
    /🎉.{0,30}(celebrate|congrat|party)/giu,
    /🎊.{0,30}(celebrate|milestone)/giu,
    /🏆.{0,30}(win|award|champion)/giu,
    /💯.{0,30}(percent|complete|perfect)/giu,
    /🔑.{0,30}(key|secret|unlock)/giu,
    /🎁.{0,30}(gift|bonus|free)/giu,
    /⏰.{0,30}(time|now|urgent|hurry)/giu,
    /🔔.{0,30}(alert|notification|reminder)/giu,
    /📣.{0,30}(announce|news|update)/giu,
    /📢.{0,30}(announce|shout|loud)/giu,
    /💬.{0,30}(comment|discuss|talk)/giu,
    /🤝.{0,30}(partner|collab|together)/giu,
    /❤️.{0,30}(love|passion|care)/giu,
    /🙏.{0,30}(thank|grateful|please)/giu,
    /👏.{0,30}(applaud|congrat|bravo)/giu,
    /🎓.{0,30}(learn|education|graduate)/giu,
    /📚.{0,30}(learn|book|knowledge)/giu,
    /🧠.{0,30}(brain|think|smart|intelligence)/giu,
    /🌍.{0,30}(world|global|international)/giu,
    /🌎.{0,30}(world|global|international)/giu,
    /🌏.{0,30}(world|global|international)/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}][\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /^[\u{1F300}-\u{1F9FF}].{20,200}[\u{1F300}-\u{1F9FF}]$/gmu,
    /[\u{1F300}-\u{1F9FF}][\s]*(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start)/giu,
    /(Click|Comment|Share|Like|Follow|Subscribe|Join|Sign up|Learn more|Read more|Get|Download|Try|Start).{0,20}[\u{1F300}-\u{1F9FF}]/giu,
    /#[a-zA-Z0-9]+[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}]#[a-zA-Z0-9]+/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*.{5,50}\?/giu,
    /.{5,50}\?[\s]*[\u{1F300}-\u{1F9FF}]/giu,
    /[\u{1F300}-\u{1F9FF}][\s]*[A-Z]{4,}/gmu,
    /[A-Z]{4,}[\s]*[\u{1F300}-\u{1F9FF}]/gmu,
    /[\u{1F300}-\u{1F9FF}]/giu
  ],

  // MEDIUM AGGRO TIER (Tier 2) - Corporate & Tech Buzzwords in Swedish (2 points per match)
  tier2: [
    /\bsynergi(er)?\b/gi,
    /\bhävstång(seffekt)?\b/gi,
    /\bfölja upp\b/gi,
    /\blågt hängande frukt(er)?\b/gi,
    /\bflytta nålen\b/gi,
    /\btänka utanför (boxen|lådan|ramarna)\b/gi,
    /\bstämma av\b/gi,
    /\bpivotera\b/gi,
    /\bdisruptiv(t|a)?\b/gi,
    /\bskala (upp|ut)\b/gi,
    /\bagil(t|a)?\b/gi,
    /\bkärnkompetens(er)?\b/gi,
    /\bintressent(er)?\b/gi,
    /\bvärdeproposition\b/gi,
    /\btankeledare?\b/gi,
    /\bbästa praxis\b/gi,
    /\bdigital (transformation|omvandling|omställning)\b/gi,
    /\bAI-driven\b/gi,
    /\bmolnbaserad\b/gi,
    /\bkundcentrerad\b/gi,
    /\bkundorienterad\b/gi,
    /\bkonkurrensfördelar?\b/gi,
    /\bmarknadsandel(ar)?\b/gi,
    /\bROI\b/gi,
    /\bKPI(er)?\b/gi,
    /\bSLA\b/gi,
    /\bMVP\b/gi,
    /\bleverabler?\b/gi,
    /\båtgärdspunkt(er)?\b/gi,
    /\bempowerment\b/gi,
    /\bdriva innovation\b/gi,
    /\boptimera\b/gi,
    /\boptimering\b/gi,
    /\bmaximera\b/gi,
    /\banpassa (till|mot|efter)\b/gi,
    /\bsamarbeta\b/gi,
    /\btvärfunktionell(t|a)?\b/gi,
    /\bheltäckande lösning\b/gi,
    /\bend-to-end[- ]lösning\b/gi,
    /\bmolnativ(t|a)?\b/gi,
    /\bcontainerisera(d|de)?\b/gi,
    /\bmikrotjänst(er)?\b/gi,
    /\bserverlös(t|a)?\b/gi,
    /\bdatadriven\b/gi,
    /\bhändelsestyrd\b/gi,
    /\brealtid(s)?\b/gi,
    /\bhög tillgänglighet\b/gi,
    /\bhög prestanda\b/gi,
    /\bskalbar(t|a)?\b/gi,
    /\bmodulär(t|a)?\b/gi,
    /\bflexibel(t|a)?\b/gi,
    /\banvändarvänlig(t|a)?\b/gi,
    /\bintuitiv(t|a)?\b/gi,
    /\banvändarupplevelse\b/gi,
    /\bdigitalt ekosystem\b/gi,
    /\bplattform (digital|teknisk|integrerad)\b/gi,
    /\bförändringsledning\b/gi,
    /\broadmap\b/gi,
    /\bagilitet\b/gi,
    /\baffärsvärde\b/gi,
    /\bmervärde\b/gi,
    /\bstrategi(sk|ska)? (inriktning|position)\b/gi,
    /\btillväxtresa\b/gi,
    /\bverksamhetsutveckling\b/gi
  ],

  // HIGH AGGRO TIER (Tier 3) - Marketing Cliches in Swedish (1 point per match)
  tier3: [
    /\bgratis\b/gi,
    /\bgaranterad\b/gi,
    /\botrolig(t|a)?\b/gi,
    /\bhäpnadsväckande\b/gi,
    /\bfantastisk(t|a)?\b/gi,
    /\bimponerande\b/gi,
    /\brevolutionerande\b/gi,
    /\bmirakul(ös|öst|ösa)\b/gi,
    /\bbäst i klassen\b/gi,
    /\bförsta klass(ens)?\b/gi,
    /\bsenaste (teknik|teknologi)\b/gi,
    /\bklicka här\b/gi,
    /\bköp nu\b/gi,
    /\bagera (nu|direkt|omedelbart)\b/gi,
    /\bbegränsat erbjudande\b/gi,
    /\bvänta inte\b/gi,
    /\ben gång i livet\b/gi,
    /\butan förpliktelse(r)?\b/gi,
    /\briskfri(tt)?\b/gi,
    /\bfördubbla (din|dina|ditt) (inkomst|intäkter|lön)\b/gi,
    /\btjäna pengar\b/gi,
    /\bsnabba pengar\b/gi,
    /\bbevisade resultat\b/gi,
    /\bspecialerbjudande\b/gi,
    /\bspara stort\b/gi,
    /\blägsta pris(et)?\b/gi,
    /\bbästa (erbjudande|pris|deal)\b/gi,
    /\bgratis (konsultation|rådgivning)\b/gi,
    /\bett måste\b/gi,
    /\btill nästa nivå\b/gi,
    /\bhöja ribban\b/gi,
    /\bsticka ut (ur|från) mängden\b/gi,
    /\bsprida sig som en löpeld\b/gi,
    /\btoppen av isberget\b/gi,
    /\binnehåll är kung\b/gi,
    /\bkomma igång (snabbt|direkt)\b/gi,
    /\bi korthet\b/gi,
    /\bi grund(en)?\b/gi,
    /\begentligen\b/gi,
    /\bfantastisk(t|a)?\b/gi,
    /\bspektakulär(t|a)?\b/gi,
    /\bfenomenal(t|a)?\b/gi,
    /\bextraordinär(t|a)?\b/gi,
    /\bsensationell(t|a)?\b/gi,
    /\böverraskande\b/gi,
    /\bunderbar(t|a)?\b/gi,
    /\bepisk(t|a)?\b/gi,
    /\blegendarisk(t|a)?\b/gi,
    /\bexklusiv tillgång\b/gi,
    /\bendast på inbjudan\b/gi,
    /\bsnart\b/gi,
    /\bmissa inte\b/gi,
    /\bFOMO\b/gi,
    /\brädsla att missa\b/gi,
    /\bskynda dig\b/gi,
    /\btrick(s|et)?\b/gi,
    /\btips och tricks\b/gi,
    /\bpro-tips?\b/gi,
    /\blifehack(s)?\b/gi,
    /\btillväxthack(s)?\b/gi,
    /\bsteg-för-steg[- ](guide|plan|system)\b/gi,
    /\bbeprövat system\b/gi,
    /\benkelt som\b/gi,
    /\bsnabbt och enkelt\b/gi,
    /\bpå bara \d+ (minut(er)?|timm(e|ar)|dag(ar)?)\b/gi,
    /\bframgång över natten\b/gi,
    /\bomedelbara resultat\b/gi,
    /\bbörja (idag|gratis|nu)\b/gi,
    /\bregistrera dig (nu|gratis)\b/gi,
    /\bgå med (nu|gratis|tusentals|miljoner)\b/gi,
    /\b(tusentals|miljoner|miljarder) (användare|kunder|människor)\b/gi,
    /\bprisbelönt\b/gi,
    /\bförändra (ditt|din) (liv|företag|karriär)\b/gi,
    /\bförändra ditt liv\b/gi,
    /\bfrigör din (potential|framgång)\b/gi
  ],

  // Political content patterns - Swedish/Scandinavian political context
  political: [
    /\b(politik|politisk|politiker|partipolitisk)\b/gi,
    /\b(socialdemokrat|moderat|sverigedemokrat|centerpartist|vänsterpartist|liberal|kristdemokrat|miljöpartist)\b/gi,
    /\b(vänster|höger|mitten[- ]vänster|mitten[- ]höger|extremvänster|extremhöger)\b/gi,
    /\b(progressiv|populist(isk)?|nationalist(isk)?|globalist(isk)?)\b/gi,
    /\b(riksdag(en)?|regering(en)?|statsminister|kommun(fullmäktige)?|landsting|region)\b/gi,
    /\b(val|rösta|omröstning|valrörelse|kandidatur|primärval)\b/gi,
    /\b(lagstiftning|lagförslag|proposition|motion|veto)\b/gi,
    /\b(misstroendeförklaring|misstroendevotum|regeringskris)\b/gi,
    /\b(statsminister|minister|riksdagsledamot|partiledare|kandidat)\b/gi,
    /\b(Rosenbad|Riksdagshuset|EU-parlamentet|Bryssel)\b/gi,
    /\b(inflation|recession|lågkonjunktur|stimulanspaket|finanspolitik)\b/gi,
    /\b(Riksbanken|ECB|ränta|styrränta|reporänta)\b/gi,
    /\b(statsskuld|budgetunderskott|räddningspaket)\b/gi,
    /\b(statsbudget(en)?|budgetproposition|finansplan)\b/gi,
    /\b(tullar|sanktioner|handelskrig)\b/gi,
    /\b(arbetslöshet|arbetsmarknad(en)?|sysselsättning)\b/gi,
    /\b(abort|pro-life|valfrihet)\b/gi,
    /\b(vapenkontroll|vapenlagstiftning|vapenlagar)\b/gi,
    /\b(invandring|migrationskris|flyktingkris|asylpolitik|integration)\b/gi,
    /\b(klimatförändring(ar)?|global uppvärmning|grön omställning|klimatpolitik)\b/gi,
    /\b(sjukvård(en)?|välfärd(en)?|offentlig sektor)\b/gi,
    /\b(skattereform|skattesänkning(ar)?|skattetryck)\b/gi,
    /\b(cancelkultur|politisk korrekthet|identitetspolitik|woke)\b/gi,
    /\b(mångfald och inkludering|DEI|jämställdhet)\b/gi,
    /\b((trans|HBTQ|köns)[- ]?rättigheter)\b/gi,
    /\b(censur|yttrandefrihet|tryckfrihet|pressfrihet)\b/gi,
    /\b(patriot|nationalism|djupa staten|globalism)\b/gi,
    /\b(mainstream[- ]media|medieeliten|fake news|propaganda)\b/gi,
    /\b(konspiration|konspirationsteori|mörkläggning)\b/gi,
    /\b(demokrati(n)?|frihet|tyranni|diktatur|auktoritär)\b/gi,
    /\b(socialistisk|kommunistisk) agenda\b/gi,
    /\b(Socialdemokraterna|Moderaterna|Sverigedemokraterna|Centerpartiet|Vänsterpartiet|Liberalerna|Kristdemokraterna|Miljöpartiet)\b/gi,
    /\b(NATO|EU|Norden|nordiskt samarbete)\b/gi
  ],

  // === SUGGESTION MAPS ===

  suggestions: {
    'fördjupa oss i': 'utforska, undersöka, analysera',
    'navigera landskapet': 'förstå situationen, utforska området',
    'paradigmskifte': 'stor förändring, grundläggande omställning',
    'banbrytande': 'betydande framsteg, viktig utveckling',
    'transformativ potential': 'beskriv den faktiska förändringen',
    'frigöra potentialen': 'möjliggöra, tillåta, göra möjligt',
    'sömlöst integrera': 'integrera, kombinera, sammanföra',
    'holistiskt angreppssätt': 'helhetssyn, fullständig strategi',
    'robust lösning': 'tillförlitligt system, solid metod',
    'dyka djupare i': 'detaljerad analys, grundlig genomgång',
    'vävnad av': 'samling av, blandning av',
    'utan motstycke': 'förklara vad som gör det unikt',
    'pionjär inom': 'nyskapande, nytt, förklara innovationen',
    'skattgömma av information': 'samling, resurs, källa',
    'outforskad mark': 'nytt område, outforskat territorium',
    'kasta ljus över': 'förklara, klargöra, belysa',
    'i slutändan': 'slutligen, i förlängningen',
    'framåtblickande': 'i framtiden, härnäst, framöver',
    'viktiga insikter': 'huvudpunkter, sammanfattning, slutsatser',
    'genombrott utan motstycke': 'förklara vilken barriär som bröts',
    'det står klart att': 'uttryck din poäng direkt',
    'jag är glad att meddela': 'meddela direkt',
    'stolt att dela': 'dela utan självberöm',
    'synergier': 'samarbete, samverkan',
    'hävstångseffekt': 'använda, tillämpa, utnyttja',
    'följa upp': 'följa upp, återkomma till, kontrollera',
    'lågt hängande frukt': 'enkla vinster, lätta uppgifter',
    'flytta nålen': 'göra framsteg, skapa effekt',
    'tänka utanför boxen': 'vara kreativ, tänka nytt',
    'pivotera': 'ändra riktning, anpassa strategin',
    'disruptiv': 'förklara vad det förändrar',
    'intressenter': 'berörda parter, teammedlemmar',
    'tankeledare': 'expert, specialist, auktoritet',
    'bästa praxis': 'effektiva metoder',
    'empowerment': 'möjliggöra, ge handlingsutrymme',
    'optimera': 'förbättra, effektivisera',
    'otrolig': 'använd specifika beskrivningar',
    'i grunden': 'ta bort eller var mer precis',
    'egentligen': 'ta bort eller var mer specifik',
    'dessutom': 'ofta onödigt - överanvänt av AI',
    'vidare': 'ofta onödigt - överanvänt av AI'
  },

  checkerSuggestions: {
    'fördjupa oss i': 'Prova: "utforska", "undersöka" eller var specifik om vad du gör',
    'navigera landskapet': 'Var specifik: Vilken situation eller vilket område menar du exakt?',
    'paradigmskifte': 'Använd konkreta termer: Vad har specifikt förändrats?',
    'banbrytande': 'Förklara varför det är viktigt istället för att använda jargong',
    'transformativ potential': 'Beskriv den faktiska förändringen',
    'hävstångseffekt': 'Prova: "använda", "tillämpa" eller "utnyttja"',
    'synergier': 'Förklara det faktiska samarbetet eller nyttan',
    'följa upp': 'Säg: "följa upp", "återkomma till" eller "kontrollera"',
    'dyka djupare i': 'Säg: "detaljerad analys" eller "grundlig genomgång"',
    'frigöra potentialen': 'Var specifik om vad som görs möjligt',
    'sömlöst': 'Visa hur det integreras istället för att påstå det',
    'robust': 'Beskriv de faktiska funktionerna eller styrkorna',
    'övergripande': 'Lista vad det täcker',
    'holistiskt': 'Förklara hur du beaktar alla aspekter',
    'disruptiv': 'Förklara vad det förändrar och hur',
    'utan motstycke': 'Om det stämmer, förklara vad som gör det unikt',
    'otrolig': 'Använd specifika, mätbara beskrivningar',
    'jag är glad att meddela': 'Hoppa över marknadsföringsfluffet. Meddela direkt vad du delar.',
    'stolt att dela': 'Skippa självberömet. Låt innehållet tala för sig självt.',
    '—': 'Tankstreck är ett tydligt tecken på AI-genererat innehåll. Använd enkel interpunktion.'
  },

  slopDatabase: [
    { slop: 'fördjupa oss i', better: 'utforska, undersöka eller analysera', tier: 'tier1' },
    { slop: 'navigera landskapet', better: 'förstå situationen, utforska området', tier: 'tier1' },
    { slop: 'paradigmskifte', better: 'stor förändring, grundläggande omställning', tier: 'tier1' },
    { slop: 'banbrytande', better: 'betydande framsteg, viktig utveckling', tier: 'tier1' },
    { slop: 'transformativ potential', better: 'beskriv den faktiska förändringen', tier: 'tier1' },
    { slop: 'frigöra potentialen', better: 'möjliggöra, tillåta, göra möjligt', tier: 'tier1' },
    { slop: 'sömlöst integrera', better: 'integrera, kombinera, sammanföra', tier: 'tier1' },
    { slop: 'holistiskt angreppssätt', better: 'helhetssyn, fullständig strategi', tier: 'tier1' },
    { slop: 'robust lösning', better: 'tillförlitligt system, solid metod', tier: 'tier1' },
    { slop: 'dyka djupare i', better: 'detaljerad analys, grundlig genomgång', tier: 'tier1' },
    { slop: 'vävnad av', better: 'samling av, blandning av', tier: 'tier1' },
    { slop: 'utan motstycke', better: 'sällsynt, ovanligt, eller förklara vad som gör det unikt', tier: 'tier1' },
    { slop: 'pionjär inom', better: 'nyskapande, nytt, eller förklara innovationen', tier: 'tier1' },
    { slop: 'skattgömma av information', better: 'samling, resurs, källa', tier: 'tier1' },
    { slop: 'outforskad mark', better: 'nytt område, outforskat territorium', tier: 'tier1' },
    { slop: 'kasta ljus över', better: 'förklara, klargöra, belysa', tier: 'tier1' },
    { slop: 'i slutändan', better: 'slutligen, i förlängningen, sammanfattningsvis', tier: 'tier1' },
    { slop: 'framåtblickande', better: 'i framtiden, härnäst, framöver', tier: 'tier1' },
    { slop: 'viktiga insikter', better: 'huvudpunkter, sammanfattning, slutsatser', tier: 'tier1' },
    { slop: 'genombrott utan motstycke', better: 'förklara vilken barriär som bröts', tier: 'tier1' },
    { slop: 'det står klart att', better: 'uttryck din poäng direkt utan preambel', tier: 'tier1' },
    { slop: 'det är viktigt att notera att', better: 'notera att... eller säg det direkt', tier: 'tier1' },
    { slop: 'jag är glad att meddela', better: 'meddela det direkt', tier: 'stopwords' },
    { slop: 'stolt att dela', better: 'dela utan den emotionella inpackningen', tier: 'stopwords' },
    { slop: 'exalterad att presentera', better: 'skippa självberömet', tier: 'stopwords' },
    { slop: 'synergier', better: 'samarbete, samverkan, gemensam insats', tier: 'tier2' },
    { slop: 'hävstångseffekt', better: 'använda, tillämpa, utnyttja', tier: 'tier2' },
    { slop: 'följa upp', better: 'följa upp, återkomma till, kontrollera', tier: 'tier2' },
    { slop: 'lågt hängande frukt', better: 'enkla vinster, lätta uppgifter', tier: 'tier2' },
    { slop: 'pivotera', better: 'ändra riktning, anpassa strategin', tier: 'tier2' },
    { slop: 'disruptiv', better: 'förklara vad det förändrar och hur', tier: 'tier2' },
    { slop: 'intressenter', better: 'berörda parter, teammedlemmar', tier: 'tier2' },
    { slop: 'tankeledare', better: 'expert, specialist, auktoritet', tier: 'tier2' },
    { slop: 'bästa praxis', better: 'effektiva metoder, beprövade tillvägagångssätt', tier: 'tier2' },
    { slop: 'empowerment', better: 'möjliggöra, ge handlingsutrymme, befogenhet', tier: 'tier2' },
    { slop: 'optimera', better: 'förbättra, effektivisera, slipa', tier: 'tier2' },
    { slop: 'otrolig', better: 'använd specifika, mätbara beskrivningar', tier: 'tier3' },
    { slop: 'häpnadsväckande', better: 'ge konkreta detaljer', tier: 'tier3' },
    { slop: 'revolutionerande', better: 'beskriv den faktiska förändringen', tier: 'tier3' },
    { slop: 'i grunden', better: 'ta bort eller var mer precis', tier: 'tier3' },
    { slop: 'egentligen', better: 'ta bort eller var mer specifik', tier: 'tier3' },
    { slop: 'tankstreck (---)', better: 'använd punkter, kommatecken eller ta bort den dramatiska pausen', tier: 'tier1' }
  ],

  // === SETTINGS DEFAULT PATTERNS (string form for pattern editor) ===

  defaultPatterns: {
    tier1: [
      '/\\bi det (ständigt föränderliga|dynamiska|komplexa|snabbt föränderliga) landskapet\\b/gi',
      '/\\blandskapet (som ständigt|alltid) (förändras|utvecklas|omvandlas)\\b/gi',
      '/\\bnavigera (det|i det|detta) (komplexa )?(landskapet|världen|miljön)\\b/gi',
      '/\\bfördjupa oss i\\b/gi',
      '/\\ben djupare (förståelse|inblick|genomgång) (av|i)\\b/gi',
      '/\\ben transformativ (resa|utveckling|upplevelse)\\b/gi',
      '/\\bge oss ut på (denna|en|vår) resa\\b/gi',
      '/\\bväv(nad)? av\\b/gi',
      '/\\bdet är (viktigt|avgörande|väsentligt|nödvändigt) att (notera|påpeka|framhålla|beakta|förstå) att\\b/gi',
      '/\\bholistiskt (angreppssätt|perspektiv|synsätt)\\b/gi',
      '/\\bsömlöst (integrera|sammanfoga|sammanlänka|förena)\\b/gi',
      '/\\bfrigöra (potentialen|nya möjligheter|kraften)\\b/gi',
      '/\\bparadigmskifte\\b/gi',
      '/\\butan motstycke\\b/gi',
      '/\\brobust lösning\\b/gi',
      '/\\bövergripande (guide|vägledning|genomgång)\\b/gi',
      '/\\btransformativ (potential|kraft|kapacitet)\\b/gi',
      '/\\bbanbrytande\\b/gi',
      '/\\bdyka (djupare |ner )?(i|in i)\\b/gi',
      '/\\bkasta ljus över\\b/gi',
      '/\\bsaknar motstycke\\b/gi',
      '/\\bi slutändan\\b/gi',
      '/\\bavslutningsvis\\b/gi',
      '/\\bsammanfattningsvis\\b/gi',
      '/\\bfrämåtblickande\\b/gi',
      '/\\bviktiga (insikter|lärdomar|slutsatser)\\b/gi',
      '/\\b(Dessutom|Vidare|Därtill|Följaktligen|Icke desto mindre|Likväl),?\\s/gi',
      '/\\b(Det (bör|ska) (noteras|påpekas|framhållas)|Det är värt att (notera|nämna|påpeka|beakta)) att\\b/gi',
      '/\\bexponentiell (tillväxt|ökning|utveckling)\\b/gi',
      '/\\bvändpunkt\\b/gi',
      '/\\bkonvergens av\\b/gi',
      '/\\bdet (är|står) klart att\\b/gi',
      '/^I (dagens|vår|den moderna|vår samtida) (värld|tid|samhälle|era),?\\s/mi',
      '/\\botvivelaktigt\\b/gi',
      '/\\butan tvekan\\b/gi'
    ],
    tier2: [
      '/\\bsynergi(er)?\\b/gi',
      '/\\bhävstång(seffekt)?\\b/gi',
      '/\\bfölja upp\\b/gi',
      '/\\bpivotera\\b/gi',
      '/\\bdisruptiv(t|a)?\\b/gi',
      '/\\bskala (upp|ut)\\b/gi',
      '/\\bagil(t|a)?\\b/gi',
      '/\\bkärnkompetens(er)?\\b/gi',
      '/\\bintressent(er)?\\b/gi',
      '/\\bvärdeproposition\\b/gi',
      '/\\btankeledare?\\b/gi',
      '/\\bbästa praxis\\b/gi',
      '/\\bdigital (transformation|omvandling|omställning)\\b/gi',
      '/\\bAI-driven\\b/gi',
      '/\\bkundcentrerad\\b/gi',
      '/\\bkonkurrensfördelar?\\b/gi',
      '/\\bROI\\b/gi',
      '/\\bKPI(er)?\\b/gi',
      '/\\bempowerment\\b/gi',
      '/\\boptimera\\b/gi',
      '/\\boptimering\\b/gi',
      '/\\bmaximera\\b/gi',
      '/\\bsamarbeta\\b/gi',
      '/\\bheltäckande lösning\\b/gi',
      '/\\bskalbar(t|a)?\\b/gi',
      '/\\banvändarvänlig(t|a)?\\b/gi',
      '/\\bintuitiv(t|a)?\\b/gi',
      '/\\bdigitalt ekosystem\\b/gi',
      '/\\bförändringsledning\\b/gi'
    ],
    tier3: [
      '/\\bgratis\\b/gi',
      '/\\bgaranterad\\b/gi',
      '/\\botrolig(t|a)?\\b/gi',
      '/\\bhäpnadsväckande\\b/gi',
      '/\\bimponerande\\b/gi',
      '/\\brevolutionerande\\b/gi',
      '/\\bklicka här\\b/gi',
      '/\\bköp nu\\b/gi',
      '/\\bbegränsat erbjudande\\b/gi',
      '/\\bvänta inte\\b/gi',
      '/\\briskfri(tt)?\\b/gi',
      '/\\btjäna pengar\\b/gi',
      '/\\bbevisade resultat\\b/gi',
      '/\\bspecialerbjudande\\b/gi',
      '/\\bbästa (erbjudande|pris|deal)\\b/gi',
      '/\\bett måste\\b/gi',
      '/\\btill nästa nivå\\b/gi',
      '/\\bi korthet\\b/gi',
      '/\\bi grund(en)?\\b/gi',
      '/\\begentligen\\b/gi',
      '/\\bfantastisk(t|a)?\\b/gi',
      '/\\bspektakulär(t|a)?\\b/gi',
      '/\\bmissa inte\\b/gi',
      '/\\bskynda dig\\b/gi',
      '/\\bbörja (idag|gratis|nu)\\b/gi',
      '/\\bförändra (ditt|din) (liv|företag|karriär)\\b/gi'
    ]
  }
};
